# Generated by Django 5.2 on 2026-05-29 18:13

import core.mixins
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, unique=True)),
                ('account_id', models.CharField(blank=True, help_text='Optional customer account number with the provider', max_length=100, verbose_name='Account ID')),
                ('portal_url', models.URLField(blank=True, help_text="URL for the provider's management/administration portal", verbose_name='Admin Portal URL')),
                ('website', models.URLField(blank=True, help_text='General public website of the provider', verbose_name='Company Website')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary support or account manager email', max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary support phone number', max_length=50, verbose_name='Contact Phone')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional internal administrative notes', verbose_name='Admin Notes')),
                ('support_contact', models.TextField(blank=True, help_text='Additional support contact details (hours, escalation, etc.)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate to hide from selection lists without deleting', verbose_name='Active')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscription_providers', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ('name',),
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Descriptive name (e.g., Adobe Creative Cloud - All Apps (Team))', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, unique=True)),
                ('type', models.CharField(choices=[('saas', 'SaaS'), ('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('other', 'Other')], db_index=True, default='saas', max_length=50, verbose_name='Subscription Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('renewing', 'Renewing'), ('trial', 'Trial')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date')),
                ('renewal_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Renewal Date')),
                ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per renewal period', max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='ISO 4217 currency code (USD, EUR, GBP, AUD, etc.)', max_length=3, verbose_name='Currency')),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('multi_year', 'Multi-Year'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle')),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Duration of the subscription term in months', null=True, verbose_name='Term (Months)')),
                ('auto_renewal', models.BooleanField(default=True, help_text='Whether this subscription renews automatically', verbose_name='Auto-Renewal')),
                ('licensed_quantity', models.PositiveIntegerField(blank=True, help_text='Number of seats/users/devices covered (for SaaS/support)', null=True, verbose_name='Licensed Quantity')),
                ('contract_reference', models.CharField(blank=True, help_text='Contract number, PO reference, or quote ID', max_length=100, verbose_name='Contract Reference')),
                ('cost_center', models.CharField(blank=True, help_text='Financial tracking code for chargeback', max_length=50, verbose_name='Cost Center / Budget Code')),
                ('cancellation_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Cancellation Date')),
                ('description', models.TextField(blank=True, help_text='Optional text detailing coverage or terms')),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes')),
                ('owner', models.ForeignKey(blank=True, help_text='Person responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.provider')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscriptions', to='extras.tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_org', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('-renewal_date', 'provider', 'name'),
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.BookmarkableMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('asset', 'assetholder', 'location', 'consumable', 'accessory')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Assignment',
                'verbose_name_plural': 'Subscription Assignments',
                'ordering': ('-assigned_date',),
                'constraints': [models.UniqueConstraint(fields=('subscription', 'content_type', 'object_id'), name='subscriptions_assignment_unique')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
