# Generated by Django 5.2 on 2025-04-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255, unique=True)),
                ('account_id', models.CharField(blank=True, help_text='Optional customer account number with the provider', max_length=100, verbose_name='Account ID')),
                ('portal_url', models.URLField(blank=True, help_text="Optional URL for the provider's management portal", verbose_name='Portal URL')),
                ('admin_notes', models.TextField(blank=True, help_text='Optional internal administrative notes', verbose_name='Admin Notes')),
                ('support_contact', models.TextField(blank=True, help_text='Optional support contact information (email, phone, etc.)')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscription_providers', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique descriptive name (e.g., Adobe Creative Cloud - All Apps (Team))', max_length=255)),
                ('type', models.CharField(choices=[('saas', 'SaaS'), ('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('other', 'Other')], default='saas', max_length=50, verbose_name='Subscription Type')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Next Renewal Date')),
                ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per renewal period', max_digits=10, null=True)),
                ('term_months', models.PositiveIntegerField(blank=True, help_text='Duration of the subscription term in months', null=True, verbose_name='Term (Months)')),
                ('description', models.TextField(blank=True, help_text='Optional text detailing coverage or terms')),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.provider')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscriptions', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('provider', 'name', 'renewal_date'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Assignment',
                'verbose_name_plural': 'Subscription Assignments',
                'ordering': ('-assigned_date',),
            },
        ),
    ]
