# Generated by Django 5.2 on 2026-05-24 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subscriptions', '0002_subscription_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-renewal_date', 'provider', 'name'), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary support or account manager email', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary support phone number', max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate to hide from selection lists without deleting', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, help_text='General public website of the provider', verbose_name='Company Website'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renewal',
            field=models.BooleanField(default=False, help_text='Whether this subscription renews automatically', verbose_name='Auto-Renewal'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Cancellation Date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='contract_reference',
            field=models.CharField(blank=True, help_text='Contract number, PO reference, or quote ID', max_length=100, verbose_name='Contract Reference'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Financial tracking code for chargeback', max_length=50, verbose_name='Cost Center / Budget Code'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(blank=True, default='USD', help_text='ISO 4217 currency code (USD, EUR, GBP, AUD, etc.)', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='licensed_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats/users/devices covered (for SaaS/support)', null=True, verbose_name='Licensed Quantity'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('renewing', 'Renewing')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='subscriptionassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='portal_url',
            field=models.URLField(blank=True, help_text="URL for the provider's management/administration portal", verbose_name='Admin Portal URL'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='support_contact',
            field=models.TextField(blank=True, help_text='Additional support contact details (hours, escalation, etc.)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(help_text='Descriptive name (e.g., Adobe Creative Cloud - All Apps (Team))', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Renewal Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='subscriptionassignment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('asset', 'assetholder', 'location', 'consumable', 'accessory')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionassignment',
            constraint=models.UniqueConstraint(fields=('subscription', 'content_type', 'object_id'), name='subscriptions_assignment_unique'),
        ),
    ]
