# Generated by Django 5.2 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_options_provider_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Deactivate to hide from selection lists without deleting', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancellation_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Cancellation Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('saas', 'SaaS'), ('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('other', 'Other')], db_index=True, default='saas', max_length=50, verbose_name='Subscription Type'),
        ),
    ]
