# Generated by Django 5.2 on 2026-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_provider_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('multi_year', 'Multi-Year'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle'),
        ),
    ]
