# Generated by Django 5.2.15 on 2026-06-07 18:16

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_asset_purchase_order_line_alter_assetrequest_status'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_allocated', models.PositiveIntegerField(default=1)),
                ('asset_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='assets.assetrequest')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='procurement.purchaseorderline')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_links', to='organization.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset_request', 'purchase_order_line'), name='unique_request_po_line_link')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
