# Generated by Django 5.2.15 on 2026-06-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_fulfillmentlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('receive_purchaseorder', 'Can receive stock from a purchase order'), ('approve_purchaseorder', 'Can approve/submit a purchase order')]},
        ),
    ]
