# Generated by Django 5.2.15 on 2026-06-08 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_alter_assetrole_name_alter_assetrole_slug_and_more'),
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
        ('procurement', '0007_alter_fulfillmentlink_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('order_number',), name='unique_purchaseorder_number_active'),
        ),
    ]
