# Generated by Django 5.2.15 on 2026-06-14 14:52

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0047_assetdisposal'),
        ('organization', '0017_remove_assetholder_unique_tenant_user_profile_and_more'),
        ('procurement', '0009_purchaseorder_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(db_index=True, max_length=100)),
                ('contract_type', models.CharField(choices=[('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('warranty', 'Warranty'), ('service', 'Service'), ('other', 'Other')], default='support', max_length=20, verbose_name='Contract Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total or per-cycle cost', max_digits=12, null=True, verbose_name='Contract Cost')),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('multi_year', 'Multi-Year'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Whether this contract renews automatically', verbose_name='Auto-Renew')),
                ('sla_response_time', models.CharField(blank=True, help_text='e.g. "4 business hours", "Next business day"', max_length=100, verbose_name='SLA Response Time')),
                ('sla_resolution_time', models.CharField(blank=True, help_text='e.g. "8 business hours", "3 business days"', max_length=100, verbose_name='SLA Resolution Time')),
                ('coverage_hours', models.CharField(blank=True, help_text='e.g. "24x7", "9-5 Mon-Fri"', max_length=50, verbose_name='Coverage Hours')),
                ('sla_terms', models.TextField(blank=True, help_text='Full SLA terms or summary text', verbose_name='SLA Terms')),
                ('notes', models.TextField(blank=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='contracts', to='assets.asset', verbose_name='Covered Assets')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='The PO this contract originated from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='procurement.purchaseorder', verbose_name='Purchase Order')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organization.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract_number',), name='unique_contract_number_active'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_date_gte_start_date')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model, core.mixins.TaggableMixin),
        ),
    ]
