# Generated by Django 5.2.15 on 2026-06-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_costcenter'),
        ('procurement', '0010_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='organization.costcenter', verbose_name='Cost Center'),
        ),
    ]
