# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('inventory', '0010_alter_accessory_category_and_more'),
        ('licenses', '0012_alter_license_cost_center_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('procurement', '0011_contract_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Renewal Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='fulfillmentlink',
            name='asset_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='assets.assetrequest', verbose_name='Asset Request'),
        ),
        migrations.AlterField(
            model_name='fulfillmentlink',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='procurement.purchaseorderline', verbose_name='Purchase Order Line'),
        ),
        migrations.AlterField(
            model_name='fulfillmentlink',
            name='qty_allocated',
            field=models.PositiveIntegerField(default=1, verbose_name='Qty Allocated'),
        ),
        migrations.AlterField(
            model_name='fulfillmentlink',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_links', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_orders', to='organization.location', verbose_name='Destination Location'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.accessory', verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='assets.assettype', verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.consumable', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='licenses.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty_ordered',
            field=models.PositiveIntegerField(default=1, verbose_name='Qty Ordered'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty_received',
            field=models.PositiveIntegerField(default=0, verbose_name='Qty Received'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
