# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('procurement', '0002_fulfillmentlink'),
        ('procurement', '0003_alter_purchaseorder_options'),
        ('procurement', '0004_setup_groups'),
        ('procurement', '0005_alter_purchaseorder_status'),
        ('procurement', '0006_purchaseorderline_license'),
        ('procurement', '0007_alter_fulfillmentlink_deleted_at_and_more'),
        ('procurement', '0008_alter_purchaseorder_order_number_and_more'),
        ('procurement', '0009_purchaseorder_currency'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_26_extras_history_7'),
        ('procurement', '0100_issue88_shard_14_procurement_schema'),
    ]

    operations = [

    ]
