# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('procurement', '0001_initial'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_13_assets_history_2'),
    ]

    operations = [
        migrations.CreateModel(
                    name='PurchaseOrder',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('order_number', models.CharField(db_index=True, max_length=100, verbose_name='Order Number')),
                        ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                        ('order_date', models.DateField(blank=True, null=True, verbose_name='Order Date')),
                        ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'permissions': [('receive_purchaseorder', 'Can receive stock from a purchase order'), ('approve_purchaseorder', 'Can approve/submit a purchase order')],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model, core.mixins.TaggableMixin),
                ),
        migrations.CreateModel(
                    name='PurchaseOrderLine',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty_ordered', models.PositiveIntegerField(default=1, verbose_name='Qty Ordered')),
                        ('qty_received', models.PositiveIntegerField(default=0, verbose_name='Qty Received')),
                        ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Contract',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255, verbose_name='Name')),
                        ('contract_number', models.CharField(db_index=True, max_length=100, verbose_name='Contract Number')),
                        ('contract_type', models.CharField(choices=[('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('warranty', 'Warranty'), ('service', 'Service'), ('other', 'Other')], default='support', max_length=20, verbose_name='Contract Type')),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                        ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total or per-cycle cost', max_digits=12, null=True, verbose_name='Contract Cost')),
                        ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                        ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('multi_year', 'Multi-Year'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle')),
                        ('start_date', models.DateField(verbose_name='Start Date')),
                        ('end_date', models.DateField(verbose_name='End Date')),
                        ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Renewal Date')),
                        ('auto_renew', models.BooleanField(default=False, help_text='Whether this contract renews automatically', verbose_name='Auto-Renew')),
                        ('sla_response_time', models.CharField(blank=True, help_text='e.g. "4 business hours", "Next business day"', max_length=100, verbose_name='SLA Response Time')),
                        ('sla_resolution_time', models.CharField(blank=True, help_text='e.g. "8 business hours", "3 business days"', max_length=100, verbose_name='SLA Resolution Time')),
                        ('coverage_hours', models.CharField(blank=True, help_text='e.g. "24x7", "9-5 Mon-Fri"', max_length=50, verbose_name='Coverage Hours')),
                        ('sla_terms', models.TextField(blank=True, help_text='Full SLA terms or summary text', verbose_name='SLA Terms')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                        ('assets', models.ManyToManyField(blank=True, related_name='contracts', to='assets.asset', verbose_name='Covered Assets')),
                        ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='organization.costcenter', verbose_name='Cost Center')),
                        ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.supplier', verbose_name='Supplier')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organization.tenant', verbose_name='Tenant')),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model, core.mixins.TaggableMixin),
                ),
        migrations.CreateModel(
                    name='FulfillmentLink',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty_allocated', models.PositiveIntegerField(default=1, verbose_name='Qty Allocated')),
                        ('asset_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='assets.assetrequest', verbose_name='Asset Request')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_links', to='organization.tenant', verbose_name='Tenant')),
                    ],
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
