# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('procurement', '0010_contract'),
        ('procurement', '0011_contract_cost_center'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_40_organization_history_4'),
        ('procurement', '0100_issue88_shard_27_procurement_history_1'),
    ]

    operations = [

    ]
