# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('procurement', '0012_alter_contract_contract_number_and_more'),
    ]

    dependencies = [
        ('inventory', '0100_issue88_shard_56_inventory_relations'),
        ('procurement', '0100_issue88_shard_41_procurement_history_2'),
    ]

    operations = [
        migrations.AddField(
                    model_name='purchaseorder',
                    name='created_by',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
                ),
        migrations.AddField(
                    model_name='purchaseorder',
                    name='destination_location',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_orders', to='organization.location', verbose_name='Destination Location'),
                ),
        migrations.AddField(
                    model_name='purchaseorder',
                    name='supplier',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='assets.supplier', verbose_name='Supplier'),
                ),
        migrations.AddField(
                    model_name='purchaseorder',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='contract',
                    name='purchase_order',
                    field=models.ForeignKey(blank=True, help_text='The PO this contract originated from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='procurement.purchaseorder', verbose_name='Purchase Order'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='accessory',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.accessory', verbose_name='Accessory'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='asset_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='assets.assettype', verbose_name='Asset Type'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='component',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.component', verbose_name='Component'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='consumable',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.consumable', verbose_name='Consumable'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='license',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='licenses.license', verbose_name='License'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='purchase_order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder', verbose_name='Purchase Order'),
                ),
        migrations.AddField(
                    model_name='purchaseorderline',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='fulfillmentlink',
                    name='purchase_order_line',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_links', to='procurement.purchaseorderline', verbose_name='Purchase Order Line'),
                ),
        migrations.AddConstraint(
                    model_name='purchaseorder',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('order_number',), name='unique_purchaseorder_number_active'),
                ),
        migrations.AddConstraint(
                    model_name='contract',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('contract_number',), name='unique_contract_number_active'),
                ),
        migrations.AddConstraint(
                    model_name='contract',
                    constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_date_gte_start_date'),
                ),
        migrations.AddConstraint(
                    model_name='fulfillmentlink',
                    constraint=models.UniqueConstraint(fields=('asset_request', 'purchase_order_line'), name='unique_request_po_line_link'),
                ),
    ]
