# Generated by Django 5.2.16 on 2026-08-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0100_issue88_shard_57_procurement_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('receive_purchaseorder', 'Can receive stock from a purchase order'), ('approve_purchaseorder', 'Can approve/submit a purchase order')], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
