# Generated by Django 5.2.16 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0101_alter_purchaseorder_options"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulfillmentlink",
            name="qty_received",
            field=models.PositiveIntegerField(
                help_text="Quantity of this line's receipts attributed to this Asset Request. Null on links that predate receipt attribution.",
                null=True,
                verbose_name="Qty Received",
            ),
        ),
    ]
