# Generated by Django 5.2.17 on 2026-10-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0121_supplier_scoping_and_commercial_fields'),
        ('organization', '0103_tenant_resource_grant_expiry'),
        ('procurement', '0102_fulfillmentlink_qty_received'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fulfillmentlink',
            name='unique_request_po_line_link',
        ),
        migrations.AddConstraint(
            model_name='fulfillmentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset_request', 'purchase_order_line'), name='unique_request_po_line_link'),
        ),
    ]
