# Generated by Django 5.2 on 2026-06-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_alter_dashboard_options_dashboard_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configcontext',
            options={'ordering': ['weight', 'name'], 'verbose_name': 'Config Context', 'verbose_name_plural': 'Config Contexts'},
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
