# Generated by Django 5.2.15 on 2026-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
