# Generated by Django 5.2.15 on 2026-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0026_disable_script_event_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='printer_settings',
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='action_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('notification', 'Notification')], max_length=20),
        ),
    ]
