# Generated by Django 5.2.15 on 2026-06-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0029_eventrule_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrule',
            name='action_config',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced/optional JSON config (notification body, header overrides, etc.)'),
        ),
    ]
