# Generated by Django 5.2 on 2026-06-13 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0030_alter_eventrule_action_config'),
        ('organization', '0016_currency_callable_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='eventrule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this endpoint. Null represents system-wide endpoints.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_webhookendpoint_tenant_name_active'),
        ),
    ]
