# Generated by Django 5.2.15 on 2026-06-17 21:14

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Stored list-view filter querystring parameters.')),
                ('shared', models.BooleanField(default=True, help_text='Visible to all members of the owning tenant. If unset, only the creator can use it.')),
                ('enabled', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(help_text='The model whose list view this filter applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='The tenant owning this filter. Null represents system-wide filters.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'ordering': ['content_type', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'content_type', 'name'), name='unique_savedfilter_name_active')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
