# Generated by Django 5.2.15 on 2026-06-18 15:08

from django.conf import settings
from django.db import migrations, models


def dedupe_open_alertlogs(apps, schema_editor):
    """Collapse pre-existing open-alert duplicates before the unique constraint.

    Keeps the earliest (oldest ``created_at``, then lowest pk) open
    active/acknowledged AlertLog per (rule, content_type, object_id) and deletes
    the rest, so AddConstraint below applies on any existing database. On a fresh
    database (e.g. the test DB) there are no rows and this is a no-op.
    """
    AlertLog = apps.get_model('extras', 'AlertLog')
    seen = set()
    to_delete = []
    rows = (
        AlertLog.objects
        .filter(status__in=['active', 'acknowledged'])
        .order_by('created_at', 'pk')
        .values_list('id', 'rule_id', 'content_type_id', 'object_id')
    )
    for row_id, rule_id, ct_id, object_id in rows.iterator():
        key = (rule_id, ct_id, object_id)
        if key in seen:
            to_delete.append(row_id)
        else:
            seen.add(key)
    if to_delete:
        AlertLog.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0032_savedfilter'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Self-cleaning: dedupe existing open rows BEFORE adding the constraint
        # so the migration applies even on a database that already has dups.
        migrations.RunPython(dedupe_open_alertlogs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='alertlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'acknowledged'])), fields=('rule', 'content_type', 'object_id'), name='uniq_open_alert_per_object'),
        ),
    ]
