# Generated by Django 5.2.15 on 2026-06-18 16:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_journalentry_tenant(apps, schema_editor):
    """Populate the denormalised tenant from each entry's journaled object.

    No-op on a fresh/empty table (e.g. the test DB or a reseeded install). On an
    existing database, resolves each parent via the historical model's unscoped
    ``_base_manager`` and bulk-updates entries grouped by tenant. Defensive:
    skips content types whose model is gone or has no ``tenant`` field.
    """
    from collections import defaultdict

    JournalEntry = apps.get_model('extras', 'JournalEntry')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    rows = list(
        JournalEntry.objects.filter(tenant__isnull=True)
        .values_list('id', 'model_id', 'object_id')
    )
    if not rows:
        return

    by_ct = defaultdict(list)
    for row_id, ct_id, object_id in rows:
        by_ct[ct_id].append((row_id, object_id))

    for ct_id, items in by_ct.items():
        try:
            ct = ContentType.objects.get(pk=ct_id)
            ParentModel = apps.get_model(ct.app_label, ct.model)
        except Exception:
            continue
        if not any(f.name == 'tenant' for f in ParentModel._meta.fields):
            continue
        obj_ids = [oid for _, oid in items]
        try:
            tenant_by_obj = dict(
                ParentModel._base_manager.filter(pk__in=obj_ids).values_list('pk', 'tenant_id')
            )
        except Exception:
            continue
        ids_by_tenant = defaultdict(list)
        for row_id, object_id in items:
            tenant_id = tenant_by_obj.get(object_id)
            if tenant_id is not None:
                ids_by_tenant[tenant_id].append(row_id)
        for tenant_id, ids in ids_by_tenant.items():
            JournalEntry.objects.filter(id__in=ids).update(tenant_id=tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0033_alertlog_uniq_open_alert_per_object'),
        ('organization', '0018_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalised owning tenant, derived from the journaled object on save. Null = system/global object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organization.tenant'),
        ),
        # Self-cleaning: backfill the new field from each entry's object before
        # anything relies on it. No-op on a fresh/empty table.
        migrations.RunPython(backfill_journalentry_tenant, migrations.RunPython.noop),
    ]
