# Generated by Django 5.2.15 on 2026-06-19 11:28

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
        ('extras', '0034_journalentry_tenant'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='delivery_status',
            field=models.JSONField(blank=True, default=dict, help_text="Per-channel delivery result: {channel_pk: 'ok'|'failed'|'error: ...'}", verbose_name='Delivery Status'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When channel notifications were last dispatched for this alert (drives re-notify).', null=True, verbose_name='Last Notified At'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Resolution Notes'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='extras.alertrule', verbose_name='Rule'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this log. Null represents system-wide logs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('upcoming_eol', 'Upcoming EOL Planning'), ('license_expiry', 'License Expiry Alert'), ('renewal_due', 'Renewal Due Alert'), ('warranty_expiry', 'Warranty Expiry Alert'), ('audit_overdue', 'Audit Overdue')], max_length=50, verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='alert_rules', to='extras.notificationchannel', verbose_name='Channels'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rules are not evaluated at all.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='Muted rules still track alerts in the Alert Center but send no channel notifications.', verbose_name='Is Muted'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='renotify_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='0 = notify once. N = re-send channel notifications every N days while an alert stays unresolved.', verbose_name='Renotify Interval Days'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold_value',
            field=models.PositiveIntegerField(help_text='Limit count or days horizon', verbose_name='Threshold Value'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='data',
            field=models.JSONField(help_text='Serialized configuration dictionary', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.location', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.region', verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.site', verbose_name='Sites'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.tenant', verbose_name='Tenants'),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Priority weight for dictionary merging conflict resolution', verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='choices',
            field=models.TextField(blank=True, help_text="New-line separated list of choices (only for 'select' type)", verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='layout',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of widget config dicts', verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='Main Dashboard', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Scope all widgets on this dashboard to this specific tenant context.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='action_config',
            field=models.JSONField(blank=True, default=dict, help_text='Advanced/optional JSON config (notification body, header overrides, etc.)', verbose_name='Action Config'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='action_type',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('notification', 'Notification')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Optional conditions for rule matching', verbose_name='Conditions'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='events',
            field=models.JSONField(default=list, help_text="List of event action types, e.g. ['create', 'update']", verbose_name='Events'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='contenttypes.contenttype', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='eventrule',
            name='webhook',
            field=models.ForeignKey(blank=True, help_text="Endpoint to call when the action type is Webhook. Takes precedence over any 'url' in action_config.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rules', to='extras.webhookendpoint', verbose_name='Webhook'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='file_extension',
            field=models.CharField(default='csv', max_length=10, verbose_name='File Extension'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='mime_type',
            field=models.CharField(default='text/csv', help_text='MIME type for the exported file', max_length=50, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='template_code',
            field=models.TextField(help_text='Jinja2 or Django template code for export', verbose_name='Template Code'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to='attachments/files/', validators=[core.validators.validate_file_attachment], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='image',
            field=models.ImageField(upload_to='attachments/images/', validators=[core.validators.validate_image_attachment], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Denormalised owning tenant, derived from the journaled object on save. Null = system/global object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='barcode_format',
            field=models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('qr', 'QR Code'), ('datamatrix', 'Data Matrix')], default='code128', max_length=20, verbose_name='Barcode Format'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='page_height',
            field=models.FloatField(default=1.25, help_text='Label height in inches', verbose_name='Page Height'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='page_width',
            field=models.FloatField(default=2.25, help_text='Label width in inches', verbose_name='Page Width'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='template_code',
            field=models.TextField(blank=True, help_text='Jinja2/HTML template for label layout', verbose_name='Template Code'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20, verbose_name='Channel Type'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Channel-specific config (SMTP settings, webhook URL, etc.)', verbose_name='Config'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this channel. Null represents system-wide channels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='objectwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_archives', to='extras.fileattachment', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='format',
            field=models.CharField(max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='scheduled_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='extras.scheduledreport', verbose_name='Scheduled Report'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reportgenerationarchive',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_archives', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='advanced_mode',
            field=models.BooleanField(default=False, help_text='Enable custom Jinja2/HTML template code override.', verbose_name='Advanced Mode'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='filter_tenants',
            field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_templates', to='organization.tenant', verbose_name='Filter Tenants'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='group_by_field',
            field=models.CharField(blank=True, help_text='Optional column key to group grid records under (e.g. location, status).', max_length=100, verbose_name='Group By Field'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='include_distribution_chart',
            field=models.BooleanField(default=False, help_text='Toggle embedding spend or status distribution charts in the HTML report.', verbose_name='Include Distribution Chart'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='include_summary_cards',
            field=models.BooleanField(default=True, help_text='Toggle displaying top card widgets (totals, counts, financial sums).', verbose_name='Include Summary Cards'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='included_columns',
            field=models.JSONField(blank=True, default=list, help_text='Checked columns to render in the report data grid.', verbose_name='Included Columns'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('asset_summary', 'Asset Inventory Summary'), ('license_utilization', 'License Utilization'), ('subscription_renewals', 'Subscription Renewals'), ('asset_maintenance', 'Asset Maintenance & Repairs'), ('asset_depreciation', 'Asset Depreciation Summary'), ('software_inventory', 'Software Catalog & Installations')], max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='style_preset',
            field=models.CharField(choices=[('default', 'Professional Layout'), ('compact', 'Compact Audit Sheet'), ('financial', 'Financial Spend Summary')], default='default', max_length=50, verbose_name='Style Preset'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_content',
            field=models.TextField(blank=True, help_text='Optional Jinja2 custom HTML override template', verbose_name='Template Content'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this report template. Null represents system-wide templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='content_type',
            field=models.ForeignKey(help_text='The model whose list view this filter applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Stored list-view filter querystring parameters.', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='shared',
            field=models.BooleanField(default=True, help_text='Visible to all members of the owning tenant. If unset, only the creator can use it.', verbose_name='Shared'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this filter. Null represents system-wide filters.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='scheduled_reports', to='extras.notificationchannel', verbose_name='Channels'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Custom Cron Expression (e.g. '0 8 * * 1-5')", max_length=100, verbose_name='Cron Expression'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='filter_tenants',
            field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_schedules', to='organization.tenant', verbose_name='Filter Tenants'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='format',
            field=models.CharField(choices=[('html', 'HTML Email'), ('csv', 'CSV Attachment')], default='html', max_length=20, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('cron', 'Custom Cron Expression')], default='weekly', max_length=50, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Run'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='last_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Status'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='recipients',
            field=models.TextField(blank=True, default='', help_text='Comma-separated email addresses', verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='extras.reporttemplate', verbose_name='Report'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='save_to_archive',
            field=models.BooleanField(default=True, help_text='Store a copy of generated reports in the local file archive', verbose_name='Save To Archive'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Linked Django-Q Schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='django_q.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time of day to run the schedule (e.g. 08:00:00)', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this scheduled report. Null represents system-wide schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='headers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Headers'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='retry_backoff',
            field=models.PositiveSmallIntegerField(default=60, help_text='Backoff in seconds between retries', verbose_name='Retry Backoff'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Max retry attempts on failure', verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(blank=True, help_text='Shared secret for HMAC payload signing', max_length=255, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this endpoint. Null represents system-wide endpoints.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='URL'),
        ),
    ]
