# Generated by Django 5.2.15 on 2026-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='as_attachment',
            field=models.BooleanField(default=True, help_text='Serve the rendered output as a file download. Disable to display it inline in the browser.', verbose_name='Download as attachment'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='file_extension',
            field=models.CharField(blank=True, default='csv', max_length=10, verbose_name='File Extension'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='mime_type',
            field=models.CharField(blank=True, default='text/csv', help_text='MIME type for the exported file', max_length=50, verbose_name='MIME Type'),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='template_code',
            field=models.TextField(help_text='Jinja2 template rendered once over the whole result set, which is available as `queryset`.', verbose_name='Template Code'),
        ),
    ]
