# Generated by Django 5.2.15 on 2026-06-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0036_exporttemplate_as_attachment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigContext',
        ),
    ]
