# Generated by Django 5.2.15 on 2026-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0037_delete_configcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore')], db_index=True, max_length=20, verbose_name='Action'),
        ),
    ]
