# Generated by Django 5.2.15 on 2026-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0038_alter_event_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('asset_summary', 'Asset Inventory Summary'), ('license_utilization', 'License Utilization'), ('subscription_renewals', 'Subscription Renewals'), ('asset_maintenance', 'Asset Maintenance & Repairs'), ('asset_depreciation', 'Asset Depreciation Summary'), ('software_inventory', 'Software Catalog & Installations'), ('contract_renewals', 'Contract Renewals & Expirations'), ('warranty_expiration', 'Warranty Expiration'), ('asset_disposal_eol', 'Asset Disposal & End-of-Life'), ('hardware_inventory', 'Hardware Inventory (Accessories, Consumables, Components)'), ('custody_compliance', 'Custody & EULA Sign-off Compliance')], max_length=50, verbose_name='Report Type'),
        ),
    ]
