# Generated by Django 5.2.15 on 2026-06-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0039_alter_reporttemplate_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='format',
            field=models.CharField(choices=[('html', 'HTML Email'), ('csv', 'CSV Attachment'), ('pdf', 'PDF Attachment'), ('xlsx', 'Excel (XLSX) Attachment')], default='html', max_length=20, verbose_name='Format'),
        ),
    ]
