# Generated by Django 5.2.15 on 2026-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0040_alter_scheduledreport_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='style_preset',
            field=models.CharField(choices=[('default', 'Executive (Branded)'), ('compact', 'Compact (Dense)'), ('financial', 'Financial (Ledger)'), ('minimal', 'Minimal (Clean)')], default='default', max_length=50, verbose_name='Style Preset'),
        ),
    ]
