# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0002_configcontext'),
        ('extras', '0003_alter_dashboard_options_dashboard_is_default_and_more'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('extras', '0005_tag_deleted_at'),
        ('extras', '0006_alter_tag_deleted_at'),
        ('extras', '0007_alter_tag_name_alter_tag_slug_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_04_organization_schema'),
        ('extras', '0100_issue88_shard_03_extras_schema'),
    ]

    operations = [

    ]
