# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0032_savedfilter'),
        ('extras', '0033_alertlog_uniq_open_alert_per_object'),
        ('extras', '0034_journalentry_tenant'),
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('extras', '0036_exporttemplate_as_attachment_and_more'),
        ('extras', '0037_delete_configcontext'),
        ('extras', '0038_alter_event_action'),
        ('extras', '0039_alter_reporttemplate_report_type'),
        ('extras', '0040_alter_scheduledreport_format'),
        ('extras', '0041_alter_reporttemplate_style_preset'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_38_core_relations'),
        ('extras', '0100_issue88_shard_34_extras_history_8'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
    ]

    operations = [
        migrations.AddField(
                    model_name='alertlog',
                    name='acknowledged_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By'),
                ),
        migrations.AddField(
                    model_name='alertlog',
                    name='content_type',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='alertlog',
                    name='resolved_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
                ),
        migrations.AddField(
                    model_name='alertlog',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this log. Null represents system-wide logs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='alertrule',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='alertlog',
                    name='rule',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='extras.alertrule', verbose_name='Rule'),
                ),
        migrations.AddField(
                    model_name='bookmark',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='bookmark',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='customfield',
                    name='object_types',
                    field=models.ManyToManyField(blank=True, help_text='The model(s) this field applies to. A field applying to Asset Type describes a hardware specification; one applying to Asset describes a per-device detail.', related_name='custom_fields', to='contenttypes.contenttype', verbose_name='Object Types'),
                ),
        migrations.AddField(
                    model_name='customfieldset',
                    name='fields',
                    field=models.ManyToManyField(blank=True, related_name='fieldsets', to='extras.customfield', verbose_name='Custom Fields'),
                ),
        migrations.AddField(
                    model_name='dashboard',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Scope all widgets on this dashboard to this specific tenant context.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='dashboard',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='event',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='eventrule',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='contenttypes.contenttype', verbose_name='Model'),
                ),
        migrations.AddField(
                    model_name='eventrule',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='exporttemplate',
                    name='content_type',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='contenttypes.contenttype', verbose_name='Content Type'),
                ),
        migrations.AddField(
                    model_name='fileattachment',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='imageattachment',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='journalentry',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='journalentry',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Denormalised owning tenant, derived from the journaled object on save. Null = system/global object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='journalentry',
                    name='user',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='notificationchannel',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this channel. Null represents system-wide channels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='alertrule',
                    name='channels',
                    field=models.ManyToManyField(blank=True, related_name='alert_rules', to='extras.notificationchannel', verbose_name='Channels'),
                ),
        migrations.AddField(
                    model_name='objectwatch',
                    name='model',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='objectwatch',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='reportgenerationarchive',
                    name='file',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_archives', to='extras.fileattachment', verbose_name='File'),
                ),
        migrations.AddField(
                    model_name='reportgenerationarchive',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_archives', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='reporttemplate',
                    name='filter_tenants',
                    field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_templates', to='organization.tenant', verbose_name='Filter Tenants'),
                ),
        migrations.AddField(
                    model_name='reporttemplate',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this report template. Null represents system-wide templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='savedfilter',
                    name='content_type',
                    field=models.ForeignKey(help_text='The model whose list view this filter applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='contenttypes.contenttype', verbose_name='Content Type'),
                ),
        migrations.AddField(
                    model_name='savedfilter',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
                ),
        migrations.AddField(
                    model_name='savedfilter',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this filter. Null represents system-wide filters.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='scheduledreport',
                    name='channels',
                    field=models.ManyToManyField(blank=True, related_name='scheduled_reports', to='extras.notificationchannel', verbose_name='Channels'),
                ),
        migrations.AddField(
                    model_name='scheduledreport',
                    name='filter_tenants',
                    field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_schedules', to='organization.tenant', verbose_name='Filter Tenants'),
                ),
        migrations.AddField(
                    model_name='scheduledreport',
                    name='report',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='extras.reporttemplate', verbose_name='Report'),
                ),
        migrations.AddField(
                    model_name='scheduledreport',
                    name='schedule',
                    field=models.ForeignKey(blank=True, help_text='Linked Django-Q Schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='django_q.schedule', verbose_name='Schedule'),
                ),
        migrations.AddField(
                    model_name='scheduledreport',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this scheduled report. Null represents system-wide schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='reportgenerationarchive',
                    name='scheduled_report',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='extras.scheduledreport', verbose_name='Scheduled Report'),
                ),
        migrations.AddConstraint(
                    model_name='tag',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_tag_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='tag',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_tag_slug_active'),
                ),
        migrations.AddField(
                    model_name='webhookendpoint',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this endpoint. Null represents system-wide endpoints.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='eventrule',
                    name='webhook',
                    field=models.ForeignKey(blank=True, help_text="Endpoint to call when the action type is Webhook. Takes precedence over any 'url' in action_config.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rules', to='extras.webhookendpoint', verbose_name='Webhook'),
                ),
        migrations.AddIndex(
                    model_name='alertlog',
                    index=models.Index(fields=['content_type', 'object_id'], name='core_alertl_content_706751_idx'),
                ),
        migrations.AddIndex(
                    model_name='alertlog',
                    index=models.Index(fields=['severity'], name='core_alertl_severit_f0ec11_idx'),
                ),
        migrations.AddIndex(
                    model_name='alertlog',
                    index=models.Index(fields=['status'], name='core_alertl_status_b2f47a_idx'),
                ),
        migrations.AddConstraint(
                    model_name='alertlog',
                    constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'acknowledged'])), fields=('rule', 'content_type', 'object_id'), name='uniq_open_alert_per_object'),
                ),
        migrations.AddIndex(
                    model_name='bookmark',
                    index=models.Index(fields=['user', 'model', 'object_id'], name='core_bookma_user_id_69a2d6_idx'),
                ),
        migrations.AddConstraint(
                    model_name='bookmark',
                    constraint=models.UniqueConstraint(fields=('user', 'model', 'object_id'), name='core_bookmark_unique_user_model_object'),
                ),
        migrations.AddConstraint(
                    model_name='customfield',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_customfield_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='customfieldset',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_customfieldset_name_active'),
                ),
        migrations.AddIndex(
                    model_name='event',
                    index=models.Index(fields=['model', 'object_id'], name='core_event_model_i_6d722d_idx'),
                ),
        migrations.AddIndex(
                    model_name='event',
                    index=models.Index(fields=['processed', 'timestamp'], name='core_event_process_17ef77_idx'),
                ),
        migrations.AddConstraint(
                    model_name='exporttemplate',
                    constraint=models.UniqueConstraint(fields=('content_type', 'name'), name='core_exporttemplate_unique_content_type_name'),
                ),
        migrations.AddIndex(
                    model_name='fileattachment',
                    index=models.Index(fields=['model', 'object_id'], name='core_fileat_model_i_c8edb4_idx'),
                ),
        migrations.AddIndex(
                    model_name='imageattachment',
                    index=models.Index(fields=['model', 'object_id'], name='core_imagea_model_i_684849_idx'),
                ),
        migrations.AddIndex(
                    model_name='journalentry',
                    index=models.Index(fields=['model', 'object_id'], name='core_journa_model_i_3f2f97_idx'),
                ),
        migrations.AddConstraint(
                    model_name='notificationchannel',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_notificationchannel_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='alertrule',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_alertrule_name_active'),
                ),
        migrations.AddIndex(
                    model_name='objectwatch',
                    index=models.Index(fields=['user', 'model', 'object_id'], name='extras_watch_user_id_idx'),
                ),
        migrations.AddConstraint(
                    model_name='objectwatch',
                    constraint=models.UniqueConstraint(fields=('user', 'model', 'object_id'), name='extras_objectwatch_unique_user_model_object'),
                ),
        migrations.AddConstraint(
                    model_name='reporttemplate',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_reporttemplate_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='savedfilter',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'content_type', 'name'), name='unique_savedfilter_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='webhookendpoint',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_webhookendpoint_tenant_name_active'),
                ),
    ]
