# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0012_repoint_event_contenttypes'),
        ('extras', '0013_exporttemplate_labeltemplate'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_19_core_history_1'),
        ('extras', '0100_issue88_shard_18_extras_history_3'),
    ]

    operations = [

    ]
