# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0021_repoint_alerting_contenttypes'),
        ('extras', '0023_align_alerting_field_metadata'),
        ('extras', '0024_null_to_empty_strings'),
        ('extras', '0025_objectwatch'),
        ('extras', '0026_disable_script_event_rules'),
        ('extras', '0027_remove_labeltemplate_printer_settings'),
        ('extras', '0028_encrypt_webhookendpoint_secret'),
        ('extras', '0029_eventrule_webhook'),
        ('extras', '0030_alter_eventrule_action_config'),
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_33_core_history_5'),
        ('extras', '0100_issue88_shard_26_extras_history_7'),
    ]

    operations = [

    ]
