# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0018_repoint_report_contenttypes'),
        ('extras', '0019_align_report_field_metadata'),
        ('extras', '0020_notificationchannel_alertrule_alertlog'),
        ('extras', '0022_fix_scheduledreport_channels_ref'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_25_core_history_4'),
        ('extras', '0100_issue88_shard_24_extras_history_6'),
    ]

    operations = [

    ]
