# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0008_customfield_customfieldset'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_15_assets_history_3'),
        ('extras', '0100_issue88_shard_05_extras_history_1'),
    ]

    operations = [

    ]
