# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0016_repoint_group3_contenttypes'),
        ('extras', '0017_reporttemplate_scheduledreport_reportgenerationarchive'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_23_core_history_3'),
        ('extras', '0100_issue88_shard_22_extras_history_5'),
    ]

    operations = [

    ]
