# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0009_repoint_customfield_contenttype'),
        ('extras', '0010_customfield_object_types'),
        ('extras', '0011_event_eventrule_webhookendpoint'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_17_assets_history_4'),
        ('extras', '0100_issue88_shard_16_extras_history_2'),
    ]

    operations = [

    ]
