# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('extras', '0014_repoint_exporttemplate_contenttypes'),
        ('extras', '0015_journalentry_bookmark_attachments'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_21_core_history_2'),
        ('extras', '0100_issue88_shard_20_extras_history_4'),
    ]

    operations = [

    ]
