# Generated by Django 5.2.16 on 2026-07-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0101_issue88_drop_legacy_webhook_name_like'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('checkout', 'Checkout'), ('checkin', 'Checkin')], db_index=True, max_length=20, verbose_name='Action'),
        ),
    ]
