# Generated by Django 5.2.16 on 2026-08-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0102_alter_event_action'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='advanced_mode',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='template_content',
        ),
    ]
