# Generated by Django 5.2.16 on 2026-08-14 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0105_reporttemplate_advanced_mode_and_more"),
        ("users", "0100_issue88_shard_62_users_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledReportScopeAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "scope_tenant_ids",
                    models.JSONField(default=list, editable=False, verbose_name="Authorized Tenant Scope"),
                ),
                ("approved_at", models.DateTimeField(auto_now=True, verbose_name="Approved At")),
                (
                    "authorized_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_report_scope_authorizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Authorized By",
                    ),
                ),
                (
                    "scheduled_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_authorization",
                        to="extras.scheduledreport",
                        verbose_name="Scheduled Report",
                    ),
                ),
            ],
        ),
    ]
