# Generated by Django 5.2.16 on 2026-08-14 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0106_scheduledreportscopeauthorization"),
        ("users", "0100_issue88_shard_62_users_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledreportscopeauthorization",
            name="revoked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Revoked At"),
        ),
        migrations.AddField(
            model_name="scheduledreportscopeauthorization",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revoked_scheduled_report_scope_authorizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revoked By",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledreportscopeauthorization",
            name="approved_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="Approved At"),
        ),
    ]
