# Generated by Django 5.2.16 on 2026-08-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0108_alertlog_delivery_outcome'),
        ('organization', '0102_alter_tenantresourcegrant_options'),
        ('users', '0100_issue88_shard_62_users_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_id', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='Delivery ID')),
                ('attempt', models.PositiveIntegerField(default=1, verbose_name='Attempt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Response Code')),
                ('error_class', models.CharField(blank=True, max_length=64, verbose_name='Error Class')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next Retry At')),
                ('test_send', models.BooleanField(db_index=True, default=False, verbose_name='Test Send')),
                ('redelivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Redelivered At')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Attempted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='extras.webhookendpoint', verbose_name='Endpoint')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='extras.event', verbose_name='Event')),
                ('redelivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Redelivered By')),
                ('redelivered_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeliveries', to='extras.webhookdelivery', verbose_name='Redelivered From')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='organization.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'status'], name='extras_webh_endpoin_9e69c4_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='extras_webh_tenant__b7c32a_idx')],
            },
        ),
    ]
