# Generated by Django 5.2.16 on 2026-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0110_issue445_task_paths"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="claim_expires_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True, verbose_name="Claim Expires At"
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="claim_token",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Claim Token"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="event_rule_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="Immutable identifier of the event rule execution that created this delivery.",
                null=True,
                verbose_name="Event Rule ID",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_enabled",
            field=models.BooleanField(default=True, verbose_name="Target Enabled"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_headers",
            field=models.JSONField(blank=True, default=dict, verbose_name="Target Headers"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_http_method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST"), ("PUT", "PUT"), ("PATCH", "PATCH")],
                default="POST",
                max_length=10,
                verbose_name="Target HTTP Method",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_retry_backoff",
            field=models.PositiveSmallIntegerField(default=60, verbose_name="Target Retry Backoff"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_retry_count",
            field=models.PositiveSmallIntegerField(default=3, verbose_name="Target Retry Count"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_secret",
            field=models.CharField(blank=True, max_length=1024, verbose_name="Target Secret"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_tenant_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="Target Tenant ID"),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="target_url",
            field=models.URLField(blank=True, max_length=2000, verbose_name="Target URL"),
        ),
    ]
