# Generated by Django 5.2.16 on 2026-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0113_upgrade_legacy_webhook_retry_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='tenant_resolution_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('resolved', 'Resolved from target'), ('global', 'Global target'), ('unresolved', 'Unresolved. Manual review required.')], db_index=True, default='not_required', help_text='Reconciliation state for legacy tenant-less alerts.', max_length=20, verbose_name='Tenant Resolution'),
        ),
    ]
