# Generated by Django 5.2.16 on 2026-09-01 19:29

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0113_upgrade_legacy_webhook_retry_schedules'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('management_kind', models.CharField(choices=[('core', 'Core'), ('library', 'Library'), ('local', 'Local')], default='local', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('managed_paths', models.JSONField(blank=True, default=dict)),
                ('source_checksum', models.CharField(blank=True, max_length=71, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_]{0,62}$')])),
                ('label', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField()),
                ('replaced_by', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['position', 'key'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomFieldChoiceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('management_kind', models.CharField(choices=[('core', 'Core'), ('library', 'Library'), ('local', 'Local')], default='local', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
                ('managed_paths', models.JSONField(blank=True, default=dict)),
                ('source_checksum', models.CharField(blank=True, max_length=71, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('namespace', models.CharField(max_length=62, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{0,61}$')])),
                ('slug', models.CharField(max_length=127, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9._-]{0,126}$')])),
                ('label', models.CharField(max_length=200)),
                ('replaced_by', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'ordering': ['namespace', 'slug'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomFieldsetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['position', 'custom_field__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='customfieldset',
            options={'ordering': ['namespace', 'slug'], 'verbose_name': 'Custom Fieldset', 'verbose_name_plural': 'Custom Fieldsets'},
        ),
        migrations.AddField(
            model_name='customfield',
            name='canonical_unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='decimal_scale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='help_text',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='customfield',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='legacy_source_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='legacy_source_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('deleted', 'Deleted')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='customfield',
            name='managed_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customfield',
            name='management_kind',
            field=models.CharField(choices=[('core', 'Core'), ('library', 'Library'), ('local', 'Local')], default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='customfield',
            name='mappings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customfield',
            name='max_values',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='maximum_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='minimum_value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='namespace',
            field=models.CharField(default='local', max_length=62, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{0,61}$')]),
        ),
        migrations.AddField(
            model_name='customfield',
            name='nullable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='quantity_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='regex',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='replaced_by',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='scope',
            field=models.CharField(blank=True, choices=[('asset_type', 'Asset Type'), ('asset', 'Asset'), ('both', 'Asset Type and Asset')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='text_max_length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='validation_rule',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='customfieldset',
            old_name='fields',
            new_name='legacy_fields',
        ),
        migrations.AlterField(
            model_name='customfieldset',
            name='legacy_fields',
            field=models.ManyToManyField(blank=True, related_name='legacy_fieldsets', to='extras.customfield', verbose_name='Legacy Custom Fields'),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('deleted', 'Deleted')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='managed_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='management_kind',
            field=models.CharField(choices=[('core', 'Core'), ('library', 'Library'), ('local', 'Local')], default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='namespace',
            field=models.CharField(default='local', max_length=62, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9-]{0,61}$')]),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='replaced_by',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='slug',
            field=models.CharField(blank=True, max_length=127, null=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9._-]{0,126}$')]),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean'), ('single-select', 'Single select'), ('multi-select', 'Multi select')], db_index=True, default='text', max_length=16, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Display Label'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(help_text='Stable JSON key (e.g. sim_card_number)', max_length=64, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{0,63}$')], verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='customfieldset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Legacy Fieldset Name'),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoiceset',
            constraint=models.UniqueConstraint(fields=('namespace', 'slug'), name='unique_customfieldchoiceset_identity'),
        ),
        migrations.AddField(
            model_name='customfieldchoice',
            name='choice_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='extras.customfieldchoiceset'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='choice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='extras.customfieldchoiceset'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_value__isnull', True), ('maximum_value__isnull', True), ('minimum_value__lte', models.F('maximum_value')), _connector='OR'), name='customfield_minimum_lte_maximum'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.CheckConstraint(condition=models.Q(('decimal_scale__isnull', True), ('decimal_scale__lte', 6), _connector='OR'), name='customfield_decimal_scale_range'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.CheckConstraint(condition=models.Q(('max_values__isnull', True), models.Q(('max_values__gte', 1), ('max_values__lte', 64)), _connector='OR'), name='customfield_max_values_range'),
        ),
        migrations.AddConstraint(
            model_name='customfield',
            constraint=models.CheckConstraint(condition=models.Q(('text_max_length__isnull', True), models.Q(('text_max_length__gte', 1), ('text_max_length__lte', 4096)), _connector='OR'), name='customfield_text_length_range'),
        ),
        migrations.AddField(
            model_name='customfieldsetfield',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldset_memberships', to='extras.customfield'),
        ),
        migrations.AddField(
            model_name='customfieldsetfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_memberships', to='extras.customfieldset'),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldsets', through='extras.CustomFieldsetField', to='extras.customfield', verbose_name='Custom Fields'),
        ),
        migrations.AddConstraint(
            model_name='customfieldset',
            constraint=models.UniqueConstraint(fields=('namespace', 'slug'), name='unique_customfieldset_identity'),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoice',
            constraint=models.UniqueConstraint(fields=('choice_set', 'key'), name='unique_customfieldchoice_key'),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoice',
            constraint=models.UniqueConstraint(fields=('choice_set', 'position'), name='unique_customfieldchoice_position'),
        ),
        migrations.AddConstraint(
            model_name='customfieldchoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('position__gte', 1), ('position__lte', 1000000)), models.Q(('position__gte', 1000000001), ('position__lte', 1000000064)), _connector='OR'), name='customfieldchoice_position_range'),
        ),
        migrations.AddConstraint(
            model_name='customfieldsetfield',
            constraint=models.UniqueConstraint(fields=('fieldset', 'custom_field'), name='unique_customfieldset_field'),
        ),
        migrations.AddConstraint(
            model_name='customfieldsetfield',
            constraint=models.UniqueConstraint(fields=('fieldset', 'position'), name='unique_customfieldset_position'),
        ),
        migrations.AddConstraint(
            model_name='customfieldsetfield',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 1000000)), name='customfieldset_position_range'),
        ),
    ]
