# Generated by Django 5.2.16 on 2026-09-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0116_alter_customfield_lifecycle_and_more'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldchoice',
            name='choice_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='extras.customfieldchoiceset'),
        ),
        migrations.AlterField(
            model_name='customfieldsetfield',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_memberships', to='extras.customfieldset'),
        ),
    ]
