# Generated by Django 5.2

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0118_issue479_t06_definition_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificationLibrary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "namespace",
                    models.CharField(
                        max_length=62,
                        unique=True,
                        validators=[django.core.validators.RegexValidator(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")],
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("installed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["namespace"],
                "constraints": [
                    models.UniqueConstraint(fields=("namespace",), name="unique_specificationlibrary_namespace"),
                ],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SpecificationLibraryRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "semantic_digest",
                    models.CharField(
                        max_length=71,
                        validators=[django.core.validators.RegexValidator(r"^sha256:[0-9a-f]{64}$")],
                    ),
                ),
                ("source_document", models.JSONField()),
                ("accepted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="extras.specificationlibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["library", "-sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("library", "sequence"),
                        name="unique_specificationlibraryrelease_library_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="specificationlibraryrelease_sequence_positive",
                    ),
                ],
                "indexes": [
                    models.Index(fields=["library", "-sequence"], name="spec_library_release_lookup"),
                ],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SpecificationLibraryLegacyProvenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_kind",
                    models.CharField(
                        choices=[
                            ("library", "Library"),
                            ("asset_type", "Asset Type"),
                            ("custom_field", "Custom Field"),
                            ("custom_fieldset", "Custom Fieldset"),
                            ("choice_set", "Choice Set"),
                            ("choice", "Choice"),
                        ],
                        max_length=16,
                    ),
                ),
                ("owner_id", models.PositiveBigIntegerField()),
                ("owner_namespace", models.CharField(max_length=62)),
                ("legacy_release", models.CharField(blank=True, max_length=64, null=True)),
                ("legacy_source_checksum", models.CharField(blank=True, max_length=71, null=True)),
                ("legacy_managed_paths", models.JSONField(default=dict)),
                ("legacy_last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disposition",
                    models.CharField(
                        choices=[("uninitialized", "Uninitialized"), ("unreconciled", "Unreconciled")],
                        max_length=16,
                    ),
                ),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_provenance",
                        to="extras.specificationlibrary",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_kind", "owner_id"),
                        name="unique_specificationlibrarylegacyprovenance_owner",
                    ),
                ],
                "indexes": [
                    models.Index(fields=["library", "owner_kind"], name="spec_legacy_library_kind"),
                    models.Index(fields=["owner_kind", "owner_id"], name="spec_legacy_owner_lookup"),
                ],
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name="specificationlibrary",
            name="accepted_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_by_libraries",
                to="extras.specificationlibraryrelease",
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fields",
                to="extras.specificationlibrary",
            ),
        ),
        migrations.AddField(
            model_name="customfieldset",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fieldsets",
                to="extras.specificationlibrary",
            ),
        ),
        migrations.AddField(
            model_name="customfieldchoiceset",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="choice_sets",
                to="extras.specificationlibrary",
            ),
        ),
        migrations.AddField(
            model_name="customfield",
            name="connector_identity",
            field=models.CharField(blank=True, db_index=True, max_length=71, null=True),
        ),
        migrations.AddField(
            model_name="customfieldset",
            name="connector_identity",
            field=models.CharField(blank=True, db_index=True, max_length=71, null=True),
        ),
        migrations.AddField(
            model_name="customfieldchoiceset",
            name="connector_identity",
            field=models.CharField(blank=True, db_index=True, max_length=71, null=True),
        ),
    ]
