# Generated by Django 5.2.16 on 2026-09-08 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0120_issue479_t07_provenance_cutover"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specificationlibrary",
            options={
                "ordering": ["namespace"],
                "permissions": [("manage_specification_library", "Can manage specification libraries")],
            },
        ),
    ]
