# Generated by Django 5.2.16 on 2026-09-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0121_specification_library_permission"),
        ("organization", "0102_alter_tenantresourcegrant_options"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="tenant_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalised owning tenant group, derived from the journaled object on save. Null = the object is tenant-scoped or system/global.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="organization.tenantgroup",
                verbose_name="Tenant group",
            ),
        ),
    ]
