# Generated by Django 5.2.16 on 2026-09-29 20:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _backfill_accepted_fires(apps, schema_editor):
    """Register each schedule's newest accepted occurrence as a fire record.

    The high-water marker predates the per-occurrence fire records; recording
    it keeps the exact-match idempotency fence in force for the newest
    accepted occurrence across the upgrade.
    """
    ScheduledReport = apps.get_model("extras", "ScheduledReport")
    ScheduledReportFire = apps.get_model("extras", "ScheduledReportFire")
    rows = [
        ScheduledReportFire(schedule_id=schedule_id, intended_fire_at=fire_at, accepted_at=timezone.now())
        for schedule_id, fire_at in ScheduledReport.objects.filter(last_accepted_fire_at__isnull=False).values_list(
            "id", "last_accepted_fire_at"
        )
    ]
    if rows:
        ScheduledReportFire.objects.bulk_create(rows, ignore_conflicts=True)


def _remove_backfilled_accepted_fires(apps, schema_editor):
    """Drop the backfilled fire records on reverse.

    Later claims belong to the table that the reverse of ``CreateModel`` drops
    right after this step, so removing just the backfilled pairs is enough.
    """
    ScheduledReport = apps.get_model("extras", "ScheduledReport")
    ScheduledReportFire = apps.get_model("extras", "ScheduledReportFire")
    for schedule_id, fire_at in ScheduledReport.objects.filter(last_accepted_fire_at__isnull=False).values_list(
        "id", "last_accepted_fire_at"
    ):
        ScheduledReportFire.objects.filter(schedule_id=schedule_id, intended_fire_at=fire_at).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0124_scheduled_report_fire_identity_delivery_outcomes"),
        ("django_q", "0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportgenerationarchive",
            name="generation_scope",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="Tenant scope snapshot of the archived generation (active tenant, data tenant ids, cross-tenant flag, approval reference). Retry delivery re-validates this archived scope, so a later scope change cannot legitimize redelivering an older export.",
                verbose_name="Generation Scope",
            ),
        ),
        migrations.AddField(
            model_name="reportgenerationarchive",
            name="retry_claim_expires_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Retry Claim Expires At"),
        ),
        migrations.AddField(
            model_name="reportgenerationarchive",
            name="retry_claim_token",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64, verbose_name="Retry Claim Token"
            ),
        ),
        migrations.AlterField(
            model_name="reportgenerationarchive",
            name="delivery_targets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-target delivery ledger of this run (email aggregate and one entry per notification channel). Retry delivery re-attempts only targets recorded as failed, using the recorded original targets and payloads.",
                verbose_name="Delivery Targets",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledreport",
            name="last_accepted_fire_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Newest intended run time accepted for execution. Informational marker only; per-occurrence idempotency is enforced by the fire records, where a redelivered occurrence is an exact-match no-op.",
                null=True,
                verbose_name="Last Accepted Fire",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledReportFire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("intended_fire_at", models.DateTimeField(verbose_name="Intended Fire")),
                ("accepted_at", models.DateTimeField(auto_now_add=True, verbose_name="Accepted At")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fires",
                        to="extras.scheduledreport",
                        verbose_name="Scheduled Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Report Fire",
                "verbose_name_plural": "Scheduled Report Fires",
                "ordering": ["-intended_fire_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "intended_fire_at"), name="extras_scheduledreportfire_unique_occurrence"
                    )
                ],
            },
        ),
        migrations.RunPython(_backfill_accepted_fires, _remove_backfilled_accepted_fires),
    ]
