# Generated by Django 5.2.17 on 2026-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0100_issue88_shard_62_users_relations"),
        ("extras", "0127_retire_report_designer_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="eventrule",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="savedfilter",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
    ]
