# Generated by Django 5.2 on 2026-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='min_qty',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='min_qty',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold'),
        ),
    ]
