# Generated by Django 5.2 on 2026-05-30 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auditsession_assetaudit'),
        ('inventory', '0003_alter_accessory_min_qty_alter_consumable_min_qty'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kititem',
            name='chk_kit_item_single_target',
        ),
        migrations.AddField(
            model_name='kititem',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.consumable', verbose_name='Consumable Catalog Item'),
        ),
        migrations.AlterField(
            model_name='kititem',
            name='qty',
            field=models.PositiveIntegerField(default=1, help_text='Quantity to checkout (applies to Accessories and Consumables)', verbose_name='Quantity'),
        ),
        migrations.AddConstraint(
            model_name='kititem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('asset_type__isnull', False), ('consumable__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', False), ('asset_type__isnull', True), ('consumable__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('consumable__isnull', True), ('license__isnull', False)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('consumable__isnull', False), ('license__isnull', True)), _connector='OR'), name='chk_kit_item_single_target'),
        ),
    ]
