# Generated by Django 5.2 on 2026-05-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_assettype_cpu_remove_assettype_gpu_and_more'),
        ('inventory', '0004_remove_kititem_chk_kit_item_single_target_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessoryassignment',
            name='chk_accessory_assignment_single_target',
        ),
        migrations.RemoveConstraint(
            model_name='consumableassignment',
            name='chk_consumable_assignment_single_target',
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions', to='assets.asset'),
        ),
        migrations.AddConstraint(
            model_name='accessoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', True), ('assigned_location__isnull', False)), models.Q(('assigned_asset__isnull', False), ('assigned_holder__isnull', True), ('assigned_location__isnull', True)), _connector='OR'), name='chk_accessory_assignment_single_target'),
        ),
        migrations.AddConstraint(
            model_name='consumableassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', True), ('assigned_location__isnull', False)), models.Q(('assigned_asset__isnull', False), ('assigned_holder__isnull', True), ('assigned_location__isnull', True)), _connector='OR'), name='chk_consumable_assignment_single_target'),
        ),
    ]
