# Generated by Django 5.2 on 2026-06-04 15:19

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0014_assettype_asset_role'),
        ('core', '0013_alter_reporttemplate_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envelope_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docusign_envelopes', to='assets.asset')),
                ('signed_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esign_envelopes', to='core.fileattachment')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
