# Generated by Django 5.2.15 on 2026-06-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_assetholder_tenant_alter_location_tenant_and_more'),
        ('users', '0002_alter_token_options_alter_userpreference_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organization.tenant'),
            preserve_default=False,
        ),
    ]
