# Generated by Django 5.2.15 on 2026-06-13 07:30

import django.contrib.postgres.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_ips',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=43), blank=True, default=list, help_text='Permitted IPv4/IPv6 networks from which this token may be used, in CIDR notation (e.g. "192.168.1.0/24, 10.0.0.5"). Leave blank to allow any source address.', size=None, validators=[users.models.validate_cidr_list], verbose_name='Allowed IPs'),
        ),
    ]
