# Generated by Django 5.2.15 on 2026-06-13 11:06
#
# Hash API tokens at rest. Existing plaintext keys are migrated into HMAC-SHA256
# digests (keyed by the current pepper) before the plaintext `key` column is
# dropped, so existing tokens keep working — their plaintext is simply no longer
# recoverable from the database.

from django.db import migrations, models


def hash_existing_tokens(apps, schema_editor):
    Token = apps.get_model('users', 'Token')
    from users.models import hash_token, current_pepper_id
    pepper_id = current_pepper_id()
    for token in Token.objects.all():
        plaintext = token.key
        if not plaintext:
            continue
        token.digest = hash_token(plaintext, pepper_id)
        token.pepper = pepper_id
        token.key_preview = plaintext[:8]
        token.save(update_fields=['digest', 'pepper', 'key_preview'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token_allowed_ips'),
    ]

    operations = [
        # 1. Add the new columns (digest not yet unique so the backfill can run).
        migrations.AddField(
            model_name='token',
            name='digest',
            field=models.CharField(blank=True, editable=False, max_length=64, default=''),
        ),
        migrations.AddField(
            model_name='token',
            name='key_preview',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='token',
            name='pepper',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        # 2. Backfill digests from the existing plaintext keys (still present).
        migrations.RunPython(hash_existing_tokens, noop),
        # 3. Drop the plaintext column now that digests exist.
        migrations.RemoveField(
            model_name='token',
            name='key',
        ),
        # 4. Enforce uniqueness on the populated digest column.
        migrations.AlterField(
            model_name='token',
            name='digest',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
