# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('users', '0005_remove_token_key_token_digest_token_key_preview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='token',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Used'),
        ),
        migrations.AlterField(
            model_name='token',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='write_enabled',
            field=models.BooleanField(default=True, verbose_name='Write Enabled'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
