# Generated by Django 5.2.15 on 2026-06-24 18:12
#
# UserGroup relocated organization -> users (identity layer). Data-preserving: the
# physical organization_usergroup* tables are RENAMED to users_usergroup* (rows + M2M
# links survive) and the existing content type is repointed IN PLACE (so the
# manage_usergroups permission and any user_permissions grants stay valid).

import core.mixins
import core.models
from django.conf import settings
from django.db import migrations, models


def move_usergroup_contenttype(apps, schema_editor):
    """Repoint the organization.usergroup ContentType -> users.usergroup IN PLACE.

    Preserving the row's PK keeps every FK valid: the manage_usergroups (and
    add/change/delete/view_usergroup) Permission rows, any user_permissions grants, and
    ObjectChange.changed_object_type references. On a fresh database the content type does
    not exist yet during migration (created at post_migrate), so this is a harmless no-op
    and post_migrate then creates users.usergroup directly.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='organization', model='usergroup').update(app_label='users')
    # Denormalised audit string on historical rows (the FK is already preserved above).
    # core may not be in the migration state on a fresh DB; there are no rows then anyway.
    try:
        ObjectChange = apps.get_model('core', 'ObjectChange')
    except LookupError:
        return
    ObjectChange.objects.filter(object_type_repr='organization | usergroup').update(
        object_type_repr='users | usergroup'
    )


def revert_usergroup_contenttype(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='users', model='usergroup').update(app_label='organization')
    try:
        ObjectChange = apps.get_model('core', 'ObjectChange')
    except LookupError:
        return
    ObjectChange.objects.filter(object_type_repr='users | usergroup').update(
        object_type_repr='organization | usergroup'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_delete_usergroup'),
        ('users', '0006_alter_token_description_alter_token_expires_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Register users.UserGroup in migration STATE only — no new tables; the physical
        #    tables are the organization_usergroup* tables, renamed to match below.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                        ('members', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                        ('roles', models.ManyToManyField(blank=True, help_text="Roles granted to members. Roles may span multiple tenants; a member gets each role's permissions in that role's tenant.", related_name='user_groups', to='organization.tenantrole', verbose_name='Roles')),
                    ],
                    options={
                        'verbose_name': 'User Group',
                        'verbose_name_plural': 'User Groups',
                        'ordering': ['name'],
                        'permissions': [('manage_usergroups', 'Can manage user groups (global)')],
                        'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='users_usergroup_unique_name_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='users_usergroup_unique_slug_active')],
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
            ],
            database_operations=[],
        ),
        # 2. Rename the physical tables + the two explicitly-named partial unique indexes so
        #    the database matches the new users.UserGroup state. Auto-named indexes are
        #    located by column introspection, so they need no rename.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE organization_usergroup RENAME TO users_usergroup;",
                "ALTER TABLE organization_usergroup_roles RENAME TO users_usergroup_roles;",
                "ALTER TABLE organization_usergroup_members RENAME TO users_usergroup_members;",
                "ALTER INDEX organization_usergroup_unique_name_active RENAME TO users_usergroup_unique_name_active;",
                "ALTER INDEX organization_usergroup_unique_slug_active RENAME TO users_usergroup_unique_slug_active;",
            ],
            reverse_sql=[
                "ALTER INDEX users_usergroup_unique_slug_active RENAME TO organization_usergroup_unique_slug_active;",
                "ALTER INDEX users_usergroup_unique_name_active RENAME TO organization_usergroup_unique_name_active;",
                "ALTER TABLE users_usergroup_members RENAME TO organization_usergroup_members;",
                "ALTER TABLE users_usergroup_roles RENAME TO organization_usergroup_roles;",
                "ALTER TABLE users_usergroup RENAME TO organization_usergroup;",
            ],
        ),
        # 3. Repoint the content type in place (preserves permissions + grants + audit FKs).
        migrations.RunPython(move_usergroup_contenttype, revert_usergroup_contenttype),
    ]
