# WARNING: GREENFIELD ONLY. This migration is NOT safe for production databases containing legacy data.
# Generated by Django 5.2.15 on 2026-06-26 — unified RBAC rewrite

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_remove_tenantrole_tenant_provider_tenant_provider_and_more'),
        ('users', '0007_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
        migrations.AddField(
            model_name='token',
            name='provider',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tokens',
                to='organization.provider',
                verbose_name='Provider',
            ),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='provider',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_groups',
                to='organization.provider',
                verbose_name='Provider',
            ),
        ),
        # The old roles M2M targeted organization.TenantRole, which is gone. Drop the
        # field and re-create it pointing to the new unified organization.Role.
        migrations.RemoveField(
            model_name='usergroup',
            name='roles',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(
                blank=True,
                help_text=("Roles granted to members. Roles may span multiple tenants or "
                           "providers; a member gets each role's permissions in its container."),
                related_name='user_groups',
                to='organization.role',
                verbose_name='Roles',
            ),
        ),
    ]
