# Generated by Django 5.2.15 on 2026-06-24 18:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_provider_tenant_provider_providerroletemplate_and_more'),
        ('users', '0007_usergroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='organization.provider', verbose_name='Provider'),
        ),
        migrations.CreateModel(
            name='ProviderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_scope', models.CharField(choices=[('explicit', 'Explicit (assigned tenants only)'), ('tenant_group', 'Tenant group'), ('all', 'All provider tenants')], default='explicit', max_length=20, verbose_name='Tenant scope')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_tenants', models.ManyToManyField(blank=True, help_text="Used when tenant scope is 'Explicit'.", related_name='provider_assignments', to='organization.tenant', verbose_name='Assigned tenants')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.provider', verbose_name='Provider')),
                ('provider_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='organization.providerrole', verbose_name='Provider role')),
                ('scope_group', models.ForeignKey(blank=True, help_text="Used when tenant scope is 'Tenant group'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_membership_scopes', to='organization.tenantgroup', verbose_name='Scope group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Provider Membership',
                'verbose_name_plural': 'Provider Memberships',
                'ordering': ['provider', 'user'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='users_providermembership_unique_user_provider')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
