# Generated by Django 5.2.15 on 2026-06-27 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_remove_membership_organization_membership_scope_consistency_and_more'),
        ('users', '0008_alter_usergroup_options_token_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_name_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_slug_active',
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', False)), fields=('provider', 'name'), name='users_usergroup_unique_provider_name_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', True)), fields=('name',), name='users_usergroup_unique_global_name_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', False)), fields=('provider', 'slug'), name='users_usergroup_unique_provider_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', True)), fields=('slug',), name='users_usergroup_unique_global_slug_active'),
        ),
    ]
