# Generated by Django 5.2.15 on 2026-06-24 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_provider_tenant_provider_providerroletemplate_and_more'),
        ('users', '0008_usergroup_provider_providermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organization.provider', verbose_name='Provider'),
        ),
    ]
