# GREENFIELD-ONLY: part of the 2026-07-10 RBAC structural collapse (Provider -> Tenant tree, per-grant RoleAssignment). Applies cleanly only on a fresh database — pre-collapse rows are intentionally not migrated (project convention: unreleased app, greenfield resets).
# Generated by Django 5.2.15 on 2026-07-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_roleassignment_remove_provider_internal_tenant_and_more'),
        ('users', '0009_remove_usergroup_users_usergroup_unique_name_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_provider_name_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_global_name_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_provider_slug_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_global_slug_active',
        ),
        migrations.RemoveField(
            model_name='token',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='provider',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'name'), name='users_usergroup_unique_tenant_name_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', True)), fields=('name',), name='users_usergroup_unique_global_name_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'slug'), name='users_usergroup_unique_tenant_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', True)), fields=('slug',), name='users_usergroup_unique_global_slug_active'),
        ),
    ]
