# Generated by Django 5.2.15 on 2026-07-13 18:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_rolegrant_rolegrantscope_and_more'),
        ('users', '0010_remove_usergroup_users_usergroup_unique_provider_name_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('scim', 'SCIM'), ('ldap', 'LDAP / Entra ID'), ('oidc', 'OIDC'), ('saml', 'SAML')], db_index=True, default='manual', max_length=20, verbose_name='Source')),
                ('external_id', models.CharField(blank=True, help_text='Stable membership identifier supplied by SCIM/LDAP when available.', max_length=255, verbose_name='External ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='organization.membership', verbose_name='Membership')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.usergroup', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'Group membership',
                'verbose_name_plural': 'Group memberships',
                'ordering': ['user_group', 'membership'],
                'indexes': [models.Index(fields=['user_group', 'source', 'external_id'], name='users_groupmember_external_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_group', 'membership'), name='users_groupmembership_unique_member'), models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('user_group', 'source', 'external_id'), name='users_groupmembership_unique_external_id')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
