# Generated by Django 5.2.15 on 2026-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_backfill_phase5_rbac'),
        ('users', '0011_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Legacy comparison field; new grants use RoleGrant + RoleGrantScope.', related_name='user_groups', to='organization.role', verbose_name='Roles'),
        ),
    ]
