# Generated by Django 5.2.15 on 2026-07-13 19:39

import django.db.models.deletion
from django.db import migrations, models


def delete_unowned_groups(apps, schema_editor):
    UserGroup = apps.get_model('users', 'UserGroup')
    UserGroup._base_manager.filter(tenant_id__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_remove_rolegrant_legacy_assignment_and_more'),
        ('users', '0012_alter_usergroup_roles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_tenant_name_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_global_name_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_tenant_slug_active',
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='users_usergroup_unique_global_slug_active',
        ),
        migrations.RunPython(delete_unowned_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usergroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='roles',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='users_usergroup_unique_tenant_name_active'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'slug'), name='users_usergroup_unique_tenant_slug_active'),
        ),
    ]
