# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('users', '0009_remove_usergroup_users_usergroup_unique_name_active_and_more'),
        ('users', '0010_remove_usergroup_users_usergroup_unique_provider_name_active_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_53_organization_history_6'),
        ('users', '0100_issue88_shard_52_users_history_2'),
    ]

    operations = [

    ]
