# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('users', '0008_alter_usergroup_options_token_provider_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_51_organization_history_5'),
        ('users', '0100_issue88_shard_50_users_history_1'),
    ]

    operations = [

    ]
