# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('users', '0013_remove_usergroup_users_usergroup_unique_tenant_name_active_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_61_organization_relations'),
        ('users', '0100_issue88_shard_60_users_history_5'),
    ]

    operations = [
        migrations.AddConstraint(
                    model_name='usergroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='users_usergroup_unique_tenant_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='usergroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'slug'), name='users_usergroup_unique_tenant_slug_active'),
                ),
        migrations.AddIndex(
                    model_name='groupmembership',
                    index=models.Index(fields=['user_group', 'source', 'external_id'], name='users_groupmember_external_idx'),
                ),
        migrations.AddConstraint(
                    model_name='groupmembership',
                    constraint=models.UniqueConstraint(fields=('user_group', 'membership'), name='users_groupmembership_unique_member'),
                ),
        migrations.AddConstraint(
                    model_name='groupmembership',
                    constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('user_group', 'source', 'external_id'), name='users_groupmembership_unique_external_id'),
                ),
    ]
