# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('users', '0001_initial'),
        ('users', '0002_alter_token_options_alter_userpreference_options'),
    ]

    dependencies = [
        ('licenses', '0100_issue88_shard_48_licenses_relations'),
        ('users', '0000_issue88_shard_01_users_bootstrap'),
    ]

    operations = [
        migrations.CreateModel(
                    name='Token',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('digest', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                        ('pepper', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                        ('key_preview', models.CharField(blank=True, editable=False, max_length=16)),
                        ('created', models.DateTimeField(auto_now_add=True)),
                        ('expires', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires')),
                        ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                        ('write_enabled', models.BooleanField(default=True, verbose_name='Write Enabled')),
                        ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                        ('allowed_ips', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=43), blank=True, default=list, help_text='Permitted IPv4/IPv6 networks from which this token may be used, in CIDR notation (e.g. "192.168.1.0/24, 10.0.0.5"). Leave blank to allow any source address.', size=None, validators=[users.models.validate_cidr_list], verbose_name='Allowed IPs')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organization.tenant', verbose_name='Tenant')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                    ],
                    options={
                        'verbose_name': 'Token',
                        'verbose_name_plural': 'Tokens',
                        'ordering': ['-created'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='UserGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='organization.tenant', verbose_name='Tenant')),
                    ],
                    options={
                        'verbose_name': 'User Group',
                        'verbose_name_plural': 'User Groups',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='GroupMembership',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('source', models.CharField(choices=[('manual', 'Manual'), ('scim', 'SCIM'), ('ldap', 'LDAP / Entra ID'), ('oidc', 'OIDC'), ('saml', 'SAML')], db_index=True, default='manual', max_length=20, verbose_name='Source')),
                        ('external_id', models.CharField(blank=True, help_text='Stable membership identifier supplied by SCIM/LDAP when available.', max_length=255, verbose_name='External ID')),
                        ('added_at', models.DateTimeField(auto_now_add=True)),
                        ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                        ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='organization.membership', verbose_name='Membership')),
                        ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.usergroup', verbose_name='User group')),
                    ],
                    options={
                        'verbose_name': 'Group membership',
                        'verbose_name_plural': 'Group memberships',
                        'ordering': ['user_group', 'membership'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='UserPreference',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                    ],
                    options={
                        'verbose_name': 'User Preference',
                        'verbose_name_plural': 'User Preferences',
                        'ordering': ('user',),
                    },
                ),
    ]
