# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('users', '0012_alter_usergroup_roles'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_59_organization_history_8'),
        ('users', '0100_issue88_shard_58_users_history_4'),
    ]

    operations = [

    ]
