# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('users', '0011_groupmembership'),
    ]

    dependencies = [
        ('procurement', '0100_issue88_shard_57_procurement_relations'),
        ('users', '0100_issue88_shard_54_users_history_3'),
    ]

    operations = [

    ]
