# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('users', '0003_token_tenant'),
        ('users', '0004_token_allowed_ips'),
        ('users', '0005_remove_token_key_token_digest_token_key_preview_and_more'),
        ('users', '0006_alter_token_description_alter_token_expires_and_more'),
        ('users', '0007_usergroup'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_49_users_schema'),
    ]

    operations = [

    ]
