# Generated by Django 5.2.16 on 2026-08-01 19:11

import uuid

from django.db import migrations, models
from django.db.models import Count


def populate_scim_ids(apps, schema_editor):
    """Populate stable opaque IDs once, without rotating partially migrated rows."""
    batch_size = 1000
    for model_name in ("User", "UserGroup"):
        model = apps.get_model("users", model_name)
        pending = []
        batch_ids = set()
        for instance in model._default_manager.order_by("pk").iterator(chunk_size=batch_size):
            if instance.scim_id is None:
                candidate = uuid.uuid4()
                while candidate in batch_ids:
                    candidate = uuid.uuid4()
                instance.scim_id = candidate
                pending.append(instance)
                batch_ids.add(candidate)
            if len(pending) >= batch_size:
                model._default_manager.bulk_update(pending, ["scim_id"], batch_size=batch_size)
                pending.clear()
                batch_ids.clear()
        if pending:
            model._default_manager.bulk_update(pending, ["scim_id"], batch_size=batch_size)

        duplicate = (
            model._default_manager.values("scim_id")
            .annotate(scim_id_count=Count("scim_id"))
            .filter(scim_id_count__gt=1)
            .exists()
        )
        if duplicate:
            raise RuntimeError(f"SCIM ID collision in {model_name}")
        if model._default_manager.filter(scim_id__isnull=True).exists():
            raise RuntimeError(f"SCIM ID migration left NULL {model_name} rows")


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0101_membership_external_id_and_more"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scim_id",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Stable opaque identifier emitted by the SCIM API.",
                null=True,
                verbose_name="SCIM resource ID",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stable identifier supplied by the provisioning domain that owns this group.",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="scim_id",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Stable opaque identifier emitted by the SCIM API.",
                null=True,
                verbose_name="SCIM resource ID",
            ),
        ),
        migrations.RunPython(populate_scim_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="scim_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Stable opaque identifier emitted by the SCIM API.",
                unique=True,
                verbose_name="SCIM resource ID",
            ),
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="scim_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Stable opaque identifier emitted by the SCIM API.",
                unique=True,
                verbose_name="SCIM resource ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="usergroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True) & ~models.Q(external_id=""),
                fields=("tenant", "external_id"),
                name="users_usergroup_unique_tenant_external_id",
            ),
        ),
    ]
