# Generated by Django 5.2.16 on 2026-08-15 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0100_issue88_shard_62_users_relations'),
        ('users', '0101_user_scim_id_usergroup_external_id_usergroup_scim_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
