# Generated by Django 5.2.16 on 2026-08-25 07:10

import core.models
import core.oidc_identity
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_issue88_shard_62_users_relations'),
        ('users', '0102_token_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=2000, validators=[core.oidc_identity.validate_oidc_issuer])),
                ('subject', models.CharField(max_length=255, validators=[core.oidc_identity.validate_oidc_subject])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='users_oidcidentity_unique_issuer_subject')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
