# Generated by Django 5.2 on 2026-06-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_assetholder_site_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('tenant', 'name'), ('tenant', 'slug')},
        ),
    ]
