# Generated by Django 5.2.15 on 2026-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_provider_tenant_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='provider',
            name='tenant',
        ),
    ]
