# Generated by Django 5.2 on 2026-06-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
        ('subscriptions', '0003_alter_provider_unique_together_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this provider. Null represents system-wide/global providers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'name'), name='unique_tenant_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('name',), name='unique_global_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'slug'), name='unique_tenant_provider_slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_global_provider_slug'),
        ),
    ]
