# Generated by Django 5.2 on 2026-06-06 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
        ('subscriptions', '0004_provider_tenant_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_global_provider_name',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_global_provider_slug',
        ),
        migrations.AddField(
            model_name='provider',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='The tenant group owning this provider.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenantgroup'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), _connector='OR'), name='provider_tenant_or_group'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False)), fields=('tenant_group', 'name'), name='unique_tenant_group_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False)), fields=('tenant_group', 'slug'), name='unique_tenant_group_provider_slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True)), fields=('name',), name='unique_global_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True)), fields=('slug',), name='unique_global_provider_slug'),
        ),
    ]
