# Generated by Django 5.2 on 2026-06-06 19:39

from django.db import migrations


def migrate_provider_contacts(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContactRole = apps.get_model('organization', 'ContactRole')
    Contact = apps.get_model('organization', 'Contact')
    ContactAssignment = apps.get_model('organization', 'ContactAssignment')
    Provider = apps.get_model('subscriptions', 'Provider')

    provider_ct, _ = ContentType.objects.get_or_create(app_label='subscriptions', model='provider')

    primary_role, _ = ContactRole.objects.get_or_create(
        slug='primary-contact',
        defaults={'name': 'Primary Contact', 'description': 'Primary Contact'}
    )
    support_role, _ = ContactRole.objects.get_or_create(
        slug='technical-support',
        defaults={'name': 'Technical Support', 'description': 'Technical Support'}
    )

    for provider in Provider.objects.all():
        has_primary = provider.contact_email or provider.contact_phone or provider.website
        if has_primary:
            contact = Contact.objects.create(
                name=f"{provider.name} Contact",
                phone=provider.contact_phone or "",
                email=provider.contact_email or "",
                web_url=provider.website or ""
            )
            ContactAssignment.objects.create(
                contact=contact,
                role=primary_role,
                content_type=provider_ct,
                object_id=provider.pk,
                priority='primary'
            )

        if provider.support_contact:
            contact = Contact.objects.create(
                name=f"{provider.name} Support",
                description=provider.support_contact
            )
            ContactAssignment.objects.create(
                contact=contact,
                role=support_role,
                content_type=provider_ct,
                object_id=provider.pk,
                priority='secondary'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_provider_unique_global_provider_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_provider_contacts, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='provider',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='support_contact',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='website',
        ),
    ]
