# Generated by Django 5.2.15 on 2026-06-08 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_alter_tag_name_alter_tag_slug_and_more'),
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
        ('subscriptions', '0008_alter_provider_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_subscription_slug_active'),
        ),
    ]
