# Generated by Django 5.2.15 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subscription_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
    ]
