# Generated by Django 5.2.15 on 2026-06-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_costcenter'),
        ('subscriptions', '0010_subscription_custom_field_data'),
    ]

    operations = [
        # cost_center was a free-text CharField; converting to an FK by dropping
        # the old text column and adding a fresh nullable FK column. An in-place
        # AlterField fails because Postgres cannot cast existing text values
        # (e.g. "NW-IT-CLOUD") to a bigint FK. The app is unreleased, so the old
        # free-text values are intentionally not preserved (they map to no
        # CostCenter); every other column on the row is retained.
        migrations.RemoveField(
            model_name='subscription',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Financial cost center responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='organization.costcenter', verbose_name='Cost Center'),
        ),
    ]
