# Generated by Django 5.2.15 on 2026-06-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_costcenter'),
        ('subscriptions', '0010_subscription_custom_field_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Financial cost center responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='organization.costcenter', verbose_name='Cost Center'),
        ),
    ]
