# Generated by Django 5.2.15 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('organization', '0018_costcenter'),
        ('subscriptions', '0011_alter_subscription_cost_center'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_tenant_provider_name',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_tenant_provider_slug',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_tenant_group_provider_name',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_tenant_group_provider_slug',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_global_provider_name',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='unique_global_provider_slug',
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_tenant_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'slug'), name='unique_tenant_provider_slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False), ('deleted_at__isnull', True)), fields=('tenant_group', 'name'), name='unique_tenant_group_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False), ('deleted_at__isnull', True)), fields=('tenant_group', 'slug'), name='unique_tenant_group_provider_slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), ('deleted_at__isnull', True)), fields=('name',), name='unique_global_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), ('deleted_at__isnull', True)), fields=('slug',), name='unique_global_provider_slug'),
        ),
    ]
