# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('subscriptions', '0013_alter_subscription_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscription_providers', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this provider. Null represents system-wide/global providers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='The tenant group owning this provider.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenantgroup', verbose_name='Tenant Group'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, help_text='Optional text detailing coverage or terms', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(help_text='Descriptive name (e.g., Adobe Creative Cloud - All Apps (Team))', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional internal notes', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.provider', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renewal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per renewal period', max_digits=10, null=True, verbose_name='Renewal Cost'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_org', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='subscriptionassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='subscriptionassignment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subscriptions.subscription', verbose_name='Subscription'),
        ),
    ]
