# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('subscriptions', '0001_initial'),
        ('subscriptions', '0002_provider_tenant_alter_provider_name_and_more'),
        ('subscriptions', '0003_alter_provider_unique_together_alter_provider_name_and_more'),
        ('subscriptions', '0004_provider_tenant_alter_provider_name_and_more'),
        ('subscriptions', '0005_remove_provider_unique_global_provider_name_and_more'),
        ('subscriptions', '0006_remove_provider_contact_email_and_more'),
        ('subscriptions', '0007_provider_deleted_at'),
        ('subscriptions', '0008_alter_provider_deleted_at_and_more'),
        ('subscriptions', '0009_alter_subscription_slug_and_more'),
        ('subscriptions', '0010_subscription_custom_field_data'),
        ('subscriptions', '0011_alter_subscription_cost_center'),
        ('subscriptions', '0012_remove_provider_unique_tenant_provider_name_and_more'),
        ('subscriptions', '0013_alter_subscription_currency'),
    ]

    dependencies = [
        ('software', '0100_issue88_shard_45_software_relations'),
    ]

    operations = [
        migrations.CreateModel(
                    name='SubscriptionAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('object_id', models.PositiveBigIntegerField()),
                        ('assigned_date', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'Subscription Assignment',
                        'verbose_name_plural': 'Subscription Assignments',
                        'ordering': ('-assigned_date',),
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Provider',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Unique name of the provider (e.g., Adobe Inc.)', max_length=255, verbose_name='Name')),
                        ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, verbose_name='Slug')),
                        ('account_id', models.CharField(blank=True, help_text='Optional customer account number with the provider', max_length=100, verbose_name='Account ID')),
                        ('portal_url', models.URLField(blank=True, help_text="URL for the provider's management/administration portal", verbose_name='Admin Portal URL')),
                        ('admin_notes', models.TextField(blank=True, help_text='Optional internal administrative notes', verbose_name='Admin Notes')),
                        ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate to hide from selection lists without deleting', verbose_name='Active')),
                        ('tags', models.ManyToManyField(blank=True, related_name='subscription_providers', to='extras.tag', verbose_name='Tags')),
                        ('tenant', models.ForeignKey(blank=True, help_text='The tenant owning this provider. Null represents system-wide/global providers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenant', verbose_name='Tenant')),
                        ('tenant_group', models.ForeignKey(blank=True, help_text='The tenant group owning this provider.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_providers', to='organization.tenantgroup', verbose_name='Tenant Group')),
                    ],
                    options={
                        'verbose_name': 'Provider',
                        'verbose_name_plural': 'Providers',
                        'ordering': ('name',),
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Subscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Descriptive name (e.g., Adobe Creative Cloud - All Apps (Team))', max_length=255, verbose_name='Name')),
                        ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if left blank)', max_length=255, null=True, verbose_name='Slug')),
                        ('type', models.CharField(choices=[('saas', 'SaaS'), ('support', 'Support'), ('maintenance', 'Maintenance'), ('lease', 'Lease'), ('other', 'Other')], db_index=True, default='saas', max_length=50, verbose_name='Subscription Type')),
                        ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('renewing', 'Renewing'), ('trial', 'Trial')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                        ('start_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Start Date')),
                        ('renewal_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Renewal Date')),
                        ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per renewal period', max_digits=10, null=True, verbose_name='Renewal Cost')),
                        ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                        ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('biannual', 'Biannual'), ('multi_year', 'Multi-Year'), ('onetime', 'One-Time')], default='annual', max_length=20, verbose_name='Billing Cycle')),
                        ('term_months', models.PositiveIntegerField(blank=True, help_text='Duration of the subscription term in months', null=True, verbose_name='Term (Months)')),
                        ('auto_renewal', models.BooleanField(default=True, help_text='Whether this subscription renews automatically', verbose_name='Auto-Renewal')),
                        ('licensed_quantity', models.PositiveIntegerField(blank=True, help_text='Number of seats/users/devices covered (for SaaS/support)', null=True, verbose_name='Licensed Quantity')),
                        ('contract_reference', models.CharField(blank=True, help_text='Contract number, PO reference, or quote ID', max_length=100, verbose_name='Contract Reference')),
                        ('cancellation_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Cancellation Date')),
                        ('description', models.TextField(blank=True, help_text='Optional text detailing coverage or terms', verbose_name='Description')),
                        ('notes', models.TextField(blank=True, help_text='Optional internal notes', verbose_name='Notes')),
                        ('cost_center', models.ForeignKey(blank=True, help_text='Financial cost center responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='organization.costcenter', verbose_name='Cost Center')),
                    ],
                    options={
                        'verbose_name': 'Subscription',
                        'verbose_name_plural': 'Subscriptions',
                        'ordering': ('-renewal_date', 'provider', 'name'),
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.BookmarkableMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
