# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('subscriptions', '0014_alter_provider_name_alter_provider_slug_and_more'),
    ]

    dependencies = [
        ('subscriptions', '0100_issue88_shard_46_subscriptions_schema'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
                    model_name='subscription',
                    name='owner',
                    field=models.ForeignKey(blank=True, help_text='Person responsible for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
                ),
        migrations.AddField(
                    model_name='subscription',
                    name='provider',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.provider', verbose_name='Provider'),
                ),
        migrations.AddField(
                    model_name='subscription',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='subscriptions', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='subscription',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_org', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='subscriptionassignment',
                    name='assigned_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
                ),
        migrations.AddField(
                    model_name='subscriptionassignment',
                    name='content_type',
                    field=models.ForeignKey(limit_choices_to={'model__in': ('asset', 'assetholder', 'location', 'consumable', 'accessory')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='subscriptionassignment',
                    name='subscription',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subscriptions.subscription', verbose_name='Subscription'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), _connector='OR'), name='provider_tenant_or_group'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'name'), name='unique_tenant_provider_name'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'slug'), name='unique_tenant_provider_slug'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False), ('deleted_at__isnull', True)), fields=('tenant_group', 'name'), name='unique_tenant_group_provider_name'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant_group__isnull', False), ('deleted_at__isnull', True)), fields=('tenant_group', 'slug'), name='unique_tenant_group_provider_slug'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), ('deleted_at__isnull', True)), fields=('name',), name='unique_global_provider_name'),
                ),
        migrations.AddConstraint(
                    model_name='provider',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('tenant_group__isnull', True), ('deleted_at__isnull', True)), fields=('slug',), name='unique_global_provider_slug'),
                ),
        migrations.AddConstraint(
                    model_name='subscription',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_subscription_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='subscriptionassignment',
                    constraint=models.UniqueConstraint(fields=('subscription', 'content_type', 'object_id'), name='subscriptions_assignment_unique'),
                ),
    ]
