# Generated by Django 5.2.16 on 2026-07-31 01:57

from django.db import migrations, models


def normalize_legacy_statuses(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    Subscription.objects.filter(status__in=("pending", "trial", "renewing")).update(status="active")


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0100_issue88_shard_47_subscriptions_relations'),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='auto_renewal',
            new_name='vendor_contract_auto_renews',
        ),
        migrations.AlterField(
            model_name="subscription",
            name="vendor_contract_auto_renews",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Records whether the vendor's contract renews automatically. ITAMbox does not renew subscriptions: "
                    "a subscription past its renewal date is marked expired."
                ),
                verbose_name="Vendor Contract Auto-Renews",
            ),
        ),
        migrations.RunPython(normalize_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='Status'),
        ),
    ]
