# Generated by Django 5.2.16 on 2026-09-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0101_remove_subscription_auto_renewal_and_more'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='licensed_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of seats, users, or devices entitled by the vendor agreement. This value is independent of linked License seats.', null=True, verbose_name='Agreement Entitled Quantity'),
        ),
    ]
