# Generated by Django 5.2.17 on 2026-10-09 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("subscriptions", "0103_unified_vendor_cutover"),
        ("users", "0100_issue88_shard_62_users_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscriptionassignment",
            name="subscriptions_assignment_unique",
        ),
        migrations.AddField(
            model_name="subscriptionassignment",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="subscriptionassignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="subscriptionassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("subscription", "content_type", "object_id"),
                name="subscriptions_assignment_unique",
            ),
        ),
    ]
