# Generated by Django 5.2.17 on 2026-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0104_subscriptionassignment_leaf_deleted_at'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='renewal_reminder_cycle_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_reminder_days',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
