# Generated by Django 5.2 on 2025-04-11 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('upn', models.CharField(max_length=255, unique=True, verbose_name='User Principal Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='organization_assetholders', to='extras.tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holders', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Asset Holder',
                'ordering': ['last_name', 'first_name', 'upn'],
            },
        ),
        migrations.CreateModel(
            name='AssetHolderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.assetholder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='organization_assetholderassignments', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Asset Holder Assignment',
                'ordering': ['asset_holder', 'content_type', 'object_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assetholder',
            constraint=models.UniqueConstraint(fields=('upn',), name='organization_assetholder_unique_upn'),
        ),
        migrations.AddConstraint(
            model_name='assetholderassignment',
            constraint=models.UniqueConstraint(fields=('asset_holder', 'content_type', 'object_id'), name='organization_assetholderassignment_unique'),
        ),
    ]
