# Generated by Django 5.2 on 2026-06-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_region_options_alter_site_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetHolderAssignment',
        ),
    ]
