# Generated by Django 5.2 on 2025-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_assetholder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetholder',
            options={'ordering': ['last_name', 'first_name', 'upn'], 'verbose_name': 'Asset Holder', 'verbose_name_plural': 'Asset Holders'},
        ),
        migrations.AlterModelOptions(
            name='assetholderassignment',
            options={'ordering': ['asset_holder', 'content_type', 'object_id'], 'verbose_name': 'Asset Holder Assignment', 'verbose_name_plural': 'Asset Holder Assignments'},
        ),
    ]
