# Generated by Django 5.2 on 2026-05-24 18:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0002_configtemplate'),
        ('organization', '0004_alter_assetholder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Role',
                'verbose_name_plural': 'Contact Roles',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('web_url', models.URLField(blank=True, verbose_name='Web URL')),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='organization_contacts', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='ContactAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('priority', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('inactive', 'Inactive')], max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.contact')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.contactrole')),
            ],
            options={
                'verbose_name': 'Contact Assignment',
                'verbose_name_plural': 'Contact Assignments',
                'ordering': ['contact', 'role', 'content_type', 'object_id'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'role', 'content_type', 'object_id'), name='organization_contactassignment_unique')],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
