# Generated by Django 5.2 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_contactrole_contact_contactassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50),
        ),
    ]
