# Generated by Django 5.2.15 on 2026-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_assetaudit_unique_together_and_more'),
        ('components', '0003_component_tenant'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='componentstock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='unique_component_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='componentstock',
            constraint=models.UniqueConstraint(fields=('component', 'location'), name='unique_component_location'),
        ),
    ]
