# Generated by Django 5.2 on 2025-04-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0010_installedsoftware'),
        ('extras', '0002_configtemplate'),
        ('organization', '0003_assetholder_user'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptive name for the license (e.g., Visio Pro 2021 - EA Renewal FY24)', max_length=255)),
                ('license_type', models.CharField(choices=[('perpetual_seat', 'Perpetual Seat'), ('subscription_seat', 'Subscription Seat')], default='perpetual_seat', max_length=50)),
                ('product_key', models.TextField(blank=True, help_text='Product key or activation code. Consider security implications.')),
                ('seats', models.PositiveIntegerField(default=1, help_text='Total number of seats purchased or entitled')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, help_text='For term licenses or maintenance', null=True)),
                ('notes', models.TextField(blank=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='software.software')),
                ('tags', models.ManyToManyField(blank=True, related_name='licenses', to='extras.tag')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ('software__manufacturer', 'software__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LicenseSeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='assets.asset')),
                ('assigned_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='organization.assetholder')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='licenses.license')),
            ],
            options={
                'verbose_name': 'License Seat Assignment',
                'verbose_name_plural': 'License Seat Assignments',
                'ordering': ('license', 'asset', 'assigned_holder'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('assigned_holder__isnull', True)), models.Q(('asset__isnull', True), ('assigned_holder__isnull', False)), _connector='OR'), name='chk_assignment_to_one_target')],
            },
        ),
    ]
