# Generated by Django 5.2 on 2026-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_license_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
