# Generated by Django 5.2 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, help_text='For term licenses or maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('perpetual_seat', 'Perpetual Seat'), ('subscription_seat', 'Subscription Seat')], db_index=True, default='perpetual_seat', max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
