# Generated by Django 5.2 on 2026-05-30 20:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_notification_target_url'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('asset_summary', 'Asset Inventory Summary'), ('license_utilization', 'License Utilization'), ('subscription_renewals', 'Subscription Renewals')], max_length=50)),
                ('template_content', models.TextField(blank=True, help_text='Optional Jinja2 custom HTML override template')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('upcoming_eol', 'Upcoming EOL Planning'), ('license_expiry', 'License Expiry Alert'), ('renewal_due', 'Renewal Due Alert')], max_length=50)),
                ('threshold_value', models.PositiveIntegerField(help_text='Limit count or days horizon')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated emails or usernames. Defaults to admins.')),
                ('is_active', models.BooleanField(default=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='alert_rules', to='core.notificationchannel')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('format', models.CharField(choices=[('html', 'HTML Email'), ('csv', 'CSV Attachment')], default='html', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.reporttemplate')),
                ('schedule', models.ForeignKey(blank=True, help_text='Linked Django-Q Schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='django_q.schedule')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='contenttypes.contenttype')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.alertrule')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_alertl_content_706751_idx'), models.Index(fields=['status'], name='core_alertl_status_b2f47a_idx')],
            },
        ),
    ]
