# Generated by Django 5.2 on 2026-06-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduledreport_channels_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LDAPSettings',
        ),
        migrations.DeleteModel(
            name='SAMLSettings',
        ),
    ]
