# Generated by Django 5.2 on 2026-06-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_ldapsettings_delete_samlsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
