# Generated by Django 5.2.15 on 2026-06-03 16:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_permissiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to='attachments/files/', validators=[core.validators.validate_file_attachment]),
        ),
        migrations.AlterField(
            model_name='imageattachment',
            name='image',
            field=models.ImageField(upload_to='attachments/images/', validators=[core.validators.validate_image_attachment]),
        ),
    ]
