# Generated by Django 5.2.15 on 2026-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_fileattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('asset_summary', 'Asset Inventory Summary'), ('license_utilization', 'License Utilization'), ('subscription_renewals', 'Subscription Renewals'), ('asset_maintenance', 'Asset Maintenance & Repairs'), ('asset_depreciation', 'Asset Depreciation Summary'), ('software_inventory', 'Software Catalog & Installations')], max_length=50),
        ),
    ]
