# Generated by Django 5.2.15 on 2026-06-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alertrule_deleted_at_notificationchannel_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_recyclebin', 'Can view Recycle Bin'), ('change_recyclebin', 'Can restore from Recycle Bin'), ('delete_recyclebin', 'Can purge from Recycle Bin')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
