# Generated by Django 5.2.15 on 2026-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recyclebin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
