# Generated by Django 5.2.15 on 2026-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_alertlog_status_alter_alertrule_deleted_at_and_more'),
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_alertrule_name_active'),
        ),
        migrations.AddConstraint(
            model_name='notificationchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_notificationchannel_name_active'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_reporttemplate_name_active'),
        ),
    ]
