# Generated by Django 5.2.15 on 2026-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alertrule_operability_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertlog',
            new_name='core_alertl_severit_f0ec11_idx',
            old_name='core_alertlog_severity_idx',
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20),
        ),
    ]
