# Generated by Django 5.2.15 on 2026-06-13 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_job_tenant'),
        ('organization', '0016_currency_callable_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectchange',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.tenant'),
        ),
    ]
