# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_objectchange_tenant'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_address',
            field=models.EmailField(default='itambox@localhost', max_length=255, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='ITAMbox Notifications', max_length=255, verbose_name='From Name'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_host',
            field=models.CharField(default='localhost', max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=1000, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=25, verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP Use TLS'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP Username'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='test_recipient',
            field=models.EmailField(blank=True, help_text='Email address for test notifications', max_length=255, verbose_name='Test Recipient'),
        ),
        migrations.AlterField(
            model_name='job',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='job',
            name='logs',
            field=models.TextField(blank=True, verbose_name='Logs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.JSONField(blank=True, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled For'),
        ),
        migrations.AlterField(
            model_name='job',
            name='started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=20, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, help_text='Optional destination URL when clicked.', max_length=500, verbose_name='Target URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user for the notification. Null represents global broadcast alert.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('checkout', 'Checked Out'), ('checkin', 'Checked In'), ('audit', 'Audited')], db_index=True, max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='objectchange',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
