# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('core', '0001_initial'),
        ('core', '0002_notification_target_url'),
        ('core', '0003_reporttemplate_alertrule_scheduledreport_alertlog'),
        ('core', '0004_reporttemplate_advanced_mode_and_more'),
        ('core', '0005_alertlog_tenant_alertrule_tenant_and_more'),
        ('core', '0006_reporttemplate_tenant_scheduledreport_tenant'),
        ('core', '0007_reporttemplate_filter_tenants_and_more'),
        ('core', '0008_alertlog_acknowledged_by_alertlog_resolution_notes_and_more'),
        ('core', '0009_scheduledreport_channels_and_more'),
        ('core', '0010_delete_ldapsettings_delete_samlsettings'),
        ('core', '0011_delete_permissiongroup'),
        ('core', '0012_alter_fileattachment_file_and_more'),
        ('core', '0013_alter_reporttemplate_report_type'),
        ('core', '0014_alter_bookmark_unique_together_and_more'),
        ('core', '0015_alertrule_deleted_at_notificationchannel_deleted_at_and_more'),
        ('core', '0016_recyclebin'),
        ('core', '0017_alter_alertlog_status_alter_alertrule_deleted_at_and_more'),
        ('core', '0018_alter_alertrule_name_alter_notificationchannel_name_and_more'),
        ('core', '0019_alertrule_warranty_type_alertlog_severity_delivery'),
        ('core', '0020_phase1_alerting_rework'),
        ('core', '0021_alertrule_operability_fields'),
        ('core', '0022_alertlog_severity_index_and_channel_choices'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_07_organization_history_1'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
                    name='RecycleBin',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'permissions': [('view_recyclebin', 'Can view Recycle Bin'), ('change_recyclebin', 'Can restore from Recycle Bin'), ('delete_recyclebin', 'Can purge from Recycle Bin')],
                        'managed': False,
                        'default_permissions': (),
                    },
                ),
        migrations.CreateModel(
                    name='EmailSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('smtp_host', models.CharField(default='localhost', max_length=255, verbose_name='SMTP Host')),
                        ('smtp_port', models.PositiveIntegerField(default=25, verbose_name='SMTP Port')),
                        ('smtp_use_tls', models.BooleanField(default=True, verbose_name='SMTP Use TLS')),
                        ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP Username')),
                        ('smtp_password', models.CharField(blank=True, max_length=1000, verbose_name='SMTP Password')),
                        ('from_address', models.EmailField(default='itambox@localhost', max_length=255, verbose_name='From Address')),
                        ('from_name', models.CharField(default='ITAMbox Notifications', max_length=255, verbose_name='From Name')),
                        ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                        ('test_recipient', models.EmailField(blank=True, help_text='Email address for test notifications', max_length=255, verbose_name='Test Recipient')),
                    ],
                    options={
                        'verbose_name': 'Email Settings',
                        'verbose_name_plural': 'Email Settings',
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                        ('message', models.TextField(verbose_name='Message')),
                        ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=20, verbose_name='Level')),
                        ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                        ('target_url', models.CharField(blank=True, help_text='Optional destination URL when clicked.', max_length=500, verbose_name='Target URL')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Notification',
                        'verbose_name_plural': 'Notifications',
                        'ordering': ('-created_at',),
                    },
                ),
        migrations.CreateModel(
                    name='ObjectChange',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                        ('user_name', models.CharField(editable=False, max_length=150)),
                        ('request_id', models.UUIDField(editable=False)),
                        ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('checkout', 'Checked Out'), ('checkin', 'Checked In'), ('audit', 'Audited')], db_index=True, max_length=50, verbose_name='Action')),
                        ('changed_object_id', models.PositiveBigIntegerField(db_index=True)),
                        ('related_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                        ('object_repr', models.CharField(editable=False, max_length=200)),
                        ('prechange_data', models.JSONField(blank=True, editable=False, null=True)),
                        ('postchange_data', models.JSONField(blank=True, editable=False, null=True)),
                        ('object_type_repr', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                    ],
                    options={
                        'ordering': ['-time'],
                    },
                ),
        migrations.CreateModel(
                    name='Job',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255, verbose_name='Name')),
                        ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                        ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                        ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                        ('logs', models.TextField(blank=True, verbose_name='Logs')),
                        ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('started', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                        ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Completed')),
                        ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled For')),
                        ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                    ],
                    options={
                        'verbose_name': 'Job',
                        'verbose_name_plural': 'Jobs',
                        'ordering': ['-created'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
