# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('core', '0023_remove_event_eventrule_webhookendpoint'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_18_extras_history_3'),
        ('core', '0100_issue88_shard_08_core_schema'),
    ]

    operations = [

    ]
