# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('core', '0032_alter_emailsettings_enabled_and_more'),
    ]

    dependencies = [
        ('inventory', '0100_issue88_shard_37_inventory_history_1'),
        ('core', '0100_issue88_shard_33_core_history_5'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
                    model_name='job',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='notification',
                    name='user',
                    field=models.ForeignKey(blank=True, help_text='Target user for the notification. Null represents global broadcast alert.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='objectchange',
                    name='changed_object_type',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='objectchange',
                    name='related_object_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
                ),
        migrations.AddField(
                    model_name='objectchange',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='objectchange',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddIndex(
                    model_name='job',
                    index=models.Index(fields=['status', 'scheduled_for'], name='core_job_status_b42200_idx'),
                ),
        migrations.AddIndex(
                    model_name='notification',
                    index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
                ),
        migrations.AddIndex(
                    model_name='objectchange',
                    index=models.Index(fields=['changed_object_type', 'changed_object_id'], name='core_object_changed_c227ce_idx'),
                ),
        migrations.AddIndex(
                    model_name='objectchange',
                    index=models.Index(fields=['related_object_type', 'related_object_id'], name='core_object_related_3375d6_idx'),
                ),
    ]
