# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('core', '0026_remove_reporttemplate_scheduledreport_reportgenerationarchive'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_24_extras_history_6'),
        ('core', '0100_issue88_shard_23_core_history_3'),
    ]

    operations = [

    ]
