# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('core', '0024_remove_exporttemplate_labeltemplate'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_20_extras_history_4'),
        ('core', '0100_issue88_shard_19_core_history_1'),
    ]

    operations = [

    ]
