# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('core', '0027_remove_notificationchannel_alertrule_alertlog'),
        ('core', '0028_encrypt_emailsettings_smtp_password'),
        ('core', '0029_null_to_empty_strings'),
        ('core', '0030_job_tenant'),
        ('core', '0031_objectchange_tenant'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_32_organization_history_2'),
        ('core', '0100_issue88_shard_25_core_history_4'),
    ]

    operations = [

    ]
