# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('core', '0025_remove_journalentry_bookmark_attachments'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_22_extras_history_5'),
        ('core', '0100_issue88_shard_21_core_history_2'),
    ]

    operations = [

    ]
