# Generated by Django 5.2 on 2026-05-29 18:13

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the software product (e.g., Microsoft Visio Professional 2021)', max_length=255, unique=True)),
                ('version', models.CharField(blank=True, help_text='Current version (e.g., 2021, 16.0)', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('operating_system', 'Operating System'), ('productivity', 'Productivity'), ('development', 'Development'), ('security', 'Security'), ('design', 'Design'), ('other', 'Other')], db_index=True, help_text='Functional category', max_length=50)),
                ('license_type', models.CharField(blank=True, choices=[('proprietary', 'Proprietary'), ('open_source', 'Open Source'), ('freeware', 'Freeware'), ('shareware', 'Shareware'), ('subscription', 'Subscription')], help_text='Default license type', max_length=50)),
                ('website', models.URLField(blank=True, help_text='Product homepage or vendor URL')),
                ('description', models.TextField(blank=True, help_text='Optional description of the software product.')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_products', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='software', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('manufacturer', 'name'),
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
