# Generated by Django 5.2 on 2025-04-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0009_remove_asset_manufacturer_remove_asset_model_and_more'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the software product (e.g., Microsoft Visio Professional 2021)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the software product.')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_products', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='software', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ('manufacturer', 'name'),
            },
        ),
    ]
