# Generated by Django 5.2 on 2026-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='category',
            field=models.CharField(blank=True, choices=[('operating_system', 'Operating System'), ('productivity', 'Productivity'), ('development', 'Development'), ('security', 'Security'), ('design', 'Design'), ('other', 'Other')], db_index=True, help_text='Functional category', max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='license_type',
            field=models.CharField(blank=True, choices=[('proprietary', 'Proprietary'), ('open_source', 'Open Source'), ('freeware', 'Freeware'), ('shareware', 'Shareware'), ('subscription', 'Subscription')], help_text='Default license type', max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, help_text='Current version (e.g., 2021, 16.0)', max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='website',
            field=models.URLField(blank=True, help_text='Product homepage or vendor URL'),
        ),
    ]
