# Generated by Django 5.2 on 2026-05-29 18:13

import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Checkout Quantity')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Accessory Assignment',
                'verbose_name_plural': 'Accessory Assignments',
                'ordering': ('-assigned_date',),
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AccessoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Accessory Stock',
                'verbose_name_plural': 'Accessory Stocks',
                'ordering': ('accessory', 'location'),
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100)),
                ('min_qty', models.PositiveIntegerField(default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                ('allow_overallocate', models.BooleanField(default=False, help_text='Allow consumption count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consumable',
                'verbose_name_plural': 'Consumables',
                'ordering': ('manufacturer', 'name'),
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConsumableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Consumed Quantity')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consumable Consumption',
                'verbose_name_plural': 'Consumable Consumptions',
                'ordering': ('-assigned_date',),
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consumable Stock',
                'verbose_name_plural': 'Consumable Stocks',
                'ordering': ('consumable', 'location'),
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kit Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'ordering': ['name'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity to checkout (only applies to Accessories)', verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Kit Item',
                'verbose_name_plural': 'Kit Items',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100)),
                ('min_qty', models.PositiveIntegerField(default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                ('allow_overallocate', models.BooleanField(default=False, help_text='Allow checkout count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'applies_to__accessory': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='assets.category', verbose_name='Category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.manufacturer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accessories', to='assets.supplier', verbose_name='Supplier')),
                ('tags', models.ManyToManyField(blank=True, related_name='accessories', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ('manufacturer', 'name'),
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
