# Generated by Django 5.2 on 2026-05-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('extras', '0001_initial'),
        ('inventory', '0001_initial'),
        ('licenses', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.accessory'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_assignments', to='organization.assetholder'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_assignments', to='organization.location'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_checkouts', to='organization.location', verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='accessorystock',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.accessory'),
        ),
        migrations.AddField(
            model_name='accessorystock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_stocks', to='organization.location'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'applies_to__consumable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='assets.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='assets.manufacturer'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='consumables', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions', to='organization.assetholder'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions', to='organization.location'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions_out', to='organization.location', verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_stocks', to='organization.location'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='kits', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.accessory', verbose_name='Accessory Catalog Item'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='assets.assettype', verbose_name='Asset Type / Model'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.kit', verbose_name='Kit'),
        ),
        migrations.AddField(
            model_name='kititem',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='licenses.license', verbose_name='Software License'),
        ),
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AddConstraint(
            model_name='accessoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_holder__isnull', True), ('assigned_location__isnull', False)), _connector='OR'), name='chk_accessory_assignment_single_target'),
        ),
        migrations.AlterUniqueTogether(
            name='accessorystock',
            unique_together={('accessory', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='consumable',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AddConstraint(
            model_name='consumableassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_holder__isnull', True), ('assigned_location__isnull', False)), _connector='OR'), name='chk_consumable_assignment_single_target'),
        ),
        migrations.AlterUniqueTogether(
            name='consumablestock',
            unique_together={('consumable', 'location')},
        ),
        migrations.AddConstraint(
            model_name='kititem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('asset_type__isnull', False), ('license__isnull', True)), models.Q(('accessory__isnull', False), ('asset_type__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('license__isnull', False)), _connector='OR'), name='chk_kit_item_single_target'),
        ),
    ]
