# Generated by Django 5.2.15 on 2026-06-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='organization.tenant'),
        ),
    ]
