# Generated by Django 5.2.15 on 2026-06-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_assetaudit_unique_together_and_more'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('inventory', '0002_alter_accessory_tenant'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='new_components', to='extras.tag'),
        ),
        migrations.AlterField(
            model_name='component',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_allocations', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_allocations', to='organization.location', verbose_name='From Location'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='component_allocations', to='extras.tag'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_stocks', to='organization.location'),
        ),
    ]
