# Generated by Django 5.2.15 on 2026-06-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_component_tags_alter_component_tenant_and_more'),
        ('organization', '0011_remove_assetholder_organization_assetholder_unique_upn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.accessory'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.accessory'),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='component',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.component'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.component'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_stocks', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.consumable'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.consumable'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
