# Generated by Django 5.2.15 on 2026-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_alter_tag_name_alter_tag_slug_and_more'),
        ('inventory', '0004_alter_accessory_deleted_at_and_more'),
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kit Name'),
        ),
        migrations.AddConstraint(
            model_name='kit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_kit_name_active'),
        ),
    ]
