# Generated by Django 5.2.15 on 2026-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_assetaudit_unique_together_and_more'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('inventory', '0005_remove_accessoryassignment_chk_accessory_assignment_single_target_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accessorystock',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumable',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='consumablestock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='inventory_accessory_unique_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='accessorystock',
            constraint=models.UniqueConstraint(fields=('accessory', 'location'), name='inventory_accessorystock_unique_accessory_location'),
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'name'), name='inventory_consumable_unique_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='consumablestock',
            constraint=models.UniqueConstraint(fields=('consumable', 'location'), name='inventory_consumablestock_unique_consumable_location'),
        ),
    ]
