# Generated by Django 5.2.15 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_accessory_slug_alter_component_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
        migrations.AddField(
            model_name='component',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
    ]
