# Generated by Django 5.2.15 on 2026-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_asset_uniq_active_tenant_serial'),
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('inventory', '0007_signed_stock_qty'),
        ('organization', '0016_currency_callable_default'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessory',
            name='inventory_accessory_unique_manufacturer_name',
        ),
        migrations.RemoveConstraint(
            model_name='component',
            name='unique_component_manufacturer_name',
        ),
        migrations.RemoveConstraint(
            model_name='consumable',
            name='inventory_consumable_unique_manufacturer_name',
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='inventory_accessory_unique_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='unique_component_manufacturer_name'),
        ),
        migrations.AddConstraint(
            model_name='consumable',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='inventory_consumable_unique_manufacturer_name'),
        ),
    ]
