# Generated by Django 5.2.15 on 2026-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('inventory', '0008_remove_accessory_inventory_accessory_unique_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='components', to='extras.tag'),
        ),
    ]
