# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('inventory', '0009_alter_component_tags'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.accessory', verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='assets.asset', verbose_name='Assigned Asset'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_assignments', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.accessory', verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='component',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='component',
            name='specs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Specs'),
        ),
        migrations.AlterField(
            model_name='component',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='components', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='component',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_allocations', to='assets.asset', verbose_name='Assigned Asset'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='componentallocation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='component_allocations', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_stocks', to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='assets.asset', verbose_name='Assigned Asset'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.consumable', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='consumableassignment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_assignments', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.consumable', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='kits', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
