# Generated by Django 5.2.15 on 2026-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_accessory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='component',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN'),
        ),
    ]
