# Generated by Django 5.2.15 on 2026-07-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_accessory_ean_component_ean_consumable_ean'),
        ('organization', '0037_tenantresourcegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryassignment',
            name='resource_grant',
            field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='source_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='target_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
        ),
        migrations.AddField(
            model_name='accessorystock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='resource_grant',
            field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='source_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='target_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
        ),
        migrations.AddField(
            model_name='componentstock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='resource_grant',
            field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='source_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='target_tenant',
            field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
