# Generated by Django 5.2.15 on 2026-07-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_backfill_stock_tenant_and_provenance'),
        ('organization', '0037_tenantresourcegrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorystock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
