# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('inventory', '0010_alter_accessory_category_and_more'),
        ('inventory', '0011_accessory_ean_component_ean_consumable_ean'),
        ('inventory', '0012_accessoryassignment_resource_grant_and_more'),
        ('inventory', '0013_backfill_stock_tenant_and_provenance'),
        ('inventory', '0014_alter_accessorystock_tenant_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_55_organization_history_7'),
        ('inventory', '0100_issue88_shard_37_inventory_history_1'),
    ]

    operations = [
        migrations.AddField(
                    model_name='accessory',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='accessory',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.accessory', verbose_name='Accessory'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='assigned_asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='assets.asset', verbose_name='Assigned Asset'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='assigned_holder',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='assigned_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='from_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checkouts', to='organization.location', verbose_name='From Location'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='resource_grant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='source_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='%(class)s_assignments', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='accessoryassignment',
                    name='target_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
                ),
        migrations.AddField(
                    model_name='accessorystock',
                    name='accessory',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.accessory', verbose_name='Accessory'),
                ),
        migrations.AddField(
                    model_name='accessorystock',
                    name='location',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='accessorystock',
                    name='tenant',
                    field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='component',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.category', verbose_name='Category'),
                ),
        migrations.AddField(
                    model_name='component',
                    name='manufacturer',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.manufacturer', verbose_name='Manufacturer'),
                ),
        migrations.AddField(
                    model_name='component',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_%(class)ss', to='assets.supplier', verbose_name='Supplier'),
                ),
        migrations.AddField(
                    model_name='component',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='components', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='component',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='assigned_asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_allocations', to='assets.asset', verbose_name='Assigned Asset'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='assigned_holder',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='assigned_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='component',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.component', verbose_name='Component'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='from_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_allocations', to='organization.location', verbose_name='From Location'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='resource_grant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='source_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='component_allocations', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='componentallocation',
                    name='target_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
                ),
        migrations.AddField(
                    model_name='componentstock',
                    name='component',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.component', verbose_name='Component'),
                ),
        migrations.AddField(
                    model_name='componentstock',
                    name='location',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_stocks', to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='componentstock',
                    name='tenant',
                    field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='consumable',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.category', verbose_name='Category'),
                ),
        migrations.AddField(
                    model_name='consumable',
                    name='manufacturer',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='assets.manufacturer', verbose_name='Manufacturer'),
                ),
        migrations.AddField(
                    model_name='consumable',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_%(class)ss', to='assets.supplier', verbose_name='Supplier'),
                ),
        migrations.AddField(
                    model_name='consumable',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='consumable',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='assigned_asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='assets.asset', verbose_name='Assigned Asset'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='assigned_holder',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='assigned_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to='organization.location', verbose_name='Assigned Location'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='consumable',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.consumable', verbose_name='Consumable'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='from_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checkouts', to='organization.location', verbose_name='From Location'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='resource_grant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='The grant that authorized a cross-tenant assignment. Stays as history after the grant is revoked.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenantresourcegrant', verbose_name='Resource grant'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='source_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant owning the source stock/location at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Source tenant'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='%(class)s_assignments', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='consumableassignment',
                    name='target_tenant',
                    field=models.ForeignKey(blank=True, editable=False, help_text='Tenant of the destination holder/location/asset at assignment time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.tenant', verbose_name='Target tenant'),
                ),
        migrations.AddField(
                    model_name='consumablestock',
                    name='consumable',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.consumable', verbose_name='Consumable'),
                ),
        migrations.AddField(
                    model_name='consumablestock',
                    name='location',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_stocks', to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='consumablestock',
                    name='tenant',
                    field=models.ForeignKey(editable=False, help_text="Owning tenant — always the stock location's tenant.", on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='kit',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='kits', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='kit',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='accessory',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.accessory', verbose_name='Accessory Catalog Item'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='asset_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='assets.assettype', verbose_name='Asset Type / Model'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='component',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.component', verbose_name='Component Catalog Item'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='consumable',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='inventory.consumable', verbose_name='Consumable Catalog Item'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='kit',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.kit', verbose_name='Kit'),
                ),
        migrations.AddField(
                    model_name='kititem',
                    name='license',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='licenses.license', verbose_name='Software License'),
                ),
        migrations.AddConstraint(
                    model_name='accessory',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='inventory_accessory_unique_manufacturer_name'),
                ),
        migrations.AddConstraint(
                    model_name='accessoryassignment',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', True), ('assigned_location__isnull', False)), models.Q(('assigned_asset__isnull', False), ('assigned_holder__isnull', True), ('assigned_location__isnull', True)), _connector='OR'), name='chk_accessory_assignment_single_target'),
                ),
        migrations.AddConstraint(
                    model_name='accessorystock',
                    constraint=models.UniqueConstraint(fields=('accessory', 'location'), name='inventory_accessorystock_unique_accessory_location'),
                ),
        migrations.AddConstraint(
                    model_name='component',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='unique_component_manufacturer_name'),
                ),
        migrations.AddConstraint(
                    model_name='componentallocation',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', True), ('assigned_location__isnull', False)), models.Q(('assigned_asset__isnull', False), ('assigned_holder__isnull', True), ('assigned_location__isnull', True)), _connector='OR'), name='chk_componentallocation_single_target'),
                ),
        migrations.AddConstraint(
                    model_name='componentstock',
                    constraint=models.UniqueConstraint(fields=('component', 'location'), name='unique_component_location'),
                ),
        migrations.AddConstraint(
                    model_name='consumable',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'name'), name='inventory_consumable_unique_manufacturer_name'),
                ),
        migrations.AddConstraint(
                    model_name='consumableassignment',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_holder__isnull', True), ('assigned_location__isnull', False)), models.Q(('assigned_asset__isnull', False), ('assigned_holder__isnull', True), ('assigned_location__isnull', True)), _connector='OR'), name='chk_consumable_assignment_single_target'),
                ),
        migrations.AddConstraint(
                    model_name='consumablestock',
                    constraint=models.UniqueConstraint(fields=('consumable', 'location'), name='inventory_consumablestock_unique_consumable_location'),
                ),
        migrations.AddConstraint(
                    model_name='kit',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_kit_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='kititem',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('asset_type__isnull', False), ('component__isnull', True), ('consumable__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', False), ('asset_type__isnull', True), ('component__isnull', True), ('consumable__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('consumable__isnull', True), ('license__isnull', False)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('consumable__isnull', False), ('license__isnull', True)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('component__isnull', False), ('consumable__isnull', True), ('license__isnull', True)), _connector='OR'), name='chk_kit_item_single_target'),
                ),
    ]
