# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('inventory', '0008_remove_accessory_inventory_accessory_unique_manufacturer_name_and_more'),
        ('inventory', '0009_alter_component_tags'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_36_assets_history_7'),
        ('inventory', '0100_issue88_shard_12_inventory_schema'),
    ]

    operations = [

    ]
