# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('inventory', '0001_initial'),
        ('inventory', '0002_alter_accessory_tenant'),
        ('inventory', '0003_alter_component_tags_alter_component_tenant_and_more'),
        ('inventory', '0004_alter_accessory_deleted_at_and_more'),
        ('inventory', '0005_alter_accessory_slug_alter_component_slug_and_more'),
        ('inventory', '0006_accessory_custom_field_data_and_more'),
        ('inventory', '0007_signed_stock_qty'),
    ]

    dependencies = [
        ('licenses', '0100_issue88_shard_11_licenses_schema'),
    ]

    operations = [
        migrations.CreateModel(
                    name='AccessoryAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.PositiveIntegerField(default=1, verbose_name='Checkout Quantity')),
                        ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'Accessory Assignment',
                        'verbose_name_plural': 'Accessory Assignments',
                        'ordering': ('-assigned_date',),
                        'abstract': False,
                    },
                    bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='AccessoryStock',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                    ],
                    options={
                        'verbose_name': 'Accessory Stock',
                        'verbose_name_plural': 'Accessory Stocks',
                        'ordering': ('location',),
                        'abstract': False,
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Component',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                        ('part_number', models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number')),
                        ('ean', models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN')),
                        ('min_qty', models.PositiveIntegerField(blank=True, default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                        ('allow_overallocate', models.BooleanField(default=False, help_text='Allow checkout count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                        ('specs', models.JSONField(blank=True, default=dict, verbose_name='Specs')),
                    ],
                    options={
                        'verbose_name': 'Component (Catalog)',
                        'verbose_name_plural': 'Components (Catalog)',
                        'ordering': ('manufacturer', 'name'),
                        'abstract': False,
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ComponentAllocation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.PositiveIntegerField(default=1, verbose_name='Checkout Quantity')),
                        ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'Component Allocation',
                        'verbose_name_plural': 'Component Allocations',
                        'ordering': ('-assigned_date',),
                        'abstract': False,
                    },
                    bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ComponentStock',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                    ],
                    options={
                        'verbose_name': 'Component Stock',
                        'verbose_name_plural': 'Component Stocks',
                        'ordering': ('location',),
                        'abstract': False,
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Consumable',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                        ('part_number', models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number')),
                        ('ean', models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN')),
                        ('min_qty', models.PositiveIntegerField(blank=True, default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                        ('allow_overallocate', models.BooleanField(default=False, help_text='Allow checkout count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'Consumable',
                        'verbose_name_plural': 'Consumables',
                        'ordering': ('manufacturer', 'name'),
                        'abstract': False,
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ConsumableAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.PositiveIntegerField(default=1, verbose_name='Checkout Quantity')),
                        ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned Date')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'Consumable Consumption',
                        'verbose_name_plural': 'Consumable Consumptions',
                        'ordering': ('-assigned_date',),
                        'abstract': False,
                    },
                    bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ConsumableStock',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                    ],
                    options={
                        'verbose_name': 'Consumable Stock',
                        'verbose_name_plural': 'Consumable Stocks',
                        'ordering': ('location',),
                        'abstract': False,
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Kit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Kit Name')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Kit',
                        'verbose_name_plural': 'Kits',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='KitItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('qty', models.PositiveIntegerField(default=1, help_text='Quantity to checkout (applies to Accessories, Consumables, and Components)', verbose_name='Quantity')),
                    ],
                    options={
                        'verbose_name': 'Kit Item',
                        'verbose_name_plural': 'Kit Items',
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Accessory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=255, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                        ('part_number', models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100, verbose_name='Part Number')),
                        ('ean', models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scannable to open this item.', max_length=14, verbose_name='EAN')),
                        ('min_qty', models.PositiveIntegerField(blank=True, default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                        ('allow_overallocate', models.BooleanField(default=False, help_text='Allow checkout count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                        ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.category', verbose_name='Category')),
                        ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.manufacturer', verbose_name='Manufacturer')),
                        ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accessories', to='assets.supplier', verbose_name='Supplier')),
                        ('tags', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', to='extras.tag', verbose_name='Tags')),
                    ],
                    options={
                        'verbose_name': 'Accessory',
                        'verbose_name_plural': 'Accessories',
                        'ordering': ('manufacturer', 'name'),
                        'abstract': False,
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
