# Generated by Django 5.2.16 on 2026-08-02 19:58

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0100_issue88_shard_56_inventory_relations"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoryassignment',
            options={'base_manager_name': 'base_objects', 'default_manager_name': 'objects', 'ordering': ('-assigned_date',), 'verbose_name': 'Accessory Assignment', 'verbose_name_plural': 'Accessory Assignments'},
        ),
        migrations.AlterModelOptions(
            name='componentallocation',
            options={'base_manager_name': 'base_objects', 'default_manager_name': 'objects', 'ordering': ('-assigned_date',), 'verbose_name': 'Component Allocation', 'verbose_name_plural': 'Component Allocations'},
        ),
        migrations.AlterModelOptions(
            name='consumableassignment',
            options={'base_manager_name': 'base_objects', 'default_manager_name': 'objects', 'ordering': ('-assigned_date',), 'verbose_name': 'Consumable Consumption', 'verbose_name_plural': 'Consumable Consumptions'},
        ),
        migrations.AlterModelManagers(
            name='accessoryassignment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='componentallocation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='consumableassignment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='system_authorization_operation',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='system_authorization_reason',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='system_authorization_operation',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='componentallocation',
            name='system_authorization_reason',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='system_authorization_operation',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='system_authorization_reason',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
