# Generated by Django 5.2.17 on 2026-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0101_alter_accessoryassignment_options_and_more"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="kititem",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="kititem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
