# Generated by Django 5.2.16 on 2026-08-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0101_alter_accessoryassignment_options_and_more'),
        ('organization', '0104_alter_tenant_changelog_retention_days'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN, UPC, or GTIN). Scan it to open this item.', max_length=14, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='accessorystock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text='Tenant of the stock location.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='component',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN, UPC, or GTIN). Scan it to open this item.', max_length=14, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='componentstock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text='Tenant of the stock location.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN, UPC, or GTIN). Scan it to open this item.', max_length=14, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='consumablestock',
            name='tenant',
            field=models.ForeignKey(editable=False, help_text='Tenant of the stock location.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
