# Generated by Django 5.2.17 on 2026-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0102_kititem_leaf_deleted_at"),
        ("organization", "0103_tenant_resource_grant_expiry"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessorystock",
            name="inventory_accessorystock_unique_accessory_location",
        ),
        migrations.RemoveConstraint(
            model_name="componentstock",
            name="unique_component_location",
        ),
        migrations.RemoveConstraint(
            model_name="consumablestock",
            name="inventory_consumablestock_unique_consumable_location",
        ),
        migrations.AddField(
            model_name="accessorystock",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="accessorystock",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="componentstock",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="componentstock",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="consumablestock",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="consumablestock",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="accessorystock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("accessory", "location"),
                name="inventory_accessorystock_unique_accessory_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("component", "location"),
                name="unique_component_location",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumablestock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("consumable", "location"),
                name="inventory_consumablestock_unique_consumable_location",
            ),
        ),
    ]
