# Generated by Django 5.2 on 2026-06-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ('user',), 'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
    ]
