# Generated by Django 5.2 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
