# Generated by Django 5.2 on 2026-05-29 18:13

import core.mixins
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_object_id', models.PositiveIntegerField()),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('expected_checkin_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-checked_out_at'],
            },
            bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Request',
                'verbose_name_plural': 'Asset Requests',
                'ordering': ['-request_date'],
            },
            bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetTagSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='ASSET-', max_length=20, unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('zero_padding', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Asset Tag Sequence',
                'verbose_name_plural': 'Asset Tag Sequences',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('part_number', models.CharField(blank=True, db_index=True, help_text='Manufacturer part number or SKU', max_length=100)),
                ('cpu', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Processor (CPU)')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage_capacity_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Storage (GB)')),
                ('storage_type', models.CharField(blank=True, choices=[('ssd', 'SSD'), ('nvme', 'NVMe SSD'), ('hdd', 'HDD'), ('emmc', 'eMMC'), ('', 'Other/Unknown')], max_length=10, verbose_name='Storage Type')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='Graphics (GPU)')),
                ('eol_months', models.PositiveIntegerField(blank=True, help_text='Lifespan in months before EOL replacement', null=True, verbose_name='EOL (Months)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='asset_types/', verbose_name='Model Image')),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('requestable', models.BooleanField(db_index=True, default=False, help_text='Allow users to request assets of this type')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('color', models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email_on_checkout', models.BooleanField(default=False, help_text='Send email notification on asset checkout')),
                ('email_on_checkin', models.BooleanField(default=False, help_text='Send email notification on asset checkin')),
                ('require_acceptance', models.BooleanField(default=False, help_text='Require digital acceptance on checkout')),
                ('email_eula', models.TextField(blank=True, verbose_name='EULA Text')),
                ('applies_to', models.JSONField(blank=True, default=dict, help_text="Applies to: {'asset': True, 'accessory': True, 'component': True}")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text='Slug-like name (e.g. sim_card_number)', unique=True, verbose_name='Field Name')),
                ('label', models.CharField(db_index=True, max_length=100, verbose_name='Display Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select / Dropdown')], db_index=True, default='text', max_length=50, verbose_name='Field Type')),
                ('choices', models.TextField(blank=True, help_text="New-line separated list of choices (only for 'select' type)", null=True)),
                ('required', models.BooleanField(db_index=True, default=False, verbose_name='Required')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'db_table': 'assets_customfield',
                'ordering': ['label'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomFieldset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fieldset Name')),
            ],
            options={
                'verbose_name': 'Custom Fieldset',
                'verbose_name_plural': 'Custom Fieldsets',
                'db_table': 'assets_customfieldset',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Depreciation Name')),
                ('months', models.PositiveIntegerField(help_text='Useful lifespan in months for straight-line calculations', verbose_name='Lifespan (Months)')),
            ],
            options={
                'verbose_name': 'Depreciation',
                'verbose_name_plural': 'Depreciations',
                'ordering': ['name'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_detected', models.CharField(blank=True, help_text='Specific version discovered on the asset (e.g., 16.78.1)', max_length=100)),
                ('install_date', models.DateField(blank=True, db_index=True, help_text='Estimated or known installation date', null=True)),
                ('discovered_by_agent', models.CharField(blank=True, help_text='Identifier for the discovery source or agent (e.g., SCCM, Intune, Lansweeper)', max_length=100, verbose_name='Discovered By')),
                ('last_seen_date', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this software was last detected on the asset', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes specific to this installation')),
            ],
            options={
                'verbose_name': 'Installed Software Instance',
                'verbose_name_plural': 'Installed Software Instances',
                'ordering': ['asset', 'software', '-last_seen_date'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('deployable', 'Deployable'), ('deployed', 'Deployed'), ('pending', 'Pending'), ('undeployable', 'Undeployable'), ('archived', 'Archived')], db_index=True, default='deployable', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6)),
            ],
            options={
                'verbose_name': 'Status Label',
                'verbose_name_plural': 'Status Labels',
                'ordering': ['name'],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_at', 'Created'), ('updated_at', 'Updated'), ('checked_out', 'Checked Out'), ('checked_in', 'Checked In'), ('audited', 'Audited')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, db_index=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, db_index=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Cost')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Order Number')),
                ('salvage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salvage Value')),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_audited', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Audited')),
                ('custom_values', models.JSONField(blank=True, default=dict, verbose_name='Custom Values')),
                ('requestable', models.BooleanField(db_index=True, default=False, help_text='Allow users to request this asset')),
                ('last_audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_assets', to=settings.AUTH_USER_MODEL, verbose_name='Last Audited By')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.mixins.CustomFieldDataMixin, core.mixins.BookmarkableMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
