# Generated by Django 5.2 on 2026-05-29 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0001_initial'),
        ('organization', '0001_initial'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_to_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_assignments', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_requests_tagged', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='assetrole',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_roles', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetrole'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_types', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='customfieldset',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='fieldsets', to='assets.customfield', verbose_name='Custom Fields'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='custom_fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.customfieldset', verbose_name='Custom Fieldset'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='depreciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.depreciation', verbose_name='Depreciation'),
        ),
        migrations.AddField(
            model_name='installedsoftware',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='installedsoftware',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_instances', to='software.software'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.manufacturer'),
        ),
        migrations.AddField(
            model_name='statuslabel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='status_labels_tagged', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.statuslabel'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['assigned_to_content_type', 'assigned_to_object_id'], name='assets_asse_assigne_b44734_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset',), name='unique_active_assignment_per_asset'),
        ),
        migrations.AlterUniqueTogether(
            name='installedsoftware',
            unique_together={('asset', 'software', 'version_detected')},
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together={('manufacturer', 'model')},
        ),
    ]
