# Generated by Django 5.2 on 2025-04-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_asset_holder_alter_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='chk_asset_assignee_exclusive',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_holder',
        ),
    ]
