# Generated by Django 5.2 on 2025-04-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_chk_asset_assignee_exclusive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
    ]
