# Generated by Django 5.2 on 2026-05-29 23:31

import core.mixins
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetassignment_checked_out_at'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Target location expected to be audited. If omitted, applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.location')),
            ],
            options={
                'ordering': ['-started_at'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('verification_method', models.CharField(choices=[('barcode', 'Barcode Scan'), ('rfid', 'RFID Reader'), ('manual', 'Manual Input'), ('auto', 'Agent API Handshake')], default='manual', max_length=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets.asset')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_performed', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='The observed physical location of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='organization.location')),
                ('status', models.ForeignKey(help_text='The observed physical status of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='assets.statuslabel')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='assets.auditsession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('session', 'asset')},
            },
        ),
    ]
