# Generated by Django 5.2 on 2025-04-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AssetRole',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='category',
            new_name='asset_role',
        ),
    ]
