# Generated by Django 5.2 on 2025-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_rename_category_assetrole_and_more'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='extras.tag'),
        ),
    ]
