# Generated by Django 5.2 on 2026-05-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auditsession_assetaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetaudit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Asset Audit', 'verbose_name_plural': 'Asset Audits'},
        ),
        migrations.AlterModelOptions(
            name='auditsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Audit Session', 'verbose_name_plural': 'Audit Sessions'},
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='pre_checkout_status',
            field=models.ForeignKey(blank=True, help_text='Preserved status label to revert to upon checkin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_pre_checkouts', to='assets.statuslabel'),
        ),
    ]
