# Generated by Django 5.2 on 2026-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetaudit_options_alter_auditsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Values'),
        ),
    ]
