# Generated by Django 5.2 on 2025-04-14 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_tags'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrole',
            options={'ordering': ('name',), 'verbose_name': 'Asset Role', 'verbose_name_plural': 'Asset Roles'},
        ),
        migrations.AddField(
            model_name='assetrole',
            name='color',
            field=models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6),
        ),
        migrations.AddField(
            model_name='assetrole',
            name='config_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_roles', to='extras.configtemplate'),
        ),
        migrations.AddField(
            model_name='assetrole',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetrole',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_roles', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
