# Generated by Django 5.2 on 2025-04-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetrole_options_assetrole_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
