# Generated by Django 5.2 on 2025-04-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_manufacturer_slug'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part number or SKU', max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='Processor (CPU)')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage_capacity_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Storage (GB)')),
                ('storage_type', models.CharField(blank=True, choices=[('ssd', 'SSD'), ('nvme', 'NVMe SSD'), ('hdd', 'HDD'), ('emmc', 'eMMC'), ('', 'Other/Unknown')], max_length=10, verbose_name='Storage Type')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='Graphics (GPU)')),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='asset_types', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype'),
        ),
    ]
