# Generated by Django 5.2 on 2025-04-15 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_manufacturer_remove_asset_model_and_more'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_detected', models.CharField(blank=True, help_text='Specific version discovered on the asset (e.g., 16.78.1)', max_length=100)),
                ('install_date', models.DateField(blank=True, help_text='Estimated or known installation date', null=True)),
                ('discovered_by_agent', models.CharField(blank=True, help_text='Identifier for the discovery source or agent (e.g., SCCM, Intune, Lansweeper)', max_length=100, verbose_name='Discovered By')),
                ('last_seen_date', models.DateTimeField(blank=True, help_text='Timestamp when this software was last detected on the asset', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes specific to this installation')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='assets.asset')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_instances', to='software.software')),
            ],
            options={
                'verbose_name': 'Installed Software',
                'verbose_name_plural': 'Installed Software',
                'ordering': ('asset', 'software', 'version_detected'),
                'unique_together': {('asset', 'software', 'version_detected')},
            },
        ),
    ]
