# Generated by Django 5.2 on 2026-06-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_options_alter_assetrole_options_and_more'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0003_alter_region_options_alter_site_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='assets_asse_assigne_b44734_idx',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_to_content_type',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='assigned_to_object_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_book_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Materialized depreciation value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_assignments', to='assets.assetassignment'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='organization.location'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='organization.assetholder'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', True), ('assigned_user__isnull', False)), models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', False), ('assigned_user__isnull', True)), models.Q(('assigned_asset__isnull', False), ('assigned_location__isnull', True), ('assigned_user__isnull', True)), _connector='OR'), name='exactly_one_assignment_target'),
        ),
    ]
