# Generated by Django 5.2 on 2025-04-15 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_installedsoftware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'verbose_name': 'Asset Type', 'verbose_name_plural': 'Asset Types'},
        ),
        migrations.AlterModelOptions(
            name='installedsoftware',
            options={'ordering': ['asset', 'software', '-last_seen_date'], 'verbose_name': 'Installed Software Instance', 'verbose_name_plural': 'Installed Software Instances'},
        ),
        migrations.RenameField(
            model_name='assettype',
            old_name='created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='assettype',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='installedsoftware',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installedsoftware',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
