# Generated by Django 5.2 on 2026-06-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_assetassignment_assets_asse_assigne_b44734_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_assignments', to='assets.asset'),
        ),
    ]
