# Generated by Django 5.2 on 2026-06-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_assetassignment_assigned_asset'),
        ('compliance', '0002_custodyreceipt_disclaimer_custodyreceipt_eula_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custody_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='compliance.custodytemplate'),
        ),
    ]
