# Generated by Django 5.2 on 2025-04-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_created_asset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created',
        ),
        migrations.RemoveField(
            model_name='assetrole',
            name='created',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='installedsoftware',
            name='created',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='created',
        ),
    ]
