# Generated by Django 5.2 on 2026-06-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_category_custody_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='custody_template',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email_eula',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email_on_checkin',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email_on_checkout',
        ),
        migrations.RemoveField(
            model_name='category',
            name='require_acceptance',
        ),
    ]
