# Generated by Django 5.2 on 2026-05-23 08:20

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_asset_created_remove_assetrole_created_and_more'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('ram', 'Memory (RAM)'), ('storage', 'Storage (SSD/HDD)'), ('gpu', 'Graphics Card (GPU)'), ('cpu', 'Processor (CPU)'), ('nic', 'Network Card (NIC)'), ('other', 'Other')], default='other', max_length=50)),
                ('part_number', models.CharField(blank=True, help_text='SKU or part number', max_length=100)),
                ('specs', models.CharField(blank=True, help_text='Specific capacity/speed details (e.g. 16GB DDR5 5600MHz)', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_types', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='component_types', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Component Type',
                'verbose_name_plural': 'Component Types',
                'ordering': ('manufacturer', 'name'),
                'unique_together': {('manufacturer', 'name')},
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, help_text='Physical serial number of the part', max_length=100)),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('in_stock', 'In Stock'), ('defective', 'Defective')], default='in_stock', max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='assets.asset')),
                ('tags', models.ManyToManyField(blank=True, related_name='component_instances', to='extras.tag')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='assets.componenttype')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ('component_type', 'serial_number'),
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
