# Generated by Django 5.2 on 2026-05-23 08:29

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_componenttype_componentinstance'),
        ('extras', '0002_configtemplate'),
        ('organization', '0004_alter_assetholder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('charger', 'Charger'), ('adaptor', 'Adapter/Dongle'), ('display', 'Display/Monitor'), ('cable', 'Cable'), ('other', 'Other')], default='other', max_length=50)),
                ('part_number', models.CharField(blank=True, help_text='SKU or manufacturer part number', max_length=100)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Total Stock')),
                ('min_qty', models.PositiveIntegerField(default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                ('allow_overallocate', models.BooleanField(default=False, help_text='Allow checkout count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                ('notes', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='accessories', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
                'ordering': ('manufacturer', 'name'),
                'unique_together': {('manufacturer', 'name')},
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Checkout Quantity')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.accessory')),
                ('assigned_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_assignments', to='organization.assetholder')),
                ('assigned_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_assignments', to='organization.location')),
            ],
            options={
                'verbose_name': 'Accessory Assignment',
                'verbose_name_plural': 'Accessory Assignments',
                'ordering': ('-assigned_date',),
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('toner', 'Toner/Ink'), ('ink', 'Ink Cartridge'), ('batteries', 'Batteries'), ('thermal_paste', 'Thermal Paste'), ('paper', 'Printer Paper'), ('other', 'Other')], default='other', max_length=50)),
                ('part_number', models.CharField(blank=True, help_text='SKU or manufacturer part number', max_length=100)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Total Quantity')),
                ('min_qty', models.PositiveIntegerField(default=0, help_text='Alert threshold quantity', verbose_name='Safety Threshold')),
                ('allow_overallocate', models.BooleanField(default=False, help_text='Allow consumption count to exceed stock capacity', verbose_name='Allow Over-allocation')),
                ('notes', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='consumables', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Consumable',
                'verbose_name_plural': 'Consumables',
                'ordering': ('manufacturer', 'name'),
                'unique_together': {('manufacturer', 'name')},
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='ConsumableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Consumed Quantity')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('assigned_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions', to='organization.assetholder')),
                ('assigned_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions', to='organization.location')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='assets.consumable')),
            ],
            options={
                'verbose_name': 'Consumable Consumption',
                'verbose_name_plural': 'Consumable Consumptions',
                'ordering': ('-assigned_date',),
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
