# Generated by Django 5.2 on 2026-05-23 08:48

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_accessory_accessoryassignment_consumable_and_more'),
        ('organization', '0004_alter_assetholder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_audited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Audited'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_assets', to=settings.AUTH_USER_MODEL, verbose_name='Last Audited By'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created_at', 'Created'), ('updated_at', 'Updated'), ('checked_out', 'Checked Out'), ('checked_in', 'Checked In'), ('audited', 'Audited')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustodyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_hash', models.CharField(max_length=64, unique=True)),
                ('signature_canvas', models.TextField(help_text='Base64 canvas stroke vector string representation')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eula_version', models.CharField(default='1.0', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_receipts', to='assets.asset')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_receipts', to='organization.assetholder')),
            ],
            options={
                'verbose_name': 'Custody Receipt',
                'verbose_name_plural': 'Custody Receipts',
                'ordering': ('-signed_at',),
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
