# Generated by Django 5.2 on 2026-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_asset_last_audited_asset_last_audited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Supplier'),
        ),
    ]
