# Generated by Django 5.2 on 2026-05-23 17:23

import core.models
import django.db.models.deletion
from django.db import migrations, models


def create_default_statuses_and_map_assets(apps, schema_editor):
    StatusLabel = apps.get_model('assets', 'StatusLabel')

    # Create default status labels
    available = StatusLabel.objects.create(
        name='Available',
        slug='available',
        type='deployable',
        color='28a745',
        description='Assets that are available to be deployed.'
    )
    in_use = StatusLabel.objects.create(
        name='In Use',
        slug='in-use',
        type='deployable',
        color='007bff',
        description='Assets that are currently checked out/assigned.'
    )
    pending_repair = StatusLabel.objects.create(
        name='Pending Repair',
        slug='pending-repair',
        type='pending',
        color='ffc107',
        description='Assets that are awaiting or undergoing maintenance/repair.'
    )
    retired = StatusLabel.objects.create(
        name='Retired',
        slug='retired',
        type='archived',
        color='dc3545',
        description='Assets that have been decommissioned or retired.'
    )

    # Use raw SQL to update the status column before Django alters its field type to ForeignKey
    schema_editor.execute(f"UPDATE assets_asset SET status = '{available.id}' WHERE status = 'available'")
    schema_editor.execute(f"UPDATE assets_asset SET status = '{in_use.id}' WHERE status = 'in_use'")
    schema_editor.execute(f"UPDATE assets_asset SET status = '{pending_repair.id}' WHERE status = 'pending_repair'")
    schema_editor.execute(f"UPDATE assets_asset SET status = '{retired.id}' WHERE status = 'retired'")
    
    # Also handle any empty or invalid legacy statuses
    schema_editor.execute(f"UPDATE assets_asset SET status = '{available.id}' WHERE status IS NULL OR status = '' OR status NOT IN ('available', 'in_use', 'pending_repair', 'retired')")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_asset_order_number_asset_purchase_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('deployable', 'Deployable'), ('pending', 'Pending'), ('undeployable', 'Undeployable'), ('archived', 'Archived')], default='deployable', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6)),
            ],
            options={
                'verbose_name': 'Status Label',
                'verbose_name_plural': 'Status Labels',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.RunPython(create_default_statuses_and_map_assets, elidable=True),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.statuslabel'),
        ),
    ]
