# Generated by Django 5.2 on 2026-05-23 17:33

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_statuslabel_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salvage Value'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='eol_months',
            field=models.PositiveIntegerField(blank=True, help_text='Lifespan in months before EOL replacement', null=True, verbose_name='EOL (Months)'),
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='Supplier/Vendor')),
                ('maintenance_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('repair', 'Repair'), ('calibration', 'Calibration'), ('software_support', 'Software Support'), ('hardware_support', 'Hardware Support')], default='repair', max_length=50, verbose_name='Maintenance Type')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maintenance Cost')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenances',
                'ordering': ['-start_date'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
