# Generated by Django 5.2 on 2026-05-23 21:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_asset_salvage_value_assettype_eol_months_and_more'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(help_text='Slug-like name (e.g. sim_card_number)', unique=True, verbose_name='Field Name')),
                ('label', models.CharField(max_length=100, verbose_name='Display Label')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select / Dropdown')], default='text', max_length=50, verbose_name='Field Type')),
                ('choices', models.TextField(blank=True, help_text="New-line separated list of choices (only for 'select' type)", null=True)),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'ordering': ['label'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Depreciation Name')),
                ('months', models.PositiveIntegerField(help_text='Useful lifespan in months for straight-line calculations', verbose_name='Lifespan (Months)')),
            ],
            options={
                'verbose_name': 'Depreciation',
                'verbose_name_plural': 'Depreciations',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kit Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Values'),
        ),
        migrations.CreateModel(
            name='CustomFieldset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fieldset Name')),
                ('fields', models.ManyToManyField(blank=True, related_name='fieldsets', to='assets.customfield', verbose_name='Custom Fields')),
            ],
            options={
                'verbose_name': 'Custom Fieldset',
                'verbose_name_plural': 'Custom Fieldsets',
                'ordering': ['name'],
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
        migrations.AddField(
            model_name='assettype',
            name='custom_fieldset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.customfieldset', verbose_name='Custom Fieldset'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='depreciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.depreciation', verbose_name='Depreciation'),
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity to checkout (only applies to Accessories)', verbose_name='Quantity')),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='assets.accessory', verbose_name='Accessory Catalog Item')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='assets.assettype', verbose_name='Asset Type / Model')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.kit', verbose_name='Kit')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='licenses.license', verbose_name='Software License')),
            ],
            options={
                'verbose_name': 'Kit Item',
                'verbose_name_plural': 'Kit Items',
            },
            bases=(models.Model, core.models.ChangeLoggingMixin),
        ),
    ]
