# Generated by Django 5.2 on 2026-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_customfield_depreciation_kit_asset_custom_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='support_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Support Phone'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='support_url',
            field=models.URLField(blank=True, null=True, verbose_name='Support URL'),
        ),
    ]
