# Generated by Django 5.2 on 2026-05-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_manufacturer_support_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='support_email',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='support_phone',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='support_url',
        ),
    ]
