# Generated by Django 5.2 on 2026-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_remove_manufacturer_support_email_and_more'),
        ('licenses', '0001_initial'),
        ('organization', '0005_contactrole_contact_contactassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created_at', 'Created'), ('updated_at', 'Updated'), ('checked_out', 'Checked Out'), ('checked_in', 'Checked In'), ('audited', 'Audited')], max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_audited',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Audited'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='accessoryassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_holder__isnull', True), ('assigned_location__isnull', False)), _connector='OR'), name='chk_accessory_assignment_single_target'),
        ),
        migrations.AddConstraint(
            model_name='consumableassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_holder__isnull', False), ('assigned_location__isnull', True)), models.Q(('assigned_holder__isnull', True), ('assigned_location__isnull', False)), _connector='OR'), name='chk_consumable_assignment_single_target'),
        ),
        migrations.AddConstraint(
            model_name='kititem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('asset_type__isnull', False), ('license__isnull', True)), models.Q(('accessory__isnull', False), ('asset_type__isnull', True), ('license__isnull', True)), models.Q(('accessory__isnull', True), ('asset_type__isnull', True), ('license__isnull', False)), _connector='OR'), name='chk_kit_item_single_target'),
        ),
    ]
