# Generated by Django 5.2 on 2026-05-24 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_activitylog_action_alter_asset_last_audited_and_more'),
        ('organization', '0005_contactrole_contact_contactassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='organization.tenant'),
        ),
    ]
