# Generated by Django 5.2 on 2026-05-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_accessory_tenant_asset_tenant_consumable_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrole',
            name='config_template',
        ),
    ]
