# Generated by Django 5.2 on 2026-05-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_remove_assetrole_config_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Manufacturer part number or SKU', max_length=100),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, help_text='Physical serial number of the part', max_length=100),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or part number', max_length=100),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='SKU or manufacturer part number', max_length=100),
        ),
    ]
