# Generated by Django 5.2 on 2026-05-27 09:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_supplier_strings_to_fk(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Supplier = apps.get_model('assets', 'Supplier')
    
    # Find all unique supplier strings
    supplier_names = Asset.objects.exclude(
        supplier__isnull=True
    ).exclude(
        supplier=''
    ).values_list('supplier', flat=True).distinct()
    
    name_to_supplier = {}
    for name in supplier_names:
        if name and name.strip():
            from django.utils.text import slugify
            slug = slugify(name)
            base_slug = slug
            counter = 1
            while Supplier.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            supplier = Supplier.objects.create(name=name, slug=slug)
            name_to_supplier[name] = supplier
    
    # Update assets that have a supplier string
    for name, supplier in name_to_supplier.items():
        Asset.objects.filter(supplier=name).update(supplier_new=supplier.pk)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_add_db_index_on_searchable_fields'),
        ('extras', '0004_dashboard_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_types/', verbose_name='Model Image'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('charger', 'Charger'), ('adaptor', 'Adapter/Dongle'), ('display', 'Display/Monitor'), ('cable', 'Cable'), ('other', 'Other')], default='other', max_length=50, verbose_name='Accessory Type'),
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.asset')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.assettype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Request',
                'verbose_name_plural': 'Asset Requests',
                'ordering': ['-request_date'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('color', models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email_on_checkout', models.BooleanField(default=False, help_text='Send email notification on asset checkout')),
                ('email_on_checkin', models.BooleanField(default=False, help_text='Send email notification on asset checkin')),
                ('require_acceptance', models.BooleanField(default=False, help_text='Require digital acceptance on checkout')),
                ('email_eula', models.BooleanField(default=False, help_text='Send EULA email on acceptance')),
                ('applies_to', models.JSONField(blank=True, default=list, help_text="Applies to: ['asset', 'accessory', 'license']")),
                ('tags', models.ManyToManyField(blank=True, related_name='categories', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='accessory',
            name='notification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_categories', to='assets.category', verbose_name='Notification Category'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='suppliers', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='accessory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accessories', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_assets', to='assets.supplier', verbose_name='Supplier FK'),
        ),
        migrations.RunPython(
            migrate_supplier_strings_to_fk,
            reverse_migration,
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='supplier_new',
            new_name='supplier',
        ),
    ]
