# Generated by Django 5.2 on 2026-05-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_phase2_feature_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='requestable',
            field=models.BooleanField(default=False, help_text='Allow users to request this asset'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='requestable',
            field=models.BooleanField(default=False, help_text='Allow users to request assets of this type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.supplier', verbose_name='Supplier'),
        ),
    ]
