# Generated by Django 5.2 on 2026-05-27 10:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_custody_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTagSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='ASSET-', max_length=20, unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('zero_padding', models.PositiveSmallIntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Asset Tag Sequence',
                'verbose_name_plural': 'Asset Tag Sequences',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='accessory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
