# Generated by Django 5.2 on 2026-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_soft_delete'),
        ('extras', '0004_dashboard_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='extras.tag'),
        ),
    ]
