# Generated by Django 5.2 on 2026-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_add_manufacturer_tags'),
        ('extras', '0004_dashboard_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_requests_tagged', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='kit',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='kits', to='extras.tag'),
        ),
        migrations.AddField(
            model_name='statuslabel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='status_labels_tagged', to='extras.tag'),
        ),
    ]
