# Generated by Django 5.2 on 2026-05-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_assetrequest_tags_kit_tags_statuslabel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('charger', 'Charger'), ('adaptor', 'Adapter/Dongle'), ('display', 'Display/Monitor'), ('cable', 'Cable'), ('other', 'Other')], db_index=True, default='other', max_length=50, verbose_name='Accessory Type'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created_at', 'Created'), ('updated_at', 'Updated'), ('checked_out', 'Checked Out'), ('checked_in', 'Checked In'), ('audited', 'Audited')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='requestable',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow users to request this asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiration',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('upgrade', 'Upgrade'), ('repair', 'Repair'), ('calibration', 'Calibration'), ('software_support', 'Software Support'), ('hardware_support', 'Hardware Support')], db_index=True, default='repair', max_length=50, verbose_name='Maintenance Type'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='cpu',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Processor (CPU)'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='model',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='requestable',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow users to request assets of this type'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='status',
            field=models.CharField(choices=[('installed', 'Installed'), ('in_stock', 'In Stock'), ('defective', 'Defective')], db_index=True, default='in_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='category',
            field=models.CharField(choices=[('ram', 'Memory (RAM)'), ('storage', 'Storage (SSD/HDD)'), ('gpu', 'Graphics Card (GPU)'), ('cpu', 'Processor (CPU)'), ('nic', 'Network Card (NIC)'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='category',
            field=models.CharField(choices=[('toner', 'Toner/Ink'), ('ink', 'Ink Cartridge'), ('batteries', 'Batteries'), ('thermal_paste', 'Thermal Paste'), ('paper', 'Printer Paper'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select / Dropdown')], db_index=True, default='text', max_length=50, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Display Label'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='install_date',
            field=models.DateField(blank=True, db_index=True, help_text='Estimated or known installation date', null=True),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='last_seen_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this software was last detected on the asset', null=True),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='type',
            field=models.CharField(choices=[('deployable', 'Deployable'), ('pending', 'Pending'), ('undeployable', 'Undeployable'), ('archived', 'Archived')], db_index=True, default='deployable', max_length=50),
        ),
        migrations.AlterModelTable(
            name='accessory',
            table='assets_accessory',
        ),
        migrations.AlterModelTable(
            name='accessoryassignment',
            table='assets_accessoryassignment',
        ),
        migrations.AlterModelTable(
            name='assetmaintenance',
            table='assets_assetmaintenance',
        ),
        migrations.AlterModelTable(
            name='componentinstance',
            table='assets_componentinstance',
        ),
        migrations.AlterModelTable(
            name='componenttype',
            table='assets_componenttype',
        ),
        migrations.AlterModelTable(
            name='consumable',
            table='assets_consumable',
        ),
        migrations.AlterModelTable(
            name='consumableassignment',
            table='assets_consumableassignment',
        ),
        migrations.AlterModelTable(
            name='custodyreceipt',
            table='assets_custodyreceipt',
        ),
        migrations.AlterModelTable(
            name='customfield',
            table='assets_customfield',
        ),
        migrations.AlterModelTable(
            name='customfieldset',
            table='assets_customfieldset',
        ),
        migrations.AlterModelTable(
            name='kit',
            table='assets_kit',
        ),
        migrations.AlterModelTable(
            name='kititem',
            table='assets_kititem',
        ),
    ]
