# Generated by Django 5.2 on 2026-05-29 12:09

import core.mixins
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0033_alter_accessory_category_alter_activitylog_action_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0004_dashboard_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_object_id', models.PositiveIntegerField()),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('expected_checkin_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='contenttypes.contenttype')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='asset_assignments', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-checked_out_at'],
                'indexes': [models.Index(fields=['assigned_to_content_type', 'assigned_to_object_id'], name='assets_asse_assigne_b44734_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset',), name='unique_active_assignment_per_asset')],
            },
            bases=(core.mixins.TaggableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
