# Generated by Django 5.2 on 2026-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_add_asset_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='applies_to',
            field=models.JSONField(blank=True, default=dict, help_text="Applies to: {'asset': True, 'accessory': True, 'component': True}"),
        ),
    ]
