# Generated by Django 5.2 on 2026-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0035_category_dict_and_components'),
        ('components', '0002_migrate_legacy_components'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentInstance',
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
    ]
