# Generated by Django 5.2 on 2026-05-29 14:25

import core.models
import django.db.models.deletion
from django.db import migrations, models


def _seed_category_objects(apps, schema_editor):
    Category = apps.get_model('assets', 'Category')

    categories = {
        'keyboard': ('Keyboard', 'accessory'),
        'mouse': ('Mouse', 'accessory'),
        'charger': ('Charger', 'accessory'),
        'adaptor': ('Adapter/Dongle', 'accessory'),
        'display': ('Display/Monitor', 'accessory'),
        'cable': ('Cable', 'accessory'),
        'toner': ('Toner/Ink', 'consumable'),
        'ink': ('Ink Cartridge', 'consumable'),
        'batteries': ('Batteries', 'consumable'),
        'thermal_paste': ('Thermal Paste', 'consumable'),
        'paper': ('Printer Paper', 'consumable'),
        'other': ('Other', 'both'),
    }

    for slug, (name, applies_type) in categories.items():
        category, created = Category.objects.get_or_create(slug=slug, defaults={'name': name})
        applies_to = dict(category.applies_to or {})
        if applies_type in ('accessory', 'both'):
            applies_to['accessory'] = True
        if applies_type in ('consumable', 'both'):
            applies_to['consumable'] = True
        category.applies_to = applies_to
        category.save()


def _migrate_accessory_category_data(apps, schema_editor):
    Category = apps.get_model('assets', 'Category')

    slug_map = {
        'keyboard': 'keyboard', 'mouse': 'mouse', 'charger': 'charger',
        'adaptor': 'adaptor', 'display': 'display', 'cable': 'cable', 'other': 'other',
    }

    cat_map = {}
    for old_val, slug in slug_map.items():
        try:
            cat_map[old_val] = Category.objects.get(slug=slug).pk
        except Category.DoesNotExist:
            cat_map[old_val] = None
    cat_map['other'] = Category.objects.get(slug='other').pk if 'other' not in [c.pk for c in Category.objects.all()] else Category.objects.get(slug='other').pk

    for old_val, cat_pk in cat_map.items():
        if cat_pk is None:
            continue
        schema_editor.execute(
            "UPDATE assets_accessory SET category_fk_id = %s WHERE category = %s",
            [cat_pk, old_val]
        )

    schema_editor.execute(
        "UPDATE assets_accessory SET category_fk_id = (SELECT id FROM assets_category WHERE slug = 'other' LIMIT 1) WHERE category_fk_id IS NULL"
    )


def _migrate_consumable_category_data(apps, schema_editor):
    Category = apps.get_model('assets', 'Category')

    slug_map = {
        'toner': 'toner', 'ink': 'ink', 'batteries': 'batteries',
        'thermal_paste': 'thermal_paste', 'paper': 'paper', 'other': 'other',
    }

    cat_map = {}
    for old_val, slug in slug_map.items():
        try:
            cat_map[old_val] = Category.objects.get(slug=slug).pk
        except Category.DoesNotExist:
            cat_map[old_val] = None

    for old_val, cat_pk in cat_map.items():
        if cat_pk is None:
            continue
        schema_editor.execute(
            "UPDATE assets_consumable SET category_fk_id = %s WHERE category = %s",
            [cat_pk, old_val]
        )

    schema_editor.execute(
        "UPDATE assets_consumable SET category_fk_id = (SELECT id FROM assets_category WHERE slug = 'other' LIMIT 1) WHERE category_fk_id IS NULL"
    )


def _backfill_stock(apps, schema_editor):
    Accessory = apps.get_model('assets', 'Accessory')
    AccessoryStock = apps.get_model('assets', 'AccessoryStock')
    Consumable = apps.get_model('assets', 'Consumable')
    ConsumableStock = apps.get_model('assets', 'ConsumableStock')
    Location = apps.get_model('organization', 'Location')

    default_location = Location.objects.first()
    if not default_location:
        return

    for accessory in Accessory.objects.all():
        if accessory.qty > 0:
            AccessoryStock.objects.create(
                accessory=accessory,
                location=default_location,
                qty=accessory.qty
            )

    for consumable in Consumable.objects.all():
        if consumable.qty > 0:
            ConsumableStock.objects.create(
                consumable=consumable,
                location=default_location,
                qty=consumable.qty
            )


def _reverse_stock(apps, schema_editor):
    Accessory = apps.get_model('assets', 'Accessory')
    AccessoryStock = apps.get_model('assets', 'AccessoryStock')
    Consumable = apps.get_model('assets', 'Consumable')
    ConsumableStock = apps.get_model('assets', 'ConsumableStock')

    for stock in AccessoryStock.objects.all():
        stock.accessory.qty = stock.qty
        stock.accessory.save()

    for stock in ConsumableStock.objects.all():
        stock.consumable.qty = stock.qty
        stock.consumable.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0036_drop_legacy_component_tables'),
        ('organization', '0006_alter_location_name_alter_location_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='assets.accessory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_stocks', to='organization.location')),
            ],
            options={
                'verbose_name': 'Accessory Stock',
                'verbose_name_plural': 'Accessory Stocks',
                'db_table': 'assets_accessorystock',
                'ordering': ('accessory', 'location'),
                'unique_together': {('accessory', 'location')},
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='assets.consumable')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_stocks', to='organization.location')),
            ],
            options={
                'verbose_name': 'Consumable Stock',
                'verbose_name_plural': 'Consumable Stocks',
                'db_table': 'assets_consumablestock',
                'ordering': ('consumable', 'location'),
                'unique_together': {('consumable', 'location')},
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.RunPython(code=_seed_category_objects, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accessory',
            name='notification_category',
        ),
        migrations.AddField(
            model_name='accessory',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories_temp', to='assets.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables_temp', to='assets.category', verbose_name='Category'),
        ),
        migrations.RunPython(code=_migrate_accessory_category_data, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=_migrate_consumable_category_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accessory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='category',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='consumable',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'applies_to__accessory': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'applies_to__consumable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='assets.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_checkouts', to='organization.location', verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='consumableassignment',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_consumptions_out', to='organization.location', verbose_name='From Location'),
        ),
        migrations.RunPython(code=_backfill_stock, reverse_code=_reverse_stock),
        migrations.RemoveField(
            model_name='accessory',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='qty',
        ),
    ]
