# Generated by Django 5.2 on 2026-06-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_tenantinvitation_tenantmembership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantinvitation',
            options={'verbose_name': 'Tenant Invitation', 'verbose_name_plural': 'Tenant Invitations'},
        ),
    ]
