# Generated by Django 5.2 on 2026-06-03 10:48

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_delete_assetholderassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Role',
                'verbose_name_plural': 'Tenant Roles',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organization.tenantrole'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.tenantrole'),
        ),
    ]
