# Generated by Django 5.2.15 on 2026-06-04 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_tenantrole_alter_tenantinvitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetholder',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holders', to='organization.site'),
        ),
        migrations.AddField(
            model_name='assetholder',
            name='tenant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holders', to='organization.tenantgroup'),
        ),
    ]
