# Generated by Django 5.2 on 2026-06-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_assetholder_site_assetholder_tenant_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetholder',
            name='site',
        ),
        migrations.RemoveField(
            model_name='assetholder',
            name='tenant_group',
        ),
    ]
