# Generated by Django 5.2.15 on 2026-06-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_assetholder_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetholder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_holders', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.tenant'),
        ),
    ]
