# Generated by Django 5.2.15 on 2026-06-05 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_assetholder_tenant_alter_location_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tenantrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='organization_tenantmembership_unique_user_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='organization_tenantrole_unique_tenant_name'),
        ),
    ]
