# Generated by Django 5.2.15 on 2026-06-07 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_alter_tag_deleted_at'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetholder',
            name='organization_assetholder_unique_upn',
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='upn',
            field=models.CharField(max_length=255, verbose_name='User Principal Name'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holder_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.site'),
        ),
        migrations.AlterField(
            model_name='region',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='tenantrole',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='assetholder',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='assetholder',
            constraint=models.UniqueConstraint(fields=('tenant', 'upn'), name='unique_tenant_upn'),
        ),
    ]
