# Generated by Django 5.2.15 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetholder',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
        migrations.AddField(
            model_name='location',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
    ]
