# Generated by Django 5.2.15 on 2026-06-12 20:50

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_tenant_currency_default_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default=organization.models._default_currency, help_text='ISO 4217 currency code used for value display (display only, no conversion).', max_length=3, verbose_name='Display currency'),
        ),
    ]
