# Generated by Django 5.2.15 on 2026-06-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('organization', '0016_currency_callable_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetholder',
            name='unique_tenant_user_profile',
        ),
        migrations.RemoveConstraint(
            model_name='assetholder',
            name='unique_tenant_upn',
        ),
        migrations.RemoveConstraint(
            model_name='tenantrole',
            name='organization_tenantrole_unique_tenant_name',
        ),
        migrations.AddConstraint(
            model_name='assetholder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'user'), name='unique_tenant_user_profile'),
        ),
        migrations.AddConstraint(
            model_name='assetholder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'upn'), name='unique_tenant_upn'),
        ),
        migrations.AddConstraint(
            model_name='tenantrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='organization_tenantrole_unique_tenant_name'),
        ),
    ]
