# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetholder',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organization_assetholders', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_holders', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='assetholder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holder_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organization_contacts', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contactassignment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contactassignment',
            name='priority',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('inactive', 'Inactive')], max_length=50, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='contactassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.contactrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactrole',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(db_index=True, help_text='Short identifier for this cost center (e.g. "CC-100").', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.costcenter', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='facility',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.location', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='location',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locations', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.region', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='regions', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='site',
            name='facility',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='site',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organization.sitegroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='physical_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Physical Address'),
        ),
        migrations.AlterField(
            model_name='site',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organization.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='site',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sites', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='site',
            name='time_zone',
            field=models.CharField(blank=True, max_length=63, verbose_name='Time Zone'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.sitegroup', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sitegroups', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='organization.tenantgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.tenantgroup', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tenantgroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tenantgroups', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted At'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organization.tenantrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organization.tenantrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tenantrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tenantrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tenantrole',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='tenantrole',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
