# Generated by Django 5.2.15 on 2026-06-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_assetholder_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
    ]
