# Generated by Django 5.2.15 on 2026-06-22 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_tenantmembership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. Leave blank for a global/shared contact (e.g. a manufacturer or service desk) visible to all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.tenant', verbose_name='Tenant'),
        ),
    ]
