# Generated by Django 5.2.15 on 2026-06-23 10:47

import core.mixins
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_contact_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantmembership',
            name='role',
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='direct_permissions',
            field=models.JSONField(blank=True, default=list, help_text='Permission codenames granted directly to this membership, independent of any role. Additive with role permissions.', verbose_name='Direct permissions'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='organization.tenantrole', verbose_name='Roles'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('members', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_groups', to='organization.tenantrole', verbose_name='Roles')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='organization.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='organization_usergroup_unique_tenant_name_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='organization_usergroup_unique_slug_active')],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
