# Generated by Django 5.2.15 on 2026-06-23 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_remove_tenantmembership_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='organization_usergroup_unique_tenant_name_active',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text="Roles granted to members. Roles may span multiple tenants; a member gets each role's permissions in that role's tenant.", related_name='user_groups', to='organization.tenantrole', verbose_name='Roles'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='organization_usergroup_unique_name_active'),
        ),
    ]
