# Generated by Django 5.2.15 on 2026-06-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_remove_usergroup_organization_usergroup_unique_tenant_name_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['name'], 'permissions': [('manage_usergroups', 'Can manage user groups (global)')], 'verbose_name': 'User Group', 'verbose_name_plural': 'User Groups'},
        ),
    ]
