# Generated by Django 5.2.15 on 2026-06-24 18:12
#
# UserGroup is RELOCATED to the users app (identity layer), not destroyed. This migration
# removes it from organization's migration STATE only — the physical table is renamed (not
# dropped) by users.0007_usergroup so rows, M2M links, the content type and the
# manage_usergroups permission (with any user_permissions grants) all survive the move.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_alter_usergroup_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='UserGroup'),
            ],
            database_operations=[],
        ),
    ]
