# Generated by Django 5.2.15 on 2026-06-24 18:23

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_delete_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Settings')),
                ('internal_tenant', models.ForeignKey(blank=True, help_text="The provider's own IT inventory tenant ('home base' for provider staff).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_internal', to='organization.tenant', verbose_name='Internal tenant')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['name'],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='tenant',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='organization.provider', verbose_name='Provider'),
        ),
        migrations.CreateModel(
            name='ProviderRoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='Permissions')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-instantiate this template as a TenantRole when a new tenant is created under the provider.', verbose_name='Default for new tenants')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='organization.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Provider Role Template',
                'verbose_name_plural': 'Provider Role Templates',
                'ordering': ['provider', 'name'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProviderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('can_manage_tenants', models.BooleanField(default=False, verbose_name='Can manage tenants')),
                ('can_manage_provider_users', models.BooleanField(default=False, verbose_name='Can manage provider users')),
                ('can_manage_groups', models.BooleanField(default=False, verbose_name='Can manage groups')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.provider', verbose_name='Provider')),
                ('tenant_role_template', models.ForeignKey(blank=True, help_text="Permission set granted in tenants within the holder's scope.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_roles', to='organization.providerroletemplate', verbose_name='Tenant role template')),
            ],
            options={
                'verbose_name': 'Provider Role',
                'verbose_name_plural': 'Provider Roles',
                'ordering': ['provider', 'name'],
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='organization_provider_unique_name_active'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='organization_provider_unique_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='providerroletemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'name'), name='organization_providerroletemplate_unique_provider_name_active'),
        ),
        migrations.AddConstraint(
            model_name='providerrole',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'name'), name='organization_providerrole_unique_provider_name_active'),
        ),
    ]
