# Generated by Django 5.2.15 on 2026-06-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_drop_legacy_role_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='organization_membership_scope_consistency',
        ),
        migrations.AlterField(
            model_name='membership',
            name='person_type',
            field=models.CharField(choices=[('staff', 'Provider staff'), ('member', 'Member')], db_index=True, default='member', max_length=20, verbose_name='Person type'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('person_type', 'staff'), ('provider__isnull', False), ('tenant__isnull', True)), models.Q(('person_type', 'member'), ('tenant__isnull', False), ('provider__isnull', True)), _connector='OR'), name='organization_membership_scope_consistency'),
        ),
    ]
