# Generated by Django 5.2.15 on 2026-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_remove_membership_organization_membership_scope_consistency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Provider-scoped roles only. Automatically clone this role into new tenants created under this provider.', verbose_name='Clone to new tenants'),
        ),
    ]
