# Generated by Django 5.2.15 on 2026-06-28 16:11
#
# Greenfield / no production data. Drops the redundant ``Membership.person_type`` enum —
# the tenant/provider FK pair is the sole discriminator (provider ⇒ staff, tenant ⇒
# member), and ``person_type`` was always derivable from it (and DB-enforced to match), so
# no data back-fill is needed. The XOR is now expressed FK-only in the swapped constraint.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_alter_role_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='organization_membership_scope_consistency',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person_type',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tenant__isnull', False), ('provider__isnull', True)), models.Q(('tenant__isnull', True), ('provider__isnull', False)), _connector='OR'), name='organization_membership_exactly_one_container'),
        ),
    ]
