# Generated by Django 5.2.15 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_remove_membership_organization_membership_scope_consistency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tenant_scope',
            field=models.CharField(blank=True, choices=[('explicit', 'Specific tenants'), ('tenant_group', 'A tenant group + its descendants'), ('all', "All of the provider's tenants")], help_text='Provider staff only. How this technician reaches customer tenants.', max_length=20, null=True, verbose_name='Tenant scope'),
        ),
    ]
