# Generated by Django 5.2.15 on 2026-07-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_alter_membership_tenant_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('tenant', 'Tenant role'), ('provider', 'Provider role')], db_index=True, default='tenant', max_length=20, verbose_name='Scope'),
        ),
    ]
