# Generated by Django 5.2.15 on 2026-07-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_alter_role_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantInvitation',
        ),
    ]
