# GREENFIELD-ONLY: part of the 2026-07-10 RBAC structural collapse (Provider -> Tenant tree, per-grant RoleAssignment). Applies cleanly only on a fresh database — pre-collapse rows are intentionally not migrated (project convention: unreleased app, greenfield resets).
# Generated by Django 5.2.15 on 2026-07-10 19:43

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_delete_tenantinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach', models.CharField(choices=[('own', 'This tenant'), ('managed', 'Managed tenants')], db_index=True, default='own', max_length=10, verbose_name='Reach')),
                ('managed_scope', models.CharField(blank=True, choices=[('explicit', 'Specific tenants'), ('tenant_group', 'A tenant group + its descendants'), ('all', 'All managed tenants')], help_text='Managed reach only. Which managed tenants this grant covers.', max_length=20, null=True, verbose_name='Managed scope')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role assignment',
                'verbose_name_plural': 'Role assignments',
                'ordering': ['membership', 'role'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='organization_membership_unique_user_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='organization_membership_unique_user_provider',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='organization_membership_exactly_one_container',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='organization_role_unique_tenant_name',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='organization_role_unique_provider_name',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='organization_role_scope_consistency',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='internal_tenant',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='role',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='assigned_tenants',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='direct_permissions',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='scope_group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='tenant_scope',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='role',
            name='scope',
        ),
        migrations.AddField(
            model_name='role',
            name='shared_with_managed',
            field=models.BooleanField(default=False, help_text='Only meaningful when the owning tenant manages others: managed tenants may assign this role to their own members; only the owning tenant can edit it.', verbose_name='Share with managed tenants'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_provider',
            field=models.BooleanField(db_index=True, default=False, help_text='Superuser-controlled. When set, this tenant can manage other tenants and its members can be granted reach into them.', verbose_name='Manages other tenants (MSP mode)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='The managing (provider) tenant. Empty for standalone/root tenants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_tenants', to='organization.tenant', verbose_name='Managed by'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text="List of permission codenames ('app_label.codename').", verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='organization_membership_unique_user_tenant'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='organization_role_unique_tenant_name'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_tenants',
            field=models.ManyToManyField(blank=True, help_text="Used when managed_scope='explicit'.", related_name='reach_assignments', to='organization.tenant', verbose_name='Assigned tenants'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Granted by'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.membership', verbose_name='Membership'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='scope_group',
            field=models.ForeignKey(blank=True, help_text="Used when managed_scope='tenant_group'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_scopes', to='organization.tenantgroup', verbose_name='Scope group'),
        ),
    ]
