# GREENFIELD-ONLY: part of the 2026-07-10 RBAC structural collapse (Provider -> Tenant tree, per-grant RoleAssignment). Applies cleanly only on a fresh database — pre-collapse rows are intentionally not migrated (project convention: unreleased app, greenfield resets).
# Generated by Django 5.2.15 on 2026-07-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_roleassignment_remove_provider_internal_tenant_and_more'),
        ('users', '0010_remove_usergroup_users_usergroup_unique_provider_name_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'role', 'reach'), name='organization_roleassignment_unique_grant'),
        ),
    ]
