# Generated by Django 5.2.15 on 2026-07-11 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_delete_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='changelog_retention_days',
            field=models.IntegerField(blank=True, help_text="Overrides ITAMBOX_CHANGELOG_RETENTION_DAYS for this tenant's ObjectChange rows only. Blank uses the global setting. 0 = unlimited (legal hold -- this tenant's changelog is never pruned by prune_changelog).", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Changelog retention override (days)'),
        ),
    ]
