# Generated by Django 5.2.15 on 2026-07-12 15:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0036_tenant_changelog_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantResourceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.PositiveBigIntegerField(verbose_name='Resource ID')),
                ('access_level', models.CharField(choices=[('view', 'View'), ('use', 'View + allocate/consume')], db_index=True, default='view', max_length=10, verbose_name='Access level')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_resource_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted by')),
                ('grantee_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_received', to='organization.tenant', verbose_name='Grantee tenant')),
                ('grantee_tenant_group', models.ForeignKey(blank=True, help_text='Grants to a group include its descendant groups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_received', to='organization.tenantgroup', verbose_name='Grantee tenant group')),
                ('resource_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'inventory'), ('model__in', ('componentstock', 'accessorystock', 'consumablestock'))), on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='Resource type')),
                ('tenant', models.ForeignKey(help_text='The tenant whose resource is being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_given', to='organization.tenant', verbose_name='Owning tenant')),
            ],
            options={
                'verbose_name': 'Tenant resource grant',
                'verbose_name_plural': 'Tenant resource grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='org_trg_resource_idx'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['resource_type', 'resource_id'], name='org_trg_active_resource_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('grantee_tenant__isnull', False), ('grantee_tenant_group__isnull', True)), models.Q(('grantee_tenant__isnull', True), ('grantee_tenant_group__isnull', False)), _connector='OR'), name='organization_trg_exactly_one_grantee'), models.CheckConstraint(condition=models.Q(('grantee_tenant__isnull', True), models.Q(('grantee_tenant', models.F('tenant')), _negated=True), _connector='OR'), name='organization_trg_owner_not_grantee'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('grantee_tenant__isnull', False)), fields=('resource_type', 'resource_id', 'grantee_tenant'), name='organization_trg_unique_active_tenant_grant'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('grantee_tenant_group__isnull', False)), fields=('resource_type', 'resource_id', 'grantee_tenant_group'), name='organization_trg_unique_active_group_grant')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
