# Generated by Django 5.2.15 on 2026-07-13 18:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_tenantresourcegrant'),
        ('users', '0010_remove_usergroup_users_usergroup_unique_provider_name_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Valid until')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted by')),
                ('legacy_assignment', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_grant', to='organization.roleassignment', verbose_name='Legacy assignment')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='organization.membership', verbose_name='Membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='organization.role', verbose_name='Role')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='users.usergroup', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'Role grant',
                'verbose_name_plural': 'Role grants',
                'ordering': ['role', 'membership', 'user_group'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RoleGrantScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('own', 'Principal tenant'), ('tenant', 'Specific managed tenant'), ('tenant_group', 'Managed tenant group + descendants'), ('all_managed', 'All managed tenants')], db_index=True, max_length=20, verbose_name='Scope type')),
                ('role_grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='organization.rolegrant', verbose_name='Role grant')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grant_scopes', to='organization.tenant', verbose_name='Tenant')),
                ('tenant_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grant_scopes', to='organization.tenantgroup', verbose_name='Tenant group')),
            ],
            options={
                'verbose_name': 'Role grant scope',
                'verbose_name_plural': 'Role grant scopes',
                'ordering': ['role_grant', 'scope_type', 'tenant', 'tenant_group'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='rolegrant',
            index=models.Index(fields=['membership', 'role'], name='org_rolegrant_member_role_idx'),
        ),
        migrations.AddIndex(
            model_name='rolegrant',
            index=models.Index(fields=['user_group', 'role'], name='org_rolegrant_group_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('membership__isnull', False), ('user_group__isnull', True)), models.Q(('membership__isnull', True), ('user_group__isnull', False)), _connector='OR'), name='organization_rolegrant_exactly_one_principal'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user_group__isnull', False)), fields=('user_group', 'role'), name='organization_rolegrant_unique_group_role'),
        ),
        migrations.AddConstraint(
            model_name='rolegrantscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type__in', ['own', 'all_managed']), ('tenant__isnull', True), ('tenant_group__isnull', True)), models.Q(('scope_type', 'tenant'), ('tenant__isnull', False), ('tenant_group__isnull', True)), models.Q(('scope_type', 'tenant_group'), ('tenant__isnull', True), ('tenant_group__isnull', False)), _connector='OR'), name='organization_rolegrantscope_shape'),
        ),
        migrations.AddConstraint(
            model_name='rolegrantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type__in', ['own', 'all_managed'])), fields=('role_grant', 'scope_type'), name='organization_rolegrantscope_unique_singleton'),
        ),
        migrations.AddConstraint(
            model_name='rolegrantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'tenant')), fields=('role_grant', 'tenant'), name='organization_rolegrantscope_unique_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rolegrantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'tenant_group')), fields=('role_grant', 'tenant_group'), name='organization_rolegrantscope_unique_group'),
        ),
    ]
