# Generated by Django 5.2.15 on 2026-07-13 18:10

from django.db import migrations


def backfill_phase5_rbac(apps, schema_editor):
    GroupMembership = apps.get_model('users', 'GroupMembership')
    Membership = apps.get_model('organization', 'Membership')
    Role = apps.get_model('organization', 'Role')
    RoleAssignment = apps.get_model('organization', 'RoleAssignment')
    RoleGrant = apps.get_model('organization', 'RoleGrant')
    RoleGrantScope = apps.get_model('organization', 'RoleGrantScope')
    UserGroup = apps.get_model('users', 'UserGroup')

    # RoleAssignment is fully derivable, including empty explicit managed scope.
    for assignment in RoleAssignment.objects.all().iterator():
        grant = RoleGrant.objects.create(
            membership_id=assignment.membership_id,
            role_id=assignment.role_id,
            granted_by_id=assignment.granted_by_id,
            legacy_assignment_id=assignment.pk,
        )
        RoleGrant.objects.filter(pk=grant.pk).update(granted_at=assignment.granted_at)
        if assignment.reach == 'own':
            RoleGrantScope.objects.create(role_grant_id=grant.pk, scope_type='own')
        elif (assignment.managed_scope or 'explicit') == 'all':
            RoleGrantScope.objects.create(
                role_grant_id=grant.pk,
                scope_type='all_managed',
            )
        elif (assignment.managed_scope or 'explicit') == 'tenant_group':
            if assignment.scope_group_id is not None:
                RoleGrantScope.objects.create(
                    role_grant_id=grant.pk,
                    scope_type='tenant_group',
                    tenant_group_id=assignment.scope_group_id,
                )
        else:
            RoleGrantScope.objects.bulk_create([
                RoleGrantScope(
                    role_grant_id=grant.pk,
                    scope_type='tenant',
                    tenant_id=tenant_id,
                )
                for tenant_id in assignment.assigned_tenants.values_list('pk', flat=True)
            ])

    # A legacy group-role edge is derivable only when both are owned by the
    # same tenant. Cross-owner/global groups are deliberately not converted:
    # the destructive cutover must not preserve invalid ownership by inventing
    # access in the canonical model.
    for group in UserGroup.objects.exclude(tenant_id=None).iterator():
        for role in Role.objects.filter(user_groups=group).iterator():
            if role.tenant_id != group.tenant_id:
                continue
            grant, _ = RoleGrant.objects.get_or_create(
                user_group_id=group.pk,
                role_id=role.pk,
            )
            RoleGrantScope.objects.get_or_create(
                role_grant_id=grant.pk,
                scope_type='own',
            )

        for user_id in group.members.values_list('pk', flat=True).iterator():
            membership = Membership.objects.filter(
                tenant_id=group.tenant_id,
                user_id=user_id,
            ).first()
            if membership is None:
                continue
            GroupMembership.objects.get_or_create(
                user_group_id=group.pk,
                membership_id=membership.pk,
                defaults={'source': 'manual'},
            )


def reverse_backfill_phase5_rbac(apps, schema_editor):
    apps.get_model('organization', 'RoleGrantScope').objects.all().delete()
    apps.get_model('organization', 'RoleGrant').objects.all().delete()
    apps.get_model('users', 'GroupMembership').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_rolegrant_rolegrantscope_and_more'),
        ('users', '0011_groupmembership'),
    ]

    operations = [
        migrations.RunPython(
            backfill_phase5_rbac,
            reverse_code=reverse_backfill_phase5_rbac,
        ),
    ]
