# Generated by Django 5.2.15 on 2026-07-13 19:38

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


PERMISSION_RENAMES = {
    f'organization.{action}_roleassignment': f'organization.{action}_rolegrant'
    for action in ('add', 'change', 'delete', 'view')
}


def _is_privileged(role):
    if role.name.lower() in {'admin', 'manager'}:
        return True
    return any(
        not isinstance(permission, str)
        or not permission.rsplit('.', 1)[-1].startswith('view_')
        for permission in role.permissions or []
    )


def prepare_canonical_rbac(apps, schema_editor):
    Role = apps.get_model('organization', 'Role')
    RoleGrant = apps.get_model('organization', 'RoleGrant')

    for role in Role.objects.all().iterator():
        rewritten = []
        for permission in role.permissions or []:
            if isinstance(permission, str):
                permission = PERMISSION_RENAMES.get(permission, permission)
            if permission not in rewritten:
                rewritten.append(permission)
        if rewritten != (role.permissions or []):
            Role.objects.filter(pk=role.pk).update(permissions=rewritten)

        if not _is_privileged(role):
            continue
        grants = RoleGrant.objects.filter(role_id=role.pk, membership_id__isnull=False)
        grants.filter(reason='').update(reason='Migrated during RBAC consolidation')
        grants.filter(valid_until__isnull=True).update(
            valid_until=timezone.now() + timedelta(days=365),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_backfill_phase5_rbac'),
        ('users', '0012_alter_usergroup_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolegrant',
            name='legacy_assignment',
        ),
        migrations.DeleteModel(
            name='RoleAssignment',
        ),
        migrations.RunPython(prepare_canonical_rbac, migrations.RunPython.noop),
    ]
