# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('organization', '0020_tenantmembership_is_active'),
        ('organization', '0021_contact_tenant'),
        ('organization', '0022_remove_tenantmembership_role_and_more'),
        ('organization', '0023_remove_usergroup_organization_usergroup_unique_tenant_name_active_and_more'),
        ('organization', '0024_alter_usergroup_options'),
        ('organization', '0025_delete_usergroup'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_39_extras_relations'),
        ('organization', '0100_issue88_shard_35_organization_history_3'),
    ]

    operations = [

    ]
