# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0035_delete_provider_and_more'),
        ('organization', '0036_tenant_changelog_retention_days'),
        ('organization', '0037_tenantresourcegrant'),
        ('organization', '0038_rolegrant_rolegrantscope_and_more'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_54_users_history_3'),
        ('organization', '0100_issue88_shard_53_organization_history_6'),
    ]

    operations = [

    ]
