# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0017_remove_assetholder_unique_tenant_user_profile_and_more'),
        ('organization', '0018_costcenter'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_34_extras_history_8'),
        ('organization', '0100_issue88_shard_32_organization_history_2'),
    ]

    operations = [

    ]
