# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.core.validators
import organization.models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0040_remove_rolegrant_legacy_assignment_and_more'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_60_users_history_5'),
        ('organization', '0100_issue88_shard_59_organization_history_8'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
                    model_name='assetholder',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_holder_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='contact',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='organization_contacts', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='contactassignment',
                    name='contact',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organization.contact', verbose_name='Contact'),
                ),
        migrations.AddField(
                    model_name='contactassignment',
                    name='content_type',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
                ),
        migrations.AddConstraint(
                    model_name='contactrole',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_contactrole_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='contactrole',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_contactrole_slug_active'),
                ),
        migrations.AddField(
                    model_name='contactassignment',
                    name='role',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.contactrole', verbose_name='Role'),
                ),
        migrations.AddField(
                    model_name='costcenter',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.costcenter', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='location',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.location', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='location',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='locations', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='membership',
                    name='user',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
                ),
        migrations.AddField(
                    model_name='region',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.region', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='region',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='regions', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='rolegrant',
                    name='granted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted by'),
                ),
        migrations.AddField(
                    model_name='rolegrant',
                    name='membership',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='organization.membership', verbose_name='Membership'),
                ),
        migrations.AddField(
                    model_name='rolegrant',
                    name='role',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='organization.role', verbose_name='Role'),
                ),
        migrations.AddField(
                    model_name='rolegrant',
                    name='user_group',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='users.usergroup', verbose_name='User group'),
                ),
        migrations.AddField(
                    model_name='rolegrantscope',
                    name='role_grant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='organization.rolegrant', verbose_name='Role grant'),
                ),
        migrations.AddField(
                    model_name='site',
                    name='region',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organization.region', verbose_name='Region'),
                ),
        migrations.AddField(
                    model_name='site',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='sites', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='location',
                    name='site',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.site', verbose_name='Site'),
                ),
        migrations.AddField(
                    model_name='sitegroup',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.sitegroup', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='sitegroup',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='sitegroups', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='site',
                    name='group',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='organization.sitegroup', verbose_name='Group'),
                ),
        migrations.AddField(
                    model_name='tenant',
                    name='default_depreciation',
                    field=models.ForeignKey(blank=True, help_text='Fallback policy applied to all assets that have no type-level schedule and no per-asset override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_defaulting', to='assets.depreciation', verbose_name='Default depreciation policy'),
                ),
        migrations.AddField(
                    model_name='tenant',
                    name='managed_by',
                    field=models.ForeignKey(blank=True, help_text='The managing (provider) tenant. Empty for standalone/root tenants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_tenants', to='organization.tenant', verbose_name='Managed by'),
                ),
        migrations.AddField(
                    model_name='tenant',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='tenants', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='site',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='rolegrantscope',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grant_scopes', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='role',
                    name='tenant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='membership',
                    name='tenant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='location',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='costcenter',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='contact',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Owning tenant. Leave blank for a global/shared contact (e.g. a manufacturer or service desk) visible to all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='assetholder',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_holders', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='tenantgroup',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.tenantgroup', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='tenantgroup',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='tenantgroups', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='tenant',
                    name='group',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='organization.tenantgroup', verbose_name='Group'),
                ),
        migrations.AddField(
                    model_name='rolegrantscope',
                    name='tenant_group',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_grant_scopes', to='organization.tenantgroup', verbose_name='Tenant group'),
                ),
        migrations.AddField(
                    model_name='tenantresourcegrant',
                    name='granted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_resource_grants', to=settings.AUTH_USER_MODEL, verbose_name='Granted by'),
                ),
        migrations.AddField(
                    model_name='tenantresourcegrant',
                    name='grantee_tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_received', to='organization.tenant', verbose_name='Grantee tenant'),
                ),
        migrations.AddField(
                    model_name='tenantresourcegrant',
                    name='grantee_tenant_group',
                    field=models.ForeignKey(blank=True, help_text='Grants to a group include its descendant groups.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_received', to='organization.tenantgroup', verbose_name='Grantee tenant group'),
                ),
        migrations.AddField(
                    model_name='tenantresourcegrant',
                    name='resource_type',
                    field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'inventory'), ('model__in', ('componentstock', 'accessorystock', 'consumablestock'))), on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='Resource type'),
                ),
        migrations.AddField(
                    model_name='tenantresourcegrant',
                    name='tenant',
                    field=models.ForeignKey(help_text='The tenant whose resource is being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_grants_given', to='organization.tenant', verbose_name='Owning tenant'),
                ),
        migrations.AddConstraint(
                    model_name='contactassignment',
                    constraint=models.UniqueConstraint(fields=('contact', 'role', 'content_type', 'object_id'), name='organization_contactassignment_unique'),
                ),
        migrations.AddConstraint(
                    model_name='region',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_region_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='region',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_region_slug_active'),
                ),
        migrations.AddIndex(
                    model_name='rolegrant',
                    index=models.Index(fields=['membership', 'role'], name='org_rolegrant_member_role_idx'),
                ),
        migrations.AddIndex(
                    model_name='rolegrant',
                    index=models.Index(fields=['user_group', 'role'], name='org_rolegrant_group_role_idx'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrant',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('membership__isnull', False), ('user_group__isnull', True)), models.Q(('membership__isnull', True), ('user_group__isnull', False)), _connector='OR'), name='organization_rolegrant_exactly_one_principal'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrant',
                    constraint=models.UniqueConstraint(condition=models.Q(('user_group__isnull', False)), fields=('user_group', 'role'), name='organization_rolegrant_unique_group_role'),
                ),
        migrations.AddConstraint(
                    model_name='sitegroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_sitegroup_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='sitegroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_sitegroup_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='site',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_site_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='site',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_site_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='role',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='organization_role_unique_tenant_name'),
                ),
        migrations.AddConstraint(
                    model_name='membership',
                    constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='organization_membership_unique_user_tenant'),
                ),
        migrations.AddConstraint(
                    model_name='location',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_location_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='costcenter',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='organization_costcenter_unique_tenant_code_active'),
                ),
        migrations.AddConstraint(
                    model_name='costcenter',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='organization_costcenter_unique_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='assetholder',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'user'), name='unique_tenant_user_profile'),
                ),
        migrations.AddConstraint(
                    model_name='assetholder',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'upn'), name='unique_tenant_upn'),
                ),
        migrations.AddConstraint(
                    model_name='tenantgroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_tenantgroup_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='tenantgroup',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_tenantgroup_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='tenant',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_tenant_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='tenant',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_tenant_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrantscope',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type__in', ['own', 'all_managed']), ('tenant__isnull', True), ('tenant_group__isnull', True)), models.Q(('scope_type', 'tenant'), ('tenant__isnull', False), ('tenant_group__isnull', True)), models.Q(('scope_type', 'tenant_group'), ('tenant__isnull', True), ('tenant_group__isnull', False)), _connector='OR'), name='organization_rolegrantscope_shape'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrantscope',
                    constraint=models.UniqueConstraint(condition=models.Q(('scope_type__in', ['own', 'all_managed'])), fields=('role_grant', 'scope_type'), name='organization_rolegrantscope_unique_singleton'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrantscope',
                    constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'tenant')), fields=('role_grant', 'tenant'), name='organization_rolegrantscope_unique_tenant'),
                ),
        migrations.AddConstraint(
                    model_name='rolegrantscope',
                    constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'tenant_group')), fields=('role_grant', 'tenant_group'), name='organization_rolegrantscope_unique_group'),
                ),
        migrations.AddIndex(
                    model_name='tenantresourcegrant',
                    index=models.Index(fields=['resource_type', 'resource_id'], name='org_trg_resource_idx'),
                ),
        migrations.AddIndex(
                    model_name='tenantresourcegrant',
                    index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['resource_type', 'resource_id'], name='org_trg_active_resource_idx'),
                ),
        migrations.AddConstraint(
                    model_name='tenantresourcegrant',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('grantee_tenant__isnull', False), ('grantee_tenant_group__isnull', True)), models.Q(('grantee_tenant__isnull', True), ('grantee_tenant_group__isnull', False)), _connector='OR'), name='organization_trg_exactly_one_grantee'),
                ),
        migrations.AddConstraint(
                    model_name='tenantresourcegrant',
                    constraint=models.CheckConstraint(condition=models.Q(('grantee_tenant__isnull', True), models.Q(('grantee_tenant', models.F('tenant')), _negated=True), _connector='OR'), name='organization_trg_owner_not_grantee'),
                ),
        migrations.AddConstraint(
                    model_name='tenantresourcegrant',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('grantee_tenant__isnull', False)), fields=('resource_type', 'resource_id', 'grantee_tenant'), name='organization_trg_unique_active_tenant_grant'),
                ),
        migrations.AddConstraint(
                    model_name='tenantresourcegrant',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('grantee_tenant_group__isnull', False)), fields=('resource_type', 'resource_id', 'grantee_tenant_group'), name='organization_trg_unique_active_group_grant'),
                ),
    ]
