# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0027_drop_legacy_role_models'),
        ('organization', '0028_remove_membership_organization_membership_scope_consistency_and_more'),
        ('organization', '0029_alter_role_is_default'),
        ('organization', '0030_remove_membership_organization_membership_scope_consistency_and_more'),
        ('organization', '0031_alter_membership_tenant_scope'),
        ('organization', '0032_alter_role_scope'),
        ('organization', '0033_delete_tenantinvitation'),
        ('organization', '0034_roleassignment_remove_provider_internal_tenant_and_more'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_52_users_history_2'),
        ('organization', '0100_issue88_shard_51_organization_history_5'),
    ]

    operations = [

    ]
