# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0026_remove_tenantrole_tenant_provider_tenant_provider_and_more'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_50_users_history_1'),
        ('organization', '0100_issue88_shard_40_organization_history_4'),
    ]

    operations = [

    ]
