# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0039_backfill_phase5_rbac'),
    ]

    dependencies = [
        ('users', '0100_issue88_shard_58_users_history_4'),
        ('organization', '0100_issue88_shard_55_organization_history_7'),
    ]

    operations = [

    ]
