# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0015_tenant_currency_default_depreciation'),
        ('organization', '0016_currency_callable_default'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_31_assets_history_6'),
        ('organization', '0100_issue88_shard_07_organization_history_1'),
    ]

    operations = [

    ]
