# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0011_remove_assetholder_organization_assetholder_unique_upn_and_more'),
        ('organization', '0012_alter_contactrole_name_alter_contactrole_slug_and_more'),
        ('organization', '0013_assetholder_custom_field_data_and_more'),
        ('organization', '0014_null_to_empty_strings'),
    ]

    dependencies = [
        ('compliance', '0100_issue88_shard_06_compliance_schema'),
        ('organization', '0100_issue88_shard_04_organization_schema'),
    ]

    operations = [

    ]
