# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.core.validators
import organization.models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('organization', '0001_initial'),
        ('organization', '0002_tenantinvitation_tenantmembership'),
        ('organization', '0003_alter_region_options_alter_site_options_and_more'),
        ('organization', '0004_delete_assetholderassignment'),
        ('organization', '0005_tenantrole_alter_tenantinvitation_role_and_more'),
        ('organization', '0006_assetholder_site_assetholder_tenant_group'),
        ('organization', '0007_remove_assetholder_site_and_more'),
        ('organization', '0008_alter_assetholder_tenant_alter_location_tenant_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_03_extras_schema'),
    ]

    operations = [
        migrations.CreateModel(
                    name='Contact',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                        ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                        ('web_url', models.URLField(blank=True, verbose_name='Web URL')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('comments', models.TextField(blank=True, verbose_name='Comments')),
                    ],
                    options={
                        'verbose_name': 'Contact',
                        'verbose_name_plural': 'Contacts',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ContactAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('object_id', models.PositiveIntegerField()),
                        ('priority', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('inactive', 'Inactive')], max_length=50, verbose_name='Priority')),
                    ],
                    options={
                        'verbose_name': 'Contact Assignment',
                        'verbose_name_plural': 'Contact Assignments',
                        'ordering': ['contact', 'role', 'content_type', 'object_id'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='ContactRole',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Contact Role',
                        'verbose_name_plural': 'Contact Roles',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='CostCenter',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('code', models.CharField(db_index=True, help_text='Short identifier for this cost center (e.g. "CC-100").', max_length=50, verbose_name='Code')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                    ],
                    options={
                        'verbose_name': 'Cost Center',
                        'verbose_name_plural': 'Cost Centers',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Location',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('status', models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50, verbose_name='Status')),
                        ('facility', models.CharField(blank=True, max_length=100, verbose_name='Facility')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Location',
                        'verbose_name_plural': 'Locations',
                        'ordering': ['site', 'name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Membership',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                        ('joined_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'verbose_name': 'Membership',
                        'verbose_name_plural': 'Memberships',
                        'ordering': ['user'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Region',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Region',
                        'verbose_name_plural': 'Regions',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Role',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('permissions', models.JSONField(blank=True, default=list, help_text="List of permission codenames ('app_label.codename').", verbose_name='Permissions')),
                        ('shared_with_managed', models.BooleanField(default=False, help_text='Only meaningful when the owning tenant manages others: managed tenants may assign this role to their own members; only the owning tenant can edit it.', verbose_name='Share with managed tenants')),
                    ],
                    options={
                        'verbose_name': 'Role',
                        'verbose_name_plural': 'Roles',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='RoleGrant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('granted_at', models.DateTimeField(auto_now_add=True)),
                        ('reason', models.TextField(blank=True, verbose_name='Reason')),
                        ('valid_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Valid until')),
                    ],
                    options={
                        'verbose_name': 'Role grant',
                        'verbose_name_plural': 'Role grants',
                        'ordering': ['role', 'membership', 'user_group'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='RoleGrantScope',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('scope_type', models.CharField(choices=[('own', 'Principal tenant'), ('tenant', 'Specific managed tenant'), ('tenant_group', 'Managed tenant group + descendants'), ('all_managed', 'All managed tenants')], db_index=True, max_length=20, verbose_name='Scope type')),
                    ],
                    options={
                        'verbose_name': 'Role grant scope',
                        'verbose_name_plural': 'Role grant scopes',
                        'ordering': ['role_grant', 'scope_type', 'tenant', 'tenant_group'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Site',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('status', models.CharField(choices=[('planned', 'Planned'), ('staging', 'Staging'), ('active', 'Active'), ('decommissioning', 'Decommissioning'), ('retired', 'Retired')], db_index=True, default='active', max_length=50, verbose_name='Status')),
                        ('facility', models.CharField(blank=True, max_length=100, verbose_name='Facility')),
                        ('time_zone', models.CharField(blank=True, max_length=63, verbose_name='Time Zone')),
                        ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                        ('physical_address', models.CharField(blank=True, max_length=200, verbose_name='Physical Address')),
                        ('shipping_address', models.CharField(blank=True, max_length=200, verbose_name='Shipping Address')),
                        ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitude')),
                        ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                        ('comments', models.TextField(blank=True, verbose_name='Comments')),
                    ],
                    options={
                        'verbose_name': 'Site',
                        'verbose_name_plural': 'Sites',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model, core.mixins.BookmarkableMixin),
                ),
        migrations.CreateModel(
                    name='SiteGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Site Group',
                        'verbose_name_plural': 'Site Groups',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='Tenant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('is_provider', models.BooleanField(db_index=True, default=False, help_text='Superuser-controlled. When set, this tenant can manage other tenants and its members can be granted reach into them.', verbose_name='Manages other tenants (MSP mode)')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('comments', models.TextField(blank=True, verbose_name='Comments')),
                        ('currency', models.CharField(default=organization.models._default_currency, help_text='ISO 4217 currency code used for value display (display only, no conversion).', max_length=3, verbose_name='Display currency')),
                        ('changelog_retention_days', models.IntegerField(blank=True, help_text="Overrides ITAMBOX_CHANGELOG_RETENTION_DAYS for this tenant's ObjectChange rows only. Blank uses the global setting. 0 = unlimited (legal hold -- this tenant's changelog is never pruned by prune_changelog).", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Changelog retention override (days)')),
                    ],
                    options={
                        'verbose_name': 'Tenant',
                        'verbose_name_plural': 'Tenants',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model, core.mixins.BookmarkableMixin),
                ),
        migrations.CreateModel(
                    name='TenantGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=100, verbose_name='Name')),
                        ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                    ],
                    options={
                        'verbose_name': 'Tenant Group',
                        'verbose_name_plural': 'Tenant Groups',
                        'ordering': ['name'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='TenantResourceGrant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('resource_id', models.PositiveBigIntegerField(verbose_name='Resource ID')),
                        ('access_level', models.CharField(choices=[('view', 'View'), ('use', 'View + allocate/consume')], db_index=True, default='view', max_length=10, verbose_name='Access level')),
                        ('reason', models.TextField(blank=True, verbose_name='Reason')),
                    ],
                    options={
                        'verbose_name': 'Tenant resource grant',
                        'verbose_name_plural': 'Tenant resource grants',
                        'ordering': ['-created_at'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='AssetHolder',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                        ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                        ('upn', models.CharField(max_length=255, verbose_name='User Principal Name')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                        ('description', models.TextField(blank=True, verbose_name='Description')),
                        ('comments', models.TextField(blank=True, verbose_name='Comments')),
                        ('tags', models.ManyToManyField(blank=True, related_name='organization_assetholders', to='extras.tag', verbose_name='Tags')),
                    ],
                    options={
                        'verbose_name': 'Asset Holder',
                        'verbose_name_plural': 'Asset Holders',
                        'ordering': ['last_name', 'first_name', 'upn'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
