# Generated by Django 5.2.16 on 2026-08-01 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0100_issue88_shard_61_organization_relations"),
        ("users", "0100_issue88_shard_62_users_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='SCIM identifier scoped to this provisioning domain.', max_length=255, verbose_name='External ID'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['tenant', 'external_id'], name='org_membership_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('tenant', 'external_id'), name='organization_membership_unique_tenant_external_id'),
        ),
    ]
