# Generated by Django 5.2.16 on 2026-08-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0101_membership_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantresourcegrant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resource Grant', 'verbose_name_plural': 'Resource Grants'},
        ),
    ]
