# Generated by Django 5.2.16 on 2026-08-15

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0102_alter_tenantresourcegrant_options"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantresourcegrant",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Valid until"),
        ),
        migrations.AddIndex(
            model_name="tenantresourcegrant",
            index=models.Index(
                fields=["tenant", "valid_until"],
                condition=models.Q(deleted_at__isnull=True, valid_until__isnull=False),
                name="org_trg_active_expiry_idx",
            ),
        ),
        migrations.CreateModel(
            name="TenantResourceGrantExpiryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                (
                    "schedule_slot",
                    models.DateTimeField(verbose_name="Schedule slot"),
                ),
                ("cutoff", models.DateTimeField(verbose_name="Cutoff")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("enqueue_failed", "Enqueue failed"),
                            ("complete", "Complete"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("skipped", "Skipped"),
                            ("retryable", "Retryable"),
                            ("terminal", "Terminal"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Outcome",
                    ),
                ),
                ("generation", models.PositiveIntegerField(default=1, verbose_name="Generation")),
                ("attempt_count", models.PositiveIntegerField(default=0, verbose_name="Attempts")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Started at")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True, verbose_name="Last attempt at")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Finished at")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Next retry at")),
                (
                    "dispatch_stale_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Dispatch stale at"),
                ),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lease expires at"),
                ),
                ("revoked_count", models.PositiveIntegerField(default=0, verbose_name="Revoked count")),
                ("remaining_due_count", models.PositiveIntegerField(default=0, verbose_name="Remaining due count")),
                ("invalid_count", models.PositiveIntegerField(default=0, verbose_name="Invalid count")),
                (
                    "error_code",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Error code"),
                ),
                ("error_message", models.TextField(blank=True, null=True, verbose_name="Error message")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_grant_expiry_runs",
                        to="organization.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Grant Expiry Run",
                "verbose_name_plural": "Resource Grant Expiry Runs",
                "ordering": ("-schedule_slot", "-pk"),
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "schedule_slot"),
                        name="organization_trg_expiry_run_tenant_slot_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(generation__gte=1),
                        name="organization_trg_expiry_run_generation_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(attempt_count__gte=0),
                        name="organization_trg_expiry_run_attempts_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                state="queued",
                                outcome__isnull=True,
                                finished_at__isnull=True,
                                lease_expires_at__isnull=True,
                            )
                            | models.Q(
                                state="queued",
                                outcome="retryable",
                                finished_at__isnull=True,
                                lease_expires_at__isnull=True,
                            )
                            | models.Q(
                                state="running",
                                outcome__isnull=True,
                                finished_at__isnull=True,
                                lease_expires_at__isnull=False,
                            )
                            | models.Q(
                                state="enqueue_failed",
                                outcome__isnull=False,
                                outcome="retryable",
                                finished_at__isnull=True,
                                lease_expires_at__isnull=True,
                            )
                            | models.Q(
                                state="complete",
                                outcome__isnull=False,
                                outcome__in=("success", "partial", "skipped", "terminal"),
                                finished_at__isnull=False,
                                lease_expires_at__isnull=True,
                                next_retry_at__isnull=True,
                            )
                        ),
                        name="organization_trg_expiry_run_state_ck",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("tenant", "-schedule_slot"),
                        name="org_trg_run_tenant_slot_idx",
                    ),
                    models.Index(
                        fields=("tenant", "outcome", "-schedule_slot"),
                        name="org_trg_expiry_run_outcome_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantResourceGrantExpiryRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True, editable=False)),
                ("triggering_valid_until", models.DateTimeField(verbose_name="Triggering deadline")),
                ("revoked_at", models.DateTimeField(verbose_name="Revoked at")),
                ("request_id", models.UUIDField(verbose_name="Request ID")),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expiry_revocations",
                        to="organization.tenantresourcegrant",
                        verbose_name="Resource grant",
                    ),
                ),
                (
                    "object_change",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_grant_expiry_revocation",
                        to="core.objectchange",
                        verbose_name="Delete change",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocations",
                        to="organization.tenantresourcegrantexpiryrun",
                        verbose_name="Expiry run",
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
            options={
                "verbose_name": "Resource Grant Expiry Revocation",
                "verbose_name_plural": "Resource Grant Expiry Revocations",
                "ordering": ("-revoked_at", "-pk"),
                "default_permissions": (),
                "base_manager_name": "all_objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grant", "revoked_at"),
                        name="organization_trg_expiry_revoke_grant_time_uniq",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("run", "grant"),
                        name="org_trg_revoke_run_grant_idx",
                    ),
                ],
            },
        ),
    ]
