# Generated by Django 5.2.17 on 2026-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0100_issue88_shard_62_users_relations"),
        ("organization", "0103_tenant_resource_grant_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
    ]
