# Generated by Django 5.2.16 on 2026-08-30 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0103_tenant_resource_grant_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='changelog_retention_days',
            field=models.IntegerField(blank=True, help_text="Set to 0 for unlimited retention under a legal hold. This tenant's change log will not be pruned automatically.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Changelog retention override (days)'),
        ),
    ]
