# Generated by Django 5.2 on 2026-05-29 18:13

import compliance.models
import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('extras', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='Maintenance', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('maintenance_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('repair', 'Repair'), ('calibration', 'Calibration'), ('software_support', 'Software Support'), ('hardware_support', 'Hardware Support')], db_index=True, default='repair', max_length=50, verbose_name='Maintenance Type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maintenance Cost')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('completion_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Completion Date')),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.asset')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='Supplier/Vendor')),
                ('tags', models.ManyToManyField(blank=True, related_name='asset_maintenances', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenances',
                'ordering': ['-start_date'],
            },
            bases=(core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustodyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=compliance.models.generate_token, max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('acceptance_method', models.CharField(default='link', max_length=50)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('signature_canvas', models.TextField(blank=True, help_text='Base64 canvas stroke vector string representation', null=True)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eula_version', models.CharField(default='1.0', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_receipts', to='assets.asset')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_receipts', to='organization.assetholder')),
            ],
            options={
                'verbose_name': 'Custody Receipt',
                'verbose_name_plural': 'Custody Receipts',
                'ordering': ('-signed_at',),
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
