# Generated by Django 5.2 on 2026-06-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_custodytemplate_email_signature_request_and_more'),
        ('organization', '0004_delete_assetholderassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytemplate',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='Target Tenant Group this template applies to (conglomerate/divisional scope).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_templates', to='organization.tenantgroup'),
        ),
    ]
