# Generated by Django 5.2.15 on 2026-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_custodytemplate_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
