# Generated by Django 5.2.15 on 2026-06-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_assetassignment_assigned_asset_and_more'),
        ('compliance', '0006_custodytemplate_deleted_at'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='organization.assetholder'),
        ),
    ]
