# Generated by Django 5.2.15 on 2026-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_null_to_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='reconciliation_report',
            field=models.JSONField(blank=True, editable=False, help_text='Frozen reconciliation report written at close time. Denormalized for long-term readability.', null=True),
        ),
    ]
