# Generated by Django 5.2.15 on 2026-06-10 22:27
#
# Backfill rule (RunPython below):
#   1. If the session has a location, use location.tenant.
#   2. Else look at the tenants of the session's audited assets; if unambiguous
#      (exactly one distinct tenant), use that.
#   3. If genuinely ambiguous (cross-tenant assets or no assets), leave NULL and
#      log a warning — do not silently globalise private session data.

import django.db.models.deletion
from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)


def backfill_session_tenant(apps, schema_editor):
    AuditSession = apps.get_model('compliance', 'AuditSession')
    AssetAudit = apps.get_model('compliance', 'AssetAudit')

    for session in AuditSession.objects.filter(tenant__isnull=True).select_related('location'):
        tenant = None

        # Strategy 1: infer from the session's location.
        if session.location_id and session.location.tenant_id:
            tenant = session.location.tenant

        if tenant is None:
            # Strategy 2: derive from the tenant of audited assets (if unambiguous).
            asset_tenant_ids = list(
                AssetAudit.objects.filter(session=session)
                .values_list('asset__tenant_id', flat=True)
                .distinct()
            )
            # Filter out None (assets with no tenant assignment)
            asset_tenant_ids = [t for t in asset_tenant_ids if t is not None]
            if len(asset_tenant_ids) == 1:
                Tenant = apps.get_model('organization', 'Tenant')
                try:
                    tenant = Tenant.objects.get(pk=asset_tenant_ids[0])
                except Tenant.DoesNotExist:
                    pass
            elif len(asset_tenant_ids) > 1:
                logger.warning(
                    "AuditSession pk=%s references assets from multiple tenants "
                    "(%s); leaving tenant=NULL (global).",
                    session.pk, asset_tenant_ids,
                )
                continue

        if tenant is not None:
            session.tenant = tenant
            session.save(update_fields=['tenant'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_auditsession_reconciliation_report'),
        ('organization', '0014_null_to_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this campaign belongs to. Leave blank for MSP-wide / global sessions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to='organization.tenant'),
        ),
        migrations.RunPython(backfill_session_tenant, reverse_code=noop),
    ]
