# Generated by Django 5.2.15 on 2026-06-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_asset_uniq_active_tenant_serial'),
        ('compliance', '0014_auditsession_tenant'),
        ('organization', '0016_currency_callable_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaudit',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this campaign belongs to. Leave blank for MSP-wide / global sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_templates', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='Target Tenant Group this template applies to (conglomerate/divisional scope).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='organization.tenantgroup'),
        ),
    ]
