# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('compliance', '0015_alter_assetaudit_asset_alter_auditsession_tenant_and_more'),
        ('extras', '0034_journalentry_tenant'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaudit',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_performed', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='location',
            field=models.ForeignKey(help_text='The observed physical location of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.auditsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='status',
            field=models.ForeignKey(help_text='The observed physical status of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='assets.statuslabel', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetaudit',
            name='verification_method',
            field=models.CharField(choices=[('barcode', 'Barcode Scan'), ('rfid', 'RFID Reader'), ('manual', 'Manual Input'), ('auto', 'Agent API Handshake')], default='manual', max_length=30, verbose_name='Verification Method'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Target location expected to be audited. If omitted, applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this campaign belongs to. Leave blank for MSP-wide / global sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='acceptance_method',
            field=models.CharField(default='link', max_length=50, verbose_name='Acceptance Method'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20, verbose_name='Acceptance Status'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted Date'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='custody_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='compliance.custodytemplate', verbose_name='Custody Template'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='disclaimer',
            field=models.TextField(blank=True, verbose_name='Disclaimer'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='eula_text',
            field=models.TextField(blank=True, verbose_name='EULA Text'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='eula_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='EULA Version'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='organization.assetholder', verbose_name='Holder'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='qms_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='QMS Reference'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='signature_canvas',
            field=models.TextField(blank=True, help_text='Base64 canvas stroke vector string representation', verbose_name='Signature Canvas'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='signature_data',
            field=models.TextField(blank=True, verbose_name='Signature Data'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='signature_provider',
            field=models.CharField(default='local', max_length=50, verbose_name='Signature Provider'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='signed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Signed At'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Target Category this template overrides for the selected Tenant scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Disclaimer statement printed at signoff', verbose_name='Disclaimer'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='email_signature_request',
            field=models.BooleanField(default=True, help_text='Send email signature request link to the holder on checkout.', verbose_name='Email Signature Request'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='eula_text',
            field=models.TextField(help_text='Terms of Service / EULA guidelines', verbose_name='EULA Text'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate to hide from choices', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='logo',
            field=models.ImageField(blank=True, help_text='Custom EULA / signoff logo image', null=True, upload_to='custody_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='name',
            field=models.CharField(help_text='Template Name (e.g. Standard Laptop EULA)', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='qms_reference',
            field=models.CharField(blank=True, help_text='Quality Management System document reference key', max_length=100, verbose_name='QMS Reference'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='require_acceptance',
            field=models.BooleanField(default=True, help_text='Require digital signature / EULA acceptance on checkout.', verbose_name='Require Acceptance'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='signature_provider',
            field=models.CharField(default='local', help_text='E-Signature workflow provider module', max_length=50, verbose_name='Signature Provider'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='custody_templates', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_templates', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='custodytemplate',
            name='tenant_group',
            field=models.ForeignKey(blank=True, help_text='Target Tenant Group this template applies to (conglomerate/divisional scope).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='organization.tenantgroup', verbose_name='Tenant Group'),
        ),
    ]
