# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('compliance', '0003_custodytemplate_category'),
        ('compliance', '0004_custodytemplate_email_signature_request_and_more'),
        ('compliance', '0005_custodytemplate_tenant_group'),
        ('compliance', '0006_custodytemplate_deleted_at'),
        ('compliance', '0007_alter_assetmaintenance_asset_and_more'),
        ('compliance', '0008_alter_assetmaintenance_deleted_at_and_more'),
        ('compliance', '0009_auditsession_assetaudit'),
        ('compliance', '0010_repoint_audit_contenttypes'),
        ('compliance', '0011_remove_assetmaintenance'),
        ('compliance', '0012_null_to_empty_strings'),
        ('compliance', '0013_auditsession_reconciliation_report'),
        ('compliance', '0014_auditsession_tenant'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_29_assets_history_5'),
        ('compliance', '0100_issue88_shard_06_compliance_schema'),
    ]

    operations = [

    ]
