# Generated by Django 5.2.16 for ITAMbox issue #88.

import compliance.models
import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('compliance', '0015_alter_assetaudit_asset_alter_auditsession_tenant_and_more'),
        ('compliance', '0016_alter_assetaudit_asset_alter_assetaudit_auditor_and_more'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_43_assets_seed'),
        ('compliance', '0100_issue88_shard_30_compliance_history_1'),
    ]

    operations = [
        migrations.AddField(
                    model_name='assetaudit',
                    name='auditor',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_performed', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
                ),
        migrations.AddField(
                    model_name='assetaudit',
                    name='location',
                    field=models.ForeignKey(help_text='The observed physical location of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='assetaudit',
                    name='status',
                    field=models.ForeignKey(help_text='The observed physical status of the asset during audit.', on_delete=django.db.models.deletion.PROTECT, to='assets.statuslabel', verbose_name='Status'),
                ),
        migrations.AddField(
                    model_name='auditsession',
                    name='created_by',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
                ),
        migrations.AddField(
                    model_name='auditsession',
                    name='location',
                    field=models.ForeignKey(blank=True, help_text='Target location expected to be audited. If omitted, applies globally.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='auditsession',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Tenant this campaign belongs to. Leave blank for MSP-wide / global sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_sessions', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='assetaudit',
                    name='session',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.auditsession', verbose_name='Session'),
                ),
        migrations.AddField(
                    model_name='custodyreceipt',
                    name='asset',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='custodyreceipt',
                    name='holder',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='organization.assetholder', verbose_name='Holder'),
                ),
        migrations.AddField(
                    model_name='custodytemplate',
                    name='category',
                    field=models.ForeignKey(blank=True, help_text='Target Category this template overrides for the selected Tenant scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='assets.category', verbose_name='Category'),
                ),
        migrations.AddField(
                    model_name='custodytemplate',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='custody_templates', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='custodytemplate',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_templates', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='custodytemplate',
                    name='tenant_group',
                    field=models.ForeignKey(blank=True, help_text='Target Tenant Group this template applies to (conglomerate/divisional scope).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='organization.tenantgroup', verbose_name='Tenant Group'),
                ),
        migrations.AddField(
                    model_name='custodyreceipt',
                    name='custody_template',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='compliance.custodytemplate', verbose_name='Custody Template'),
                ),
        migrations.AddConstraint(
                    model_name='assetaudit',
                    constraint=models.UniqueConstraint(fields=('session', 'asset'), name='unique_session_asset'),
                ),
    ]
