# Generated by Django 5.2.16 for ITAMbox issue #88.

import compliance.models
import core.mixins
import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    replaces = [
        ('compliance', '0001_initial'),
        ('compliance', '0002_custodyreceipt_disclaimer_custodyreceipt_eula_text_and_more'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_05_extras_history_1'),
    ]

    operations = [
        migrations.CreateModel(
                    name='AuditSession',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(max_length=200, verbose_name='Name')),
                        ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed')], default='planned', max_length=20, verbose_name='Status')),
                        ('started_at', models.DateTimeField(auto_now_add=True)),
                        ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                        ('reconciliation_report', models.JSONField(blank=True, editable=False, help_text='Frozen reconciliation report written at close time. Denormalized for long-term readability.', null=True)),
                    ],
                    options={
                        'verbose_name': 'Audit Session',
                        'verbose_name_plural': 'Audit Sessions',
                        'ordering': ['-started_at'],
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='CustodyReceipt',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('token', models.CharField(default=compliance.models.generate_token, max_length=64, unique=True)),
                        ('signature_provider', models.CharField(default='local', max_length=50, verbose_name='Signature Provider')),
                        ('eula_text', models.TextField(blank=True, verbose_name='EULA Text')),
                        ('disclaimer', models.TextField(blank=True, verbose_name='Disclaimer')),
                        ('qms_reference', models.CharField(blank=True, max_length=100, verbose_name='QMS Reference')),
                        ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                        ('accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Accepted Date')),
                        ('acceptance_method', models.CharField(default='link', max_length=50, verbose_name='Acceptance Method')),
                        ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20, verbose_name='Acceptance Status')),
                        ('signature_data', models.TextField(blank=True, verbose_name='Signature Data')),
                        ('signature_hash', models.CharField(blank=True, max_length=64)),
                        ('verification_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                        ('signature_canvas', models.TextField(blank=True, help_text='Base64 canvas stroke vector string representation', verbose_name='Signature Canvas')),
                        ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Signed At')),
                        ('eula_version', models.CharField(default='1.0', max_length=10, verbose_name='EULA Version')),
                        ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                        ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                    ],
                    options={
                        'verbose_name': 'Custody Receipt',
                        'verbose_name_plural': 'Custody Receipts',
                        'ordering': ('-signed_at',),
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='CustodyTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Template Name (e.g. Standard Laptop EULA)', max_length=255, verbose_name='Name')),
                        ('signature_provider', models.CharField(default='local', help_text='E-Signature workflow provider module', max_length=50, verbose_name='Signature Provider')),
                        ('logo', models.ImageField(blank=True, help_text='Custom EULA / signoff logo image', null=True, upload_to='custody_logos/', verbose_name='Logo')),
                        ('eula_text', models.TextField(help_text='Terms of Service / EULA guidelines', verbose_name='EULA Text')),
                        ('disclaimer', models.TextField(blank=True, help_text='Disclaimer statement printed at signoff', verbose_name='Disclaimer')),
                        ('qms_reference', models.CharField(blank=True, help_text='Quality Management System document reference key', max_length=100, verbose_name='QMS Reference')),
                        ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide from choices', verbose_name='Is Active')),
                        ('require_acceptance', models.BooleanField(default=True, help_text='Require digital signature / EULA acceptance on checkout.', verbose_name='Require Acceptance')),
                        ('email_signature_request', models.BooleanField(default=True, help_text='Send email signature request link to the holder on checkout.', verbose_name='Email Signature Request')),
                    ],
                    options={
                        'verbose_name': 'Custody Template',
                        'verbose_name_plural': 'Custody Templates',
                        'ordering': ('name',),
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='AssetAudit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                        ('verification_method', models.CharField(choices=[('barcode', 'Barcode Scan'), ('rfid', 'RFID Reader'), ('manual', 'Manual Input'), ('auto', 'Agent API Handshake')], default='manual', max_length=30, verbose_name='Verification Method')),
                        ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='assets.asset', verbose_name='Asset')),
                    ],
                    options={
                        'verbose_name': 'Asset Audit',
                        'verbose_name_plural': 'Asset Audits',
                        'ordering': ['-timestamp'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
