# Generated by Django 5.2.16 on 2026-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0100_issue88_shard_44_compliance_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodyreceipt',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signed At'),
        ),
    ]
