# Generated by Django 5.2.16 on 2026-08-09 20:29

from django.db import migrations


def clear_unsigned_receipt_timestamps(apps, schema_editor):
    CustodyReceipt = apps.get_model('compliance', 'CustodyReceipt')
    CustodyReceipt.objects.exclude(acceptance_status='accepted').update(signed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0101_alter_custodyreceipt_signed_at'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.RunPython(clear_unsigned_receipt_timestamps, migrations.RunPython.noop),
    ]
