# Generated by Django 5.2.16 on 2026-08-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0102_clear_unsigned_receipt_timestamps'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custodyreceipt',
            options={'ordering': ('-signed_at',), 'permissions': (('prepare_custodyreceipt', 'Can prepare custody receipt signing sessions'), ('export_custodyreceipt', 'Can export custody receipts')), 'verbose_name': 'Custody Receipt', 'verbose_name_plural': 'Custody Receipts'},
        ),
    ]
