# Generated by Django 5.2.16 on 2026-08-10 07:27

import compliance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0103_alter_custodyreceipt_options'),
        ('organization', '0102_alter_tenantresourcegrant_options'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodySigningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=compliance.models.generate_custody_signing_session_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=compliance.models.custody_signing_session_expiry, editable=False)),
                ('consumed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], editable=False, max_length=20)),
                ('intended_holder', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_signing_sessions', to='organization.assetholder', verbose_name='Intended Holder')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_custody_signing_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('receipt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='signing_sessions', to='compliance.custodyreceipt', verbose_name='Custody Receipt')),
            ],
            options={
                'verbose_name': 'Custody Signing Session',
                'verbose_name_plural': 'Custody Signing Sessions',
                'ordering': ('-created_at', '-pk'),
                'default_permissions': (),
            },
        ),
    ]
