# Generated by Django 5.2.16 on 2026-08-10 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0104_custodysigningsession'),
        ('users', '0100_issue88_shard_62_users_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyHandoffDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.PositiveIntegerField(verbose_name='Attempt')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('succeeded', 'Succeeded'), ('terminal_failed', 'Terminal failure')], max_length=20, verbose_name='Status')),
                ('error_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Error class')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('operator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='custody_handoff_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('receipt', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='handoff_deliveries', to='compliance.custodyreceipt', verbose_name='Custody Receipt')),
                ('signing_session', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='handoff_deliveries', to='compliance.custodysigningsession', verbose_name='Custody Signing Session')),
            ],
            options={
                'verbose_name': 'Custody Handoff Delivery',
                'verbose_name_plural': 'Custody Handoff Deliveries',
                'ordering': ('-created_at', '-pk'),
                'unique_together': {('signing_session', 'attempt')},
            },
        ),
    ]
