# Generated by Django 5.2.17 on 2026-10-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0105_custodyhandoffdelivery'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodyreceipt',
            name='accepted',
        ),
    ]
