# Generated by Django 5.2.17 on 2026-10-06 12:48

import django.db.models.deletion
from django.db import migrations, models


def backfill_assignment_and_supersede(apps, schema_editor):
    """Link receipts to their custody period where unambiguous; close stale pending receipts."""
    CustodyReceipt = apps.get_model("compliance", "CustodyReceipt")
    AssetAssignment = apps.get_model("assets", "AssetAssignment")
    db = schema_editor.connection.alias
    for receipt in CustodyReceipt.objects.using(db).filter(assignment__isnull=True).iterator():
        candidates = list(
            AssetAssignment.objects.using(db).filter(asset_id=receipt.asset_id, assigned_user_id=receipt.holder_id)
        )
        if len(candidates) > 1 and receipt.created_date is not None:
            candidates = [
                a
                for a in candidates
                if a.checked_out_at <= receipt.created_date
                and (a.checked_in_at is None or a.checked_in_at >= receipt.created_date)
            ]
        if len(candidates) == 1:
            CustodyReceipt.objects.using(db).filter(pk=receipt.pk).update(assignment_id=candidates[0].pk)
    stale = CustodyReceipt.objects.using(db).filter(acceptance_status="pending")
    for receipt in stale.iterator():
        if receipt.assignment_id is not None:
            active = AssetAssignment.objects.using(db).filter(pk=receipt.assignment_id, is_active=True).exists()
        else:
            active = AssetAssignment.objects.using(db).filter(
                asset_id=receipt.asset_id, assigned_user_id=receipt.holder_id, is_active=True
            ).exists()
        if not active:
            CustodyReceipt.objects.using(db).filter(pk=receipt.pk).update(acceptance_status="superseded")


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0121_supplier_scoping_and_commercial_fields'),
        ('compliance', '0106_remove_custodyreceipt_accepted'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodyreceipt',
            name='assignment',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_receipts', to='assets.assetassignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='custodyreceipt',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=20, verbose_name='Acceptance Status'),
        ),
        migrations.RunPython(backfill_assignment_and_supersede, migrations.RunPython.noop),
    ]
