# Generated by Django 5.2 on 2026-05-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, help_text='Optional destination URL when clicked.', max_length=500, null=True),
        ),
    ]
