# Generated by Django 5.2 on 2025-04-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objectchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
