# Generated by Django 5.2 on 2026-05-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reporttemplate_alertrule_scheduledreport_alertlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='advanced_mode',
            field=models.BooleanField(default=False, help_text='Enable custom Jinja2/HTML template code override.'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='group_by_field',
            field=models.CharField(blank=True, help_text='Optional column key to group grid records under (e.g. location, status).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='include_distribution_chart',
            field=models.BooleanField(default=False, help_text='Toggle embedding spend or status distribution charts in the HTML report.'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='include_summary_cards',
            field=models.BooleanField(default=True, help_text='Toggle displaying top card widgets (totals, counts, financial sums).'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='included_columns',
            field=models.JSONField(blank=True, default=list, help_text='Checked columns to render in the report data grid.'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='style_preset',
            field=models.CharField(choices=[('default', 'Professional Layout'), ('compact', 'Compact Audit Sheet'), ('financial', 'Financial Spend Summary')], default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=50),
        ),
    ]
