# Generated by Django 5.2 on 2026-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectchange',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('checkout', 'Checked Out'), ('checkin', 'Checked In'), ('audit', 'Audited')], db_index=True, max_length=50),
        ),
    ]
