# Generated by Django 5.2 on 2026-05-30 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reporttemplate_advanced_mode_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this log. Null represents system-wide logs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this rule. Null represents system-wide rules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this channel. Null represents system-wide channels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organization.tenant'),
        ),
    ]
