# Generated by Django 5.2 on 2026-05-30 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alertlog_tenant_alertrule_tenant_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this report template. Null represents system-wide templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this scheduled report. Null represents system-wide schedules.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organization.tenant'),
        ),
    ]
