# Generated by Django 5.2 on 2026-05-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reporttemplate_tenant_scheduledreport_tenant'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='filter_tenants',
            field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_templates', to='organization.tenant'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='filter_tenants',
            field=models.ManyToManyField(blank=True, help_text='Filter compiled data to only include these selected tenants. If none are selected, aggregates data globally.', related_name='filtered_schedules', to='organization.tenant'),
        ),
    ]
