# Generated by Django 5.2 on 2026-05-27 09:37

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_phase1_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(default='localhost', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=25)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('from_address', models.EmailField(default='assetbox@localhost', max_length=255)),
                ('from_name', models.CharField(default='AssetBox Notifications', max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('test_recipient', models.EmailField(blank=True, help_text='Email address for test notifications', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('in_app', 'In-App'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Channel-specific config (SMTP settings, webhook URL, etc.)')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('checkout', 'Checkout'), ('checkin', 'Checkin'), ('audit', 'Audit'), ('expiring', 'Expiring Alert'), ('low_stock', 'Low Stock Alert'), ('renewal', 'Renewal Reminder')], max_length=30)),
                ('subject_template', models.CharField(blank=True, help_text='Jinja2 template for notification subject', max_length=500)),
                ('body_template', models.TextField(blank=True, help_text='Jinja2 template for notification body')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.notificationchannel')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
