# Generated by Django 5.2 on 2026-05-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_phase2_feature_parity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_code', models.TextField(help_text='Jinja2 or Django template code for export')),
                ('mime_type', models.CharField(default='text/csv', help_text='MIME type for the exported file', max_length=50)),
                ('file_extension', models.CharField(default='csv', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'ordering': ['content_type', 'name'],
                'unique_together': {('content_type', 'name')},
            },
        ),
    ]
