# Generated by Django 5.2 on 2026-05-31 16:05

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alertlog_acknowledged_by_alertlog_resolution_notes_and_more'),
        ('organization', '0002_tenantinvitation_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='scheduled_reports', to='core.notificationchannel'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Custom Cron Expression (e.g. '0 8 * * 1-5')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='save_to_archive',
            field=models.BooleanField(default=True, help_text='Store a copy of generated reports in the local file archive'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Time of day to run the schedule (e.g. 08:00:00)', null=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('asset_summary', 'Asset Inventory Summary'), ('license_utilization', 'License Utilization'), ('subscription_renewals', 'Subscription Renewals'), ('asset_maintenance', 'Asset Maintenance & Repairs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('cron', 'Custom Cron Expression')], default='weekly', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='recipients',
            field=models.TextField(blank=True, default='', help_text='Comma-separated email addresses'),
        ),
        migrations.CreateModel(
            name='ReportGenerationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('format', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_archives', to='core.fileattachment')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.scheduledreport')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_archives', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Report Generation Archive',
                'verbose_name_plural': 'Report Generation Archives',
                'ordering': ['-generated_at'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
