# Generated by Django 5.2 on 2026-05-27 10:47

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_export_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('page_width', models.FloatField(default=2.25, help_text='Label width in inches')),
                ('page_height', models.FloatField(default=1.25, help_text='Label height in inches')),
                ('barcode_format', models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('qr', 'QR Code'), ('datamatrix', 'Data Matrix')], default='code128', max_length=20)),
                ('template_code', models.TextField(blank=True, help_text='Jinja2/HTML template for label layout')),
                ('printer_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Label Template',
                'verbose_name_plural': 'Label Templates',
                'ordering': ['name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LDAPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_uri', models.CharField(help_text='ldap://ldap.example.com', max_length=500)),
                ('bind_dn', models.CharField(blank=True, max_length=500)),
                ('bind_password', models.CharField(blank=True, max_length=255)),
                ('user_search_base', models.CharField(blank=True, max_length=500)),
                ('user_search_filter', models.CharField(default='(uid=%(user)s)', max_length=500)),
                ('group_search_base', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('require_group', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'LDAP Settings',
                'verbose_name_plural': 'LDAP Settings',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SAMLSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idp_metadata_url', models.URLField(blank=True, help_text='Identity Provider metadata URL')),
                ('idp_entity_id', models.CharField(blank=True, max_length=500)),
                ('sp_entity_id', models.CharField(default='assetbox', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('strict', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SAML Settings',
                'verbose_name_plural': 'SAML Settings',
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict, help_text="{'assets.view_asset': True, 'assets.change_asset': True, ...}")),
                ('users', models.ManyToManyField(blank=True, related_name='permission_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
                'ordering': ['name'],
            },
        ),
    ]
