# Generated by Django 5.2 on 2026-05-29 23:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Priority weight for dictionary merging conflict resolution')),
                ('data', models.JSONField(help_text='Serialized configuration dictionary')),
                ('locations', models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.location')),
                ('regions', models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.region')),
                ('sites', models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.site')),
                ('tenants', models.ManyToManyField(blank=True, related_name='config_contexts', to='organization.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
