# Generated by Django 5.2 on 2026-05-30 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def make_existing_dashboards_default(apps, schema_editor):
    Dashboard = apps.get_model('extras', 'Dashboard')
    Dashboard.objects.all().update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_configcontext'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='Main Dashboard', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Scope all widgets on this dashboard to this specific tenant context.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(make_existing_dashboards_default),
    ]
