# Generated by Django 5.2 on 2026-05-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_remove_assetrole_config_template'),
        ('extras', '0002_configtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigTemplate',
        ),
    ]
