# Generated by Django 5.2 on 2026-06-02 16:11

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0004_delete_assetholderassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodyreceipt',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custodyreceipt',
            name='eula_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custodyreceipt',
            name='qms_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custodyreceipt',
            name='signature_provider',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.CreateModel(
            name='CustodyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template Name (e.g. Standard Laptop EULA)', max_length=255)),
                ('signature_provider', models.CharField(default='local', help_text='E-Signature workflow provider module', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Custom EULA / signoff logo image', null=True, upload_to='custody_logos/')),
                ('eula_text', models.TextField(help_text='Terms of Service / EULA guidelines')),
                ('disclaimer', models.TextField(blank=True, help_text='Disclaimer statement printed at signoff')),
                ('qms_reference', models.CharField(blank=True, help_text='Quality Management System document reference key', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide from choices')),
                ('tags', models.ManyToManyField(blank=True, related_name='custody_templates', to='extras.tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_templates', to='organization.tenant')),
            ],
            options={
                'verbose_name': 'Custody Template',
                'verbose_name_plural': 'Custody Templates',
                'ordering': ('name',),
            },
            bases=(core.mixins.TaggableMixin, core.mixins.CloneableMixin, core.mixins.ExportableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='custodyreceipt',
            name='custody_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='compliance.custodytemplate'),
        ),
    ]
