# Generated by Django 5.2 on 2026-06-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_category_custody_template'),
        ('compliance', '0002_custodyreceipt_disclaimer_custodyreceipt_eula_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Target Category this template overrides for the selected Tenant scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_templates', to='assets.category'),
        ),
    ]
