# Generated by Django 5.2 on 2026-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_custodytemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodytemplate',
            name='email_signature_request',
            field=models.BooleanField(default=True, help_text='Send email signature request link to the holder on checkout.'),
        ),
        migrations.AddField(
            model_name='custodytemplate',
            name='require_acceptance',
            field=models.BooleanField(default=True, help_text='Require digital signature / EULA acceptance on checkout.'),
        ),
    ]
