# Generated by Django 5.2 on 2026-05-29 12:15

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0035_category_dict_and_components'),
        ('extras', '0004_dashboard_model'),
        ('organization', '0006_alter_location_name_alter_location_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(limit_choices_to={'applies_to__component': True}, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='assets.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='assets.manufacturer')),
                ('tags', models.ManyToManyField(blank=True, related_name='new_components', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Component (Catalog)',
                'verbose_name_plural': 'Components (Catalog)',
                'ordering': ('manufacturer', 'name'),
                'unique_together': {('manufacturer', 'name')},
            },
            bases=(core.mixins.AutoSlugMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComponentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('qty_allocated', models.PositiveIntegerField(default=1)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_allocations', to='assets.asset')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='components.component')),
                ('tags', models.ManyToManyField(blank=True, related_name='component_allocations', to='extras.tag')),
            ],
            options={
                'verbose_name': 'Component Allocation',
                'verbose_name_plural': 'Component Allocations',
                'ordering': ('-allocated_at',),
            },
            bases=(core.mixins.TaggableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComponentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='components.component')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_stocks', to='organization.location')),
            ],
            options={
                'verbose_name': 'Component Stock',
                'verbose_name_plural': 'Component Stocks',
                'ordering': ('component', 'location'),
                'unique_together': {('component', 'location')},
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
