# Generated by Django 5.2 on 2026-05-29 12:16

from django.db import migrations


def migrate_component_types_to_components(apps, schema_editor):
    ComponentType = apps.get_model('assets', 'ComponentType')
    ComponentInstance = apps.get_model('assets', 'ComponentInstance')
    Category = apps.get_model('assets', 'Category')
    Component = apps.get_model('components', 'Component')
    ComponentStock = apps.get_model('components', 'ComponentStock')
    ComponentAllocation = apps.get_model('components', 'ComponentAllocation')

    comp_type_cat_map = {
        'ram': 'RAM',
        'storage': 'SSD',
        'gpu': 'GPU',
        'cpu': 'CPU',
        'nic': 'NIC',
        'other': 'Other',
    }

    component_type_to_new = {}

    for ct in ComponentType.objects.all():
        cat_name = comp_type_cat_map.get(ct.category, 'Other')
        cat, _ = Category.objects.get_or_create(
            name=cat_name,
            defaults={
                'slug': cat_name.lower().replace(' ', '-'),
                'applies_to': {'component': True},
            }
        )
        if not cat.applies_to.get('component'):
            cat.applies_to['component'] = True
            cat.save(update_fields=['applies_to'])

        comp = Component.objects.create(
            name=ct.name,
            slug=ct.slug if ct.slug else f"{ct.manufacturer.name}-{ct.name}".lower().replace(' ', '-')[:255],
            manufacturer=ct.manufacturer,
            category=cat,
            part_number=ct.part_number or '',
            specs={'specs': ct.specs} if ct.specs else {},
            min_stock_level=0,
            description=ct.description or '',
        )
        component_type_to_new[ct.pk] = comp

    for ci in ComponentInstance.objects.all():
        comp = component_type_to_new.get(ci.component_type_id)
        if comp is None:
            continue

        if ci.parent_asset:
            ComponentAllocation.objects.create(
                component=comp,
                asset=ci.parent_asset,
                qty_allocated=1,
                notes=ci.notes or '',
            )
        elif ci.status == 'in_stock':
            location = ci.parent_asset.location if ci.parent_asset else None
            if location or ci.parent_asset:
                loc = ci.parent_asset.location if ci.parent_asset else None
                if loc:
                    ComponentStock.objects.get_or_create(
                        component=comp,
                        location=loc,
                        defaults={'qty': 0},
                    )
                    stock = ComponentStock.objects.get(component=comp, location=loc)
                    stock.qty += 1
                    stock.save(update_fields=['qty'])


def reverse_migration(apps, schema_editor):
    Component = apps.get_model('components', 'Component')
    ComponentStock = apps.get_model('components', 'ComponentStock')
    ComponentAllocation = apps.get_model('components', 'ComponentAllocation')
    ComponentStock.objects.all().delete()
    ComponentAllocation.objects.all().delete()
    Component.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_category_dict_and_components'),
        ('assets', '0035_category_dict_and_components'),
    ]

    operations = [
        migrations.RunPython(migrate_component_types_to_components, reverse_migration),
    ]
