# Generated by Django 5.2 on 2026-05-31 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_deleted_at_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='organization.tenant'),
        ),
    ]
