"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# AssetBox Version
VERSION = '0.1.0'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7&re8o6pow!b5aakt7ox#n$8_%)$qs@b9^@dnsi@h0e5j&&*sz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assets',
    'organization',
    'software',
    'subscriptions',
    'licenses',
    'django_tables2',
    'template_partials',
    'django_htmx',
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
    'extras.apps.ExtrasConfig',
    'rest_framework',
    'drf_spectacular',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'core.middleware.CurrentUserMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Keep your existing default_loaders definition if you have one, or define it:
default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

# Configure cached and partial loaders
# TODO: Consider enabling cached loader in production (requires defining CACHES)
# cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]
# partial_loaders = [("template_partials.loader.Loader", cached_loaders)]
# For now, use non-cached version for simplicity
partial_loaders = [("template_partials.loader.Loader", default_loaders)]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False, # Explicit loaders are defined below
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.breadcrumbs',
                 # Add any custom ones AssetBox needs
            ],
            # Ensure 'loaders' is set correctly: - REMOVED partial_loaders
            'loaders': partial_loaders,
            # Explicitly register libraries if auto-discovery fails - REMOVED
            # 'libraries': {
            #     'htmx_tags': 'django_htmx.templatetags.htmx_tags',
            #     # Add other potentially problematic libraries here if needed
            # },
            # Add 'builtins' if not already present for template_partials tags
            # 'builtins': [ # REMOVED builtins as APP_DIRS handles discovery
            #     # 'template_partials.templatetags.partials', # Removed - Loader should handle this
            #     # Add other custom builtins if needed
            #     'django_tables2.templatetags.django_tables2', # Ensure tables2 tags are loaded if needed globally
            #     'django.templatetags.static', # Common builtin
            #     'crispy_forms.templatetags.crispy_forms_tags', # Common builtin
            #     # 'django_htmx', # Removed - htmx tags should be loaded explicitly
            # ],
            # 'debug': DEBUG, # Link to your project's DEBUG setting - Handled by Django automatically based on DEBUG setting
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Add other DRF settings here if needed in the future
    # e.g., authentication, permissions, pagination
}

SEARCH_BACKEND = 'core.search_backends.DatabaseBackend'

# Login/Logout Redirects
LOGIN_URL = 'login' # URL name for the login view
LOGIN_REDIRECT_URL = 'dashboard' # URL name to redirect to after successful login
LOGOUT_REDIRECT_URL = 'login' # URL name to redirect to after logout

# --- Pagination Settings --- 
DEFAULT_PAGINATE_COUNT = 25 
PAGINATE_COUNT_CHOICES = (
    (25, '25'), 
    (50, '50'),
    (100, '100'),
    (250, '250'),
    (500, '500'),
    (1000, '1000'),
)