# Generated by Django 5.2 on 2026-06-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_assetholder_site_and_more'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='Unique name of the software product (e.g., Microsoft Visio Professional 2021)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('name', 'tenant')},
        ),
    ]
