# Generated by Django 5.2.15 on 2026-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_software_tenant_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='software',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='Unique name of the software product (e.g., Microsoft Visio Professional 2021)', max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='software',
            name='tenant',
        ),
    ]
