# Generated by Django 5.2.15 on 2026-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_alter_software_unique_together_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
