# Generated by Django 5.2.15 on 2026-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_software_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
