# Generated by Django 5.2.15 on 2026-06-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0044_assetrole_allows_components'),
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('organization', '0016_currency_callable_default'),
        ('software', '0008_repoint_installedsoftware_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. Null denotes a shared/global catalogue entry visible to all tenants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='Name of the software product (e.g., Microsoft Visio Professional 2021). Unique per tenant.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'name'), name='unique_tenant_software_name'),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', True)), fields=('name',), name='unique_global_software_name'),
        ),
    ]
