# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('software', '0009_software_tenant_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedsoftware',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='install_date',
            field=models.DateField(blank=True, db_index=True, help_text='Estimated or known installation date', null=True, verbose_name='Install Date'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='last_seen_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this software was last detected on the asset', null=True, verbose_name='Last Seen Date'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes specific to this installation', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_instances', to='software.software', verbose_name='Software'),
        ),
        migrations.AlterField(
            model_name='installedsoftware',
            name='version_detected',
            field=models.CharField(blank=True, help_text='Specific version discovered on the asset (e.g., 16.78.1)', max_length=100, verbose_name='Version Detected'),
        ),
        migrations.AlterField(
            model_name='software',
            name='category',
            field=models.CharField(blank=True, choices=[('operating_system', 'Operating System'), ('productivity', 'Productivity'), ('development', 'Development'), ('security', 'Security'), ('design', 'Design'), ('other', 'Other')], db_index=True, help_text='Functional category', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the software product.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_type',
            field=models.CharField(blank=True, choices=[('proprietary', 'Proprietary'), ('open_source', 'Open Source'), ('freeware', 'Freeware'), ('shareware', 'Shareware'), ('subscription', 'Subscription')], help_text='Default license type', max_length=50, verbose_name='License Type'),
        ),
        migrations.AlterField(
            model_name='software',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_products', to='assets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(help_text='Name of the software product (e.g., Microsoft Visio Professional 2021). Unique per tenant.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='software',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='software', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='software',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. Null denotes a shared/global catalogue entry visible to all tenants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, help_text='Current version (e.g., 2021, 16.0)', max_length=50, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='software',
            name='website',
            field=models.URLField(blank=True, help_text='Product homepage or vendor URL', verbose_name='Website'),
        ),
    ]
