# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('software', '0007_installedsoftware'),
    ]

    dependencies = [
        ('procurement', '0100_issue88_shard_27_procurement_history_1'),
        ('software', '0100_issue88_shard_09_software_schema'),
    ]

    operations = [

    ]
