# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('software', '0008_repoint_installedsoftware_contenttype'),
        ('software', '0009_software_tenant_alter_software_name_and_more'),
        ('software', '0010_alter_installedsoftware_asset_and_more'),
    ]

    dependencies = [
        ('compliance', '0100_issue88_shard_44_compliance_relations'),
        ('software', '0100_issue88_shard_28_software_history_1'),
    ]

    operations = [
        migrations.AddConstraint(
                    model_name='software',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'name'), name='unique_tenant_software_name'),
                ),
        migrations.AddConstraint(
                    model_name='software',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', True)), fields=('name',), name='unique_global_software_name'),
                ),
        migrations.AddConstraint(
                    model_name='installedsoftware',
                    constraint=models.UniqueConstraint(fields=('asset', 'software', 'version_detected'), name='unique_asset_software_version'),
                ),
    ]
