# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('software', '0001_initial'),
        ('software', '0002_software_tenant_alter_software_name_and_more'),
        ('software', '0003_alter_software_unique_together_alter_software_name_and_more'),
        ('software', '0004_software_deleted_at'),
        ('software', '0005_alter_software_deleted_at'),
        ('software', '0006_software_custom_field_data'),
    ]

    dependencies = [
        ('core', '0100_issue88_shard_08_core_schema'),
    ]

    operations = [
        migrations.CreateModel(
                    name='Software',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Name of the software product (e.g., Microsoft Visio Professional 2021). Unique per tenant.', max_length=255, verbose_name='Name')),
                        ('version', models.CharField(blank=True, help_text='Current version (e.g., 2021, 16.0)', max_length=50, verbose_name='Version')),
                        ('category', models.CharField(blank=True, choices=[('operating_system', 'Operating System'), ('productivity', 'Productivity'), ('development', 'Development'), ('security', 'Security'), ('design', 'Design'), ('other', 'Other')], db_index=True, help_text='Functional category', max_length=50, verbose_name='Category')),
                        ('license_type', models.CharField(blank=True, choices=[('proprietary', 'Proprietary'), ('open_source', 'Open Source'), ('freeware', 'Freeware'), ('shareware', 'Shareware'), ('subscription', 'Subscription')], help_text='Default license type', max_length=50, verbose_name='License Type')),
                        ('website', models.URLField(blank=True, help_text='Product homepage or vendor URL', verbose_name='Website')),
                        ('description', models.TextField(blank=True, help_text='Optional description of the software product.', verbose_name='Description')),
                        ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_products', to='assets.manufacturer', verbose_name='Manufacturer')),
                        ('tags', models.ManyToManyField(blank=True, related_name='software', to='extras.tag', verbose_name='Tags')),
                        ('tenant', models.ForeignKey(blank=True, help_text='Owning tenant. Null denotes a shared/global catalogue entry visible to all tenants.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software', to='organization.tenant', verbose_name='Tenant')),
                    ],
                    options={
                        'verbose_name': 'Software',
                        'verbose_name_plural': 'Software',
                        'ordering': ('manufacturer', 'name'),
                    },
                    bases=(core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='InstalledSoftware',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('version_detected', models.CharField(blank=True, help_text='Specific version discovered on the asset (e.g., 16.78.1)', max_length=100, verbose_name='Version Detected')),
                        ('install_date', models.DateField(blank=True, db_index=True, help_text='Estimated or known installation date', null=True, verbose_name='Install Date')),
                        ('discovered_by_agent', models.CharField(blank=True, help_text='Identifier for the discovery source or agent (e.g., SCCM, Intune, Lansweeper)', max_length=100, verbose_name='Discovered By')),
                        ('last_seen_date', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when this software was last detected on the asset', null=True, verbose_name='Last Seen Date')),
                        ('notes', models.TextField(blank=True, help_text='Optional notes specific to this installation', verbose_name='Notes')),
                        ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='assets.asset', verbose_name='Asset')),
                        ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_instances', to='software.software', verbose_name='Software')),
                    ],
                    options={
                        'verbose_name': 'Installed Software Instance',
                        'verbose_name_plural': 'Installed Software Instances',
                        'ordering': ['asset', 'software', '-last_seen_date'],
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
