# Generated by Django 5.2.17 on 2026-10-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0123_asset_archive_leaf_markers"),
        ("software", "0100_issue88_shard_45_software_relations"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="installedsoftware",
            name="unique_asset_software_version",
        ),
        migrations.AddField(
            model_name="installedsoftware",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="installedsoftware",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="installedsoftware",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("asset", "software", "version_detected"),
                name="unique_asset_software_version",
            ),
        ),
    ]
