# Generated by Django 5.2 on 2026-05-29 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_seed_status_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='checked_out_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
