# Generated by Django 5.2 on 2026-05-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assettype_custom_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='ram_gb',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='storage_capacity_gb',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='storage_type',
        ),
    ]
