# Generated by Django 5.2 on 2026-06-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_assettype_cpu_remove_assettype_gpu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetrole',
            options={'verbose_name': 'Asset Role', 'verbose_name_plural': 'Asset Roles'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
