# Generated by Django 5.2 on 2026-06-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_category_custody_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='asset_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.assetrole', verbose_name='Asset Role'),
        ),
    ]
