# Generated by Django 5.2.15 on 2026-06-05 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assettype_asset_role'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0008_alter_assetholder_tenant_alter_location_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettagsequence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The asset category this sequence applies to. Null represents default sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='assets.category'),
        ),
        migrations.AddField(
            model_name='assettagsequence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assettagsequence',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this sequence. Null represents system-wide/global sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='organization.tenant'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='prefix',
            field=models.CharField(default='ASSET-', help_text='Prefix for generated asset tags (e.g. ASSET-)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'asset_tag'), name='unique_tenant_asset_tag'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('asset_tag',), name='unique_global_asset_tag'),
        ),
        migrations.AddConstraint(
            model_name='assettagsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'prefix'), name='unique_tenant_prefix'),
        ),
        migrations.AddConstraint(
            model_name='assettagsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('prefix',), name='unique_global_prefix'),
        ),
    ]
