# Generated by Django 5.2.15 on 2026-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_assettagsequence_category_assettagsequence_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
