# Generated by Django 5.2.15 on 2026-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_alter_asset_asset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='model_level',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this field defines a hardware specification on the Asset Type (e.g. CPU, RAM) rather than a device-specific instance detail (e.g. Hostname, OS version).', verbose_name='Model Level / Specification'),
        ),
    ]
