# Generated by Django 5.2.15 on 2026-06-05 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_customfield_model_level'),
        ('extras', '0004_alter_configcontext_options_alter_dashboard_options_and_more'),
        ('organization', '0009_alter_tenantmembership_unique_together_and_more'),
        ('software', '0003_alter_software_unique_together_alter_software_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetaudit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assettype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='installedsoftware',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assetaudit',
            constraint=models.UniqueConstraint(fields=('session', 'asset'), name='unique_session_asset'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model'), name='unique_manufacturer_model'),
        ),
        migrations.AddConstraint(
            model_name='installedsoftware',
            constraint=models.UniqueConstraint(fields=('asset', 'software', 'version_detected'), name='unique_asset_software_version'),
        ),
    ]
