# Generated by Django 5.2.15 on 2026-06-07 11:20

from django.db import migrations, models


def make_existing_assets_inherit_requestable(apps, schema_editor):
    Asset = apps.get_model('assets', 'Asset')
    Asset.objects.filter(requestable=False).update(requestable=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_assetrequest_deleted_at_assetrole_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='requestable',
            field=models.BooleanField(blank=True, db_index=True, default=None, help_text='Allow users to request this asset', null=True),
        ),
        migrations.RunPython(make_existing_assets_inherit_requestable, reverse_code=migrations.RunPython.noop),
    ]
