# Generated by Django 5.2.15 on 2026-06-07 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_alter_asset_requestable'),
        ('extras', '0005_tag_deleted_at'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_requests_for', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='organization.location'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='organization.assetholder'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='organization.tenant'),
        ),
        migrations.AddConstraint(
            model_name='assetrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', True), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', False), ('assigned_location__isnull', True), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', False), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', True), ('assigned_asset__isnull', False)), _connector='OR'), name='at_most_one_request_target'),
        ),
    ]
