# Generated by Django 5.2.15 on 2026-06-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_assetrequest_assigned_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'ordering': ['-request_date'], 'permissions': [('add_delegated_assetrequest', 'Can request assets on behalf of others')], 'verbose_name': 'Asset Request', 'verbose_name_plural': 'Asset Requests'},
        ),
    ]
