# Generated by Django 5.2.15 on 2026-06-07 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_alter_assetrequest_options'),
        ('extras', '0005_tag_deleted_at'),
        ('inventory', '0003_alter_component_tags_alter_component_tenant_and_more'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.accessory'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.component'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.consumable'),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='assetrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', True), ('accessory__isnull', True), ('consumable__isnull', True), models.Q(('asset__isnull', False), ('asset_type__isnull', False), _connector='OR')), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', False), ('accessory__isnull', True), ('consumable__isnull', True)), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('accessory__isnull', False), ('consumable__isnull', True)), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('accessory__isnull', True), ('consumable__isnull', False)), _connector='OR'), name='exactly_one_requested_category'),
        ),
    ]
