# Generated by Django 5.2.15 on 2026-06-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assetrequest_accessory_assetrequest_component_and_more'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='organization.location'),
        ),
    ]
