# Generated by Django 5.2.15 on 2026-06-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_assetrequest_source_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='is_group',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests', to='assets.assetrequest'),
        ),
    ]
