# Generated by Django 5.2.15 on 2026-06-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_asset_purchase_order_line_alter_assetrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'ordering': ['-request_date'], 'permissions': [('add_delegated_assetrequest', 'Can request assets on behalf of others'), ('approve_assetrequest', 'Can approve asset requests'), ('fulfill_assetrequest', 'Can fulfill/claim asset requests')], 'verbose_name': 'Asset Request', 'verbose_name_plural': 'Asset Requests'},
        ),
    ]
