# Generated by Django 5.2.15 on 2026-06-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_alter_assetrequest_options'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assignments', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.assetholder'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests_for', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.location'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.assetholder'),
        ),
    ]
