# Generated by Django 5.2.15 on 2026-06-07 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_assetassignment_assigned_asset_and_more'),
        ('extras', '0005_tag_deleted_at'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetassignment',
            name='exactly_one_assignment_target',
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', True), ('assigned_user__isnull', False)), models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', False), ('assigned_user__isnull', True)), models.Q(('assigned_asset__isnull', False), ('assigned_location__isnull', True), ('assigned_user__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', True), ('assigned_user__isnull', True)), _connector='OR'), name='exactly_one_assignment_target'),
        ),
    ]
