# Generated by Django 5.2.15 on 2026-06-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_alter_assetrole_name_alter_assetrole_slug_and_more'),
        ('extras', '0007_alter_tag_name_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assettype',
            name='unique_manufacturer_model',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetrole'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='type',
            field=models.CharField(choices=[('pending', 'Pending'), ('deployable', 'Deployable'), ('deployed', 'Deployed'), ('undeployable', 'Undeployable'), ('archived', 'Archived')], db_index=True, default='deployable', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'model'), name='unique_manufacturer_model_active'),
        ),
    ]
