# Generated by Django 5.2.15 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_rename_custom_values_to_custom_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
    ]
