# Generated by Django 5.2.15 on 2026-06-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_null_to_empty_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audit_interval_months',
            field=models.PositiveIntegerField(blank=True, help_text='How often assets in this category must be physically audited, in months. Leave blank for no required cadence.', null=True),
        ),
    ]
