# Generated by Django 5.2.15 on 2026-06-11 05:23

from django.db import migrations, models
from django.db.models import Q


def backfill_allows_components(apps, schema_editor):
    """Set allows_components=True for roles that matched the old slug heuristic."""
    AssetRole = apps.get_model('assets', 'AssetRole')
    AssetRole.objects.filter(
        Q(slug__icontains='server') |
        Q(slug__icontains='modular') |
        Q(slug__icontains='workstation') |
        Q(slug__icontains='hypervisor')
    ).update(allows_components=True)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_seed_depreciation_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrole',
            name='allows_components',
            field=models.BooleanField(default=False, help_text='Assets with this role can have components allocated (servers, workstations, …)'),
        ),
        migrations.RunPython(backfill_allows_components, migrations.RunPython.noop),
    ]
