# Generated by Django 5.2.15 on 2026-06-14 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0044_assetrole_allows_components'),
        ('extras', '0031_eventrule_deleted_at_eventrule_tenant_and_more'),
        ('organization', '0016_currency_callable_default'),
        ('procurement', '0008_alter_purchaseorder_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('serial_number', ''), _negated=True)), fields=('tenant', 'serial_number'), name='uniq_active_tenant_serial'),
        ),
    ]
