# Generated by Django 5.2.15 on 2026-06-14 14:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0046_asset_currency_assetmaintenance_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disposal_method', models.CharField(choices=[('resale', 'Resale'), ('recycle', 'Recycle / WEEE'), ('donation', 'Donation'), ('destruction', 'Physical Destruction'), ('return_to_lessor', 'Return to Lessor'), ('other', 'Other')], db_index=True, default='destruction', max_length=30, verbose_name='Disposal Method')),
                ('disposal_date', models.DateField(db_index=True, verbose_name='Disposal Date')),
                ('data_sanitization_method', models.CharField(choices=[('none', 'None / Not Applicable'), ('nist_clear', 'NIST Clear (overwrite)'), ('nist_purge', 'NIST Purge (cryptographic or ATA Secure Erase)'), ('nist_destroy', 'NIST Destroy (media destruction)'), ('dod_3pass', 'DoD 5220.22-M 3-Pass'), ('degauss', 'Degaussing'), ('physical_destruction', 'Physical Destruction (shred/crush)'), ('crypto_erase', 'Cryptographic Erase')], db_index=True, default='none', help_text='NIST SP 800-88 Rev.1 aligned method used to sanitize storage media.', max_length=30, verbose_name='Data Sanitization Method')),
                ('sanitization_certificate', models.CharField(blank=True, help_text='Certificate serial number or reference ID from the sanitization vendor.', max_length=255, verbose_name='Sanitization Certificate / Reference')),
                ('sanitized_by', models.CharField(blank=True, help_text='Person or vendor who performed the data sanitization.', max_length=255, verbose_name='Sanitized By')),
                ('recipient', models.CharField(blank=True, help_text='Buyer, recycler, charity, or other recipient of the disposed asset.', max_length=255, verbose_name='Recipient')),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Amount received for the asset (resale / salvage). Leave blank if none.', max_digits=12, null=True, verbose_name='Proceeds')),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                ('weee_compliant', models.BooleanField(default=False, help_text='Disposal was carried out by an authorised WEEE recycler.', verbose_name='WEEE Compliant')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='assets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'ordering': ['-disposal_date'],
                'permissions': [('dispose_asset', 'Can record asset disposal / end-of-life')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
