# Generated by Django 5.2.15 on 2026-06-14 16:16

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0047_assetdisposal'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiration',
        ),
        migrations.AddField(
            model_name='asset',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.costcenter', verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Mandatory return date for loaner assets.', null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='is_loan',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this assignment as a temporary loan with a mandatory return date.', verbose_name='Is Loan'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='returned_at',
            field=models.DateField(blank=True, help_text='Date the loaned asset was physically returned.', null=True, verbose_name='Returned At'),
        ),
        migrations.CreateModel(
            name='AssetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Purpose')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.asset', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_reservations', to='organization.assetholder', verbose_name='Reserved For')),
            ],
            options={
                'verbose_name': 'Asset Reservation',
                'verbose_name_plural': 'Asset Reservations',
                'ordering': ['start_date'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warranty_type', models.CharField(choices=[('hardware', 'Hardware'), ('parts_labor', 'Parts & Labor'), ('onsite', 'On-site'), ('accidental', 'Accidental Damage'), ('extended', 'Extended'), ('full', 'Full Coverage')], db_index=True, default='hardware', max_length=30, verbose_name='Warranty Type')),
                ('provider', models.CharField(blank=True, help_text='e.g. "Dell ProSupport Plus"', max_length=255, verbose_name='Provider')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cost')),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                ('reference', models.CharField(blank=True, help_text='Claim number, policy reference, or contract ID.', max_length=255, verbose_name='Reference')),
                ('terms', models.TextField(blank=True, verbose_name='Terms')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='assets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'ordering': ['end_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='warranty_end_date_gte_start_date')],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
    ]
