# Generated by Django 5.2.15 on 2026-06-14 17:43

from django.db import migrations


def migrate_supplier_contacts(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContactRole = apps.get_model('organization', 'ContactRole')
    Contact = apps.get_model('organization', 'Contact')
    ContactAssignment = apps.get_model('organization', 'ContactAssignment')
    Supplier = apps.get_model('assets', 'Supplier')
    supplier_ct, _ = ContentType.objects.get_or_create(app_label='assets', model='supplier')
    primary_role, _ = ContactRole.objects.get_or_create(
        slug='primary-contact',
        defaults={'name': 'Primary Contact', 'description': 'Primary Contact'},
    )
    for supplier in Supplier.objects.all():
        if supplier.contact_name or supplier.contact_email or supplier.contact_phone:
            contact = Contact.objects.create(
                name=supplier.contact_name or f"{supplier.name} Contact",
                phone=supplier.contact_phone or "",
                email=supplier.contact_email or "",
                web_url=supplier.website or "",
            )
            ContactAssignment.objects.create(
                contact=contact,
                role=primary_role,
                content_type=supplier_ct,
                object_id=supplier.pk,
                priority='primary',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0048_remove_asset_warranty_expiration_asset_cost_center_and_more'),
        ('organization', '0018_costcenter'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(migrate_supplier_contacts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_phone',
        ),
    ]
