# Generated by Django 5.2.15 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0049_supplier_contacts_unification'),
        ('organization', '0018_costcenter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assettagsequence',
            name='unique_tenant_prefix',
        ),
        migrations.RemoveConstraint(
            model_name='assettagsequence',
            name='unique_global_prefix',
        ),
        migrations.AddConstraint(
            model_name='assettagsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'prefix'), name='unique_tenant_prefix'),
        ),
        migrations.AddConstraint(
            model_name='assettagsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('deleted_at__isnull', True)), fields=('prefix',), name='unique_global_prefix'),
        ),
    ]
