# Generated by Django 5.2.15 on 2026-06-16 12:07

import assets.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0050_remove_assettagsequence_unique_tenant_prefix_and_more'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The exclusion constraint below mixes '=' (asset) with '&&' (daterange
        # overlap); Postgres needs the btree_gist operator class for the equality
        # part inside a GiST exclusion constraint. Enable it before AddConstraint.
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='assetreservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['active', 'pending']), ('deleted_at__isnull', True)), expressions=[('asset', '='), (assets.models.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=False)), '&&')], name='assetreservation_no_overlap'),
        ),
    ]
