# Generated by Django 5.2.15 on 2026-06-17 17:59

import assets.models.lifecycle
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0051_assetreservation_assetreservation_no_overlap'),
        ('organization', '0018_costcenter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetreservation',
            name='assetreservation_no_overlap',
        ),
        migrations.AddConstraint(
            model_name='assetreservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['active', 'pending']), ('deleted_at__isnull', True)), expressions=[('asset', '='), (assets.models.lifecycle.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='assetreservation_no_overlap'),
        ),
    ]
