# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0052_remove_assetreservation_assetreservation_no_overlap_and_more'),
        ('extras', '0034_journalentry_tenant'),
        ('inventory', '0009_alter_component_tags'),
        ('organization', '0018_costcenter'),
        ('procurement', '0011_contract_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetrole', verbose_name='Asset Role'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype', verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_book_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Materialized depreciation value', max_digits=10, null=True, verbose_name='Current Book Value'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Depreciation Updated At'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='procurement.purchaseorderline', verbose_name='Purchase Order Line'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='requestable',
            field=models.BooleanField(blank=True, db_index=True, default=None, help_text='Allow users to request this asset', null=True, verbose_name='Requestable'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.statuslabel', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assignments', to='assets.asset', verbose_name='Assigned Asset'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.assetholder', verbose_name='Assigned User'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked In At'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='checked_out_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Checked Out At'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL, verbose_name='Checked Out By'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='expected_checkin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Checkin Date'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='pre_checkout_status',
            field=models.ForeignKey(blank=True, help_text='Preserved status label to revert to upon checkin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_pre_checkouts', to='assets.statuslabel', verbose_name='Pre-checkout Status'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_assignments', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='performed_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Performed By'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_maintenances', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='title',
            field=models.CharField(default='Maintenance', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.accessory', verbose_name='Accessory'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.assettype', verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests_for', to='assets.asset', verbose_name='Assigned Asset'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.assetholder', verbose_name='Assigned User'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.component', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.consumable', verbose_name='Consumable'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='is_group',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Group'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests', to='assets.assetrequest', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responded By'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Response Date'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='response_notes',
            field=models.TextField(blank=True, verbose_name='Response Notes'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='organization.location', verbose_name='Source Location'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('procurement', 'Awaiting Procurement'), ('denied', 'Denied'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_requests_tagged', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='allows_components',
            field=models.BooleanField(default=False, help_text='Assets with this role can have components allocated (servers, workstations, …)', verbose_name='Allows Components'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='color',
            field=models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='assetrole',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_roles', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The asset category this sequence applies to. Null represents default sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='assets.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='next_value',
            field=models.PositiveIntegerField(default=1, verbose_name='Next Value'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='prefix',
            field=models.CharField(default='ASSET-', help_text='Prefix for generated asset tags (e.g. ASSET-)', max_length=20, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant owning this sequence. Null represents system-wide/global sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='assettagsequence',
            name='zero_padding',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Zero Padding'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='model',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Manufacturer part number or SKU', max_length=100, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='requestable',
            field=models.BooleanField(db_index=True, default=False, help_text='Allow users to request assets of this type', verbose_name='Requestable'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='asset_types', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='category',
            name='applies_to',
            field=models.JSONField(blank=True, default=dict, help_text="Applies to: {'asset': True, 'accessory': True, 'component': True}", verbose_name='Applies To'),
        ),
        migrations.AlterField(
            model_name='category',
            name='audit_interval_months',
            field=models.PositiveIntegerField(blank=True, help_text='How often assets in this category must be physically audited, in months. Leave blank for no required cadence.', null=True, verbose_name='Audit Interval (Months)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='color',
            field=models.CharField(blank=True, help_text='RGB color in hexadecimal (e.g. 00ff00)', max_length=6, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='status_labels_tagged', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='statuslabel',
            name='type',
            field=models.CharField(choices=[('pending', 'Pending'), ('deployable', 'Deployable'), ('deployed', 'Deployed'), ('undeployable', 'Undeployable'), ('archived', 'Archived'), ('in_repair', 'In Repair'), ('on_order', 'On Order')], db_index=True, default='deployable', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='Website'),
        ),
    ]
