# Generated by Django 5.2.15 on 2026-06-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmaintenance',
            name='title',
        ),
    ]
