# Generated by Django 5.2.15 on 2026-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0054_remove_assetmaintenance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN / UPC / GTIN) — scanning shows assets of this type.', max_length=14, verbose_name='EAN'),
        ),
    ]
