# Generated by Django 5.2.15 on 2026-06-20 20:53

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0055_assettype_ean'),
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetassignment',
            name='unique_active_assignment_per_asset',
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='proceeds',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount received for the asset (resale / salvage). Leave blank if none.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proceeds'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('deleted_at__isnull', True)), fields=('asset',), name='unique_active_assignment_per_asset'),
        ),
    ]
