# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0036_remove_installedsoftware'),
        ('assets', '0037_remove_auditsession_created_by_and_more'),
    ]

    dependencies = [
        ('software', '0100_issue88_shard_28_software_history_1'),
        ('assets', '0100_issue88_shard_17_assets_history_4'),
    ]

    operations = [

    ]
