# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0002_initial'),
        ('assets', '0003_seed_status_labels'),
        ('assets', '0004_alter_assetassignment_checked_out_at'),
        ('assets', '0005_auditsession_assetaudit'),
        ('assets', '0006_alter_assetaudit_options_alter_auditsession_options_and_more'),
        ('assets', '0007_assettype_custom_values'),
        ('assets', '0008_remove_assettype_cpu_remove_assettype_gpu_and_more'),
        ('assets', '0009_alter_asset_options_alter_assetrole_options_and_more'),
        ('assets', '0010_remove_assetassignment_assets_asse_assigne_b44734_idx_and_more'),
        ('assets', '0011_alter_assetassignment_assigned_asset'),
        ('assets', '0012_category_custody_template'),
        ('assets', '0013_remove_category_custody_template_and_more'),
        ('assets', '0014_assettype_asset_role'),
        ('assets', '0015_assettagsequence_category_assettagsequence_is_active_and_more'),
        ('assets', '0016_alter_asset_asset_tag'),
        ('assets', '0017_customfield_model_level'),
        ('assets', '0018_alter_assetaudit_unique_together_and_more'),
        ('assets', '0019_assetrequest_deleted_at_assetrole_deleted_at_and_more'),
        ('assets', '0020_alter_asset_requestable'),
        ('assets', '0021_assetrequest_assigned_asset_and_more'),
        ('assets', '0022_alter_assetrequest_options'),
    ]

    dependencies = [
        ('software', '0100_issue88_shard_09_software_schema'),
        ('assets', '0100_issue88_shard_02_assets_schema'),
    ]

    operations = [

    ]
