# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0033_remove_customfieldset_fields_and_more'),
        ('assets', '0034_rename_custom_values_to_custom_field_data'),
        ('assets', '0035_supplier_custom_field_data'),
    ]

    dependencies = [
        ('extras', '0100_issue88_shard_16_extras_history_2'),
        ('assets', '0100_issue88_shard_15_assets_history_3'),
    ]

    operations = [

    ]
