# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations

STATUS_LABELS = (
    ("Available", "available", "deployable", "28a745"),
    ("In Use", "in-use", "deployed", "007bff"),
    ("Pending Repair", "pending-repair", "pending", "ffc107"),
    ("Retired", "retired", "archived", "dc3545"),
    ("In Transit", "in-transit", "pending", "6f42c1"),
    ("Decommissioned", "decommissioned", "undeployable", "6c757d"),
    ("Quarantined", "quarantined", "pending", "fd7e14"),
)

DEPRECIATION_POLICIES = (
    {
        "name": "IT-Hardware 36 Monate (AfA)",
        "months": 36,
        "method": "straight_line",
        "convention": "include_purchase_month",
        "description": "AfA-Tabelle 2021 — Computer, Notebooks, Tablets: 3 Jahre",
    },
    {
        "name": "Server 60 Monate (AfA)",
        "months": 60,
        "method": "straight_line",
        "convention": "include_purchase_month",
        "description": "AfA-Tabelle 2021 — Server / Workstations: 5 Jahre",
    },
    {
        "name": "Sofortabschreibung GWG (≤ 800 €)",
        "months": 1,
        "method": "straight_line",
        "convention": "include_purchase_month",
        "immediate_expense_threshold": "800.00",
        "description": "Geringwertige Wirtschaftsgüter §6 Abs. 2 EStG — Sofortabschreibung bis 800 €",
    },
)


def seed_required_asset_data(apps, schema_editor):
    status_label = apps.get_model("assets", "StatusLabel")
    for name, slug, status_type, color in STATUS_LABELS:
        status_label.objects.update_or_create(
            slug=slug,
            defaults={"name": name, "type": status_type, "color": color},
        )

    depreciation = apps.get_model("assets", "Depreciation")
    for policy in DEPRECIATION_POLICIES:
        depreciation.objects.update_or_create(
            name=policy["name"],
            defaults={key: value for key, value in policy.items() if key != "name"},
        )


def unseed_required_asset_data(apps, schema_editor):
    apps.get_model("assets", "StatusLabel").objects.filter(
        slug__in=[item[1] for item in STATUS_LABELS]
    ).delete()
    apps.get_model("assets", "Depreciation").objects.filter(
        name__in=[item["name"] for item in DEPRECIATION_POLICIES]
    ).delete()


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0056_remove_assetassignment_unique_active_assignment_per_asset_and_more'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_42_assets_relations'),
    ]

    operations = [
        migrations.RunPython(seed_required_asset_data, unseed_required_asset_data),
    ]
