# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0023_assetrequest_accessory_assetrequest_component_and_more'),
        ('assets', '0024_assetrequest_source_location'),
        ('assets', '0025_assetrequest_is_group_assetrequest_parent'),
    ]

    dependencies = [
        ('inventory', '0100_issue88_shard_12_inventory_schema'),
        ('assets', '0100_issue88_shard_10_assets_history_1'),
    ]

    operations = [

    ]
