# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0038_assetmaintenance'),
        ('assets', '0039_repoint_assetmaintenance_contenttype'),
        ('assets', '0040_null_to_empty_strings'),
        ('assets', '0041_category_audit_interval_months'),
        ('assets', '0042_depreciation_v2'),
        ('assets', '0043_seed_depreciation_policies'),
        ('assets', '0044_assetrole_allows_components'),
    ]

    dependencies = [
        ('compliance', '0100_issue88_shard_30_compliance_history_1'),
        ('assets', '0100_issue88_shard_29_assets_history_5'),
    ]

    operations = [

    ]
