# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0045_asset_uniq_active_tenant_serial'),
        ('assets', '0046_asset_currency_assetmaintenance_currency_and_more'),
        ('assets', '0047_assetdisposal'),
        ('assets', '0048_remove_asset_warranty_expiration_asset_cost_center_and_more'),
        ('assets', '0049_supplier_contacts_unification'),
        ('assets', '0050_remove_assettagsequence_unique_tenant_prefix_and_more'),
        ('assets', '0051_assetreservation_assetreservation_no_overlap'),
        ('assets', '0052_remove_assetreservation_assetreservation_no_overlap_and_more'),
    ]

    dependencies = [
        ('organization', '0100_issue88_shard_35_organization_history_3'),
        ('assets', '0100_issue88_shard_31_assets_history_6'),
    ]

    operations = [

    ]
