# Generated by Django 5.2.16 for ITAMbox issue #88.

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0026_asset_purchase_order_line_alter_assetrequest_status'),
        ('assets', '0027_alter_assetrequest_options'),
        ('assets', '0028_alter_assetassignment_assigned_asset_and_more'),
        ('assets', '0029_remove_assetassignment_exactly_one_assignment_target_and_more'),
        ('assets', '0030_assetassignment_deleted_at_alter_asset_deleted_at_and_more'),
        ('assets', '0031_alter_assetrole_name_alter_assetrole_slug_and_more'),
        ('assets', '0032_remove_assettype_unique_manufacturer_model_and_more'),
    ]

    dependencies = [
        ('procurement', '0100_issue88_shard_14_procurement_schema'),
        ('assets', '0100_issue88_shard_13_assets_history_2'),
    ]

    operations = [

    ]
