# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion
import assets.models.lifecycle
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension


class Migration(migrations.Migration):

    replaces = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('assets', '0054_remove_assetmaintenance_title'),
        ('assets', '0055_assettype_ean'),
    ]

    dependencies = [
        ('procurement', '0100_issue88_shard_41_procurement_history_2'),
        ('assets', '0100_issue88_shard_36_assets_history_7'),
    ]

    operations = [
        migrations.AddField(
                    model_name='asset',
                    name='cost_center',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.costcenter', verbose_name='Cost Center'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='last_audited_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_assets', to=settings.AUTH_USER_MODEL, verbose_name='Last Audited By'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='organization.location', verbose_name='Location'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='purchase_order_line',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='procurement.purchaseorderline', verbose_name='Purchase Order Line'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='assets', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='asset',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='assigned_asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assignments', to='assets.asset', verbose_name='Assigned Asset'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='assigned_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.location', verbose_name='Assigned Location'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='assigned_user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='organization.assetholder', verbose_name='Assigned User'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='checked_in_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='Checked In By'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='checked_out_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL, verbose_name='Checked Out By'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='asset_assignments', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetdisposal',
                    name='asset',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='assetmaintenance',
                    name='asset',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='assetmaintenance',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='asset_maintenances', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='accessory',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.accessory', verbose_name='Accessory'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='assigned_asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests_for', to='assets.asset', verbose_name='Assigned Asset'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='assigned_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.location', verbose_name='Assigned Location'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='assigned_user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_requests', to='organization.assetholder', verbose_name='Assigned User'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='component',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.component', verbose_name='Component'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='consumable',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.consumable', verbose_name='Consumable'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='parent',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests', to='assets.assetrequest', verbose_name='Parent'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='requester',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='responded_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_request_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responded By'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='source_location',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='organization.location', verbose_name='Source Location'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='asset_requests_tagged', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='assetreservation',
                    name='asset',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='assetreservation',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
                ),
        migrations.AddField(
                    model_name='assetreservation',
                    name='reserved_for',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_reservations', to='organization.assetholder', verbose_name='Reserved For'),
                ),
        migrations.AddField(
                    model_name='assetrole',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='asset_roles', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='asset_role',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetrole', verbose_name='Asset Role'),
                ),
        migrations.AddField(
                    model_name='assettagsequence',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='The tenant owning this sequence. Null represents system-wide/global sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='asset_role',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.assetrole', verbose_name='Asset Role'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='custom_fieldset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='extras.customfieldset', verbose_name='Custom Fieldset'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='asset_types', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetrequest',
                    name='asset_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='assets.assettype', verbose_name='Asset Type'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='asset_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assettype', verbose_name='Asset Type'),
                ),
        migrations.AddField(
                    model_name='category',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='categories', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.category', verbose_name='Category'),
                ),
        migrations.AddField(
                    model_name='assettagsequence',
                    name='category',
                    field=models.ForeignKey(blank=True, help_text='The asset category this sequence applies to. Null represents default sequences.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_sequences', to='assets.category', verbose_name='Category'),
                ),
        migrations.AddConstraint(
                    model_name='depreciation',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_depreciation_name_active'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='depreciation',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_types', to='assets.depreciation', verbose_name='Depreciation'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='depreciation_override',
                    field=models.ForeignKey(blank=True, help_text='Override depreciation policy — leave empty to use the tenant default or asset-type schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_overrides', to='assets.depreciation', verbose_name='Depreciation override'),
                ),
        migrations.AddField(
                    model_name='manufacturer',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='manufacturers', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assettype',
                    name='manufacturer',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.manufacturer', verbose_name='Manufacturer'),
                ),
        migrations.AddField(
                    model_name='statuslabel',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='status_labels_tagged', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetassignment',
                    name='pre_checkout_status',
                    field=models.ForeignKey(blank=True, help_text='Preserved status label to revert to upon checkin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_pre_checkouts', to='assets.statuslabel', verbose_name='Pre-checkout Status'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='status',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.statuslabel', verbose_name='Status'),
                ),
        migrations.AddField(
                    model_name='supplier',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='suppliers', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='assetmaintenance',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='Supplier/Vendor'),
                ),
        migrations.AddField(
                    model_name='asset',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.supplier', verbose_name='Supplier'),
                ),
        migrations.AddField(
                    model_name='warranty',
                    name='asset',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='assets.asset', verbose_name='Asset'),
                ),
        BtreeGistExtension(),
        migrations.AddConstraint(
                    model_name='assetreservation',
                    constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['active', 'pending']), ('deleted_at__isnull', True)), expressions=[('asset', '='), (assets.models.lifecycle.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&')], name='assetreservation_no_overlap'),
                ),
        migrations.AddConstraint(
                    model_name='assetrole',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_assetrole_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='assetrole',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_assetrole_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='assetrequest',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', True), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', False), ('assigned_location__isnull', True), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', False), ('assigned_asset__isnull', True)), models.Q(('assigned_user__isnull', True), ('assigned_location__isnull', True), ('assigned_asset__isnull', False)), _connector='OR'), name='at_most_one_request_target'),
                ),
        migrations.AddConstraint(
                    model_name='assetrequest',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', True), ('accessory__isnull', True), ('consumable__isnull', True), models.Q(('asset__isnull', False), ('asset_type__isnull', False), _connector='OR')), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', False), ('accessory__isnull', True), ('consumable__isnull', True)), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('accessory__isnull', False), ('consumable__isnull', True)), models.Q(('asset__isnull', True), ('asset_type__isnull', True), ('component__isnull', True), ('accessory__isnull', True), ('consumable__isnull', False)), _connector='OR'), name='exactly_one_requested_category'),
                ),
        migrations.AddConstraint(
                    model_name='category',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_category_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='category',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_category_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='assettagsequence',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False), ('deleted_at__isnull', True)), fields=('tenant', 'prefix'), name='unique_tenant_prefix'),
                ),
        migrations.AddConstraint(
                    model_name='assettagsequence',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True), ('deleted_at__isnull', True)), fields=('prefix',), name='unique_global_prefix'),
                ),
        migrations.AddConstraint(
                    model_name='manufacturer',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_manufacturer_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='manufacturer',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_manufacturer_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='assettype',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('manufacturer', 'model'), name='unique_manufacturer_model_active'),
                ),
        migrations.AddConstraint(
                    model_name='assettype',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_assettype_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='statuslabel',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_statuslabel_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='statuslabel',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_statuslabel_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='assetassignment',
                    constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('deleted_at__isnull', True)), fields=('asset',), name='unique_active_assignment_per_asset'),
                ),
        migrations.AddConstraint(
                    model_name='assetassignment',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', True), ('assigned_user__isnull', False)), models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', False), ('assigned_user__isnull', True)), models.Q(('assigned_asset__isnull', False), ('assigned_location__isnull', True), ('assigned_user__isnull', True)), models.Q(('assigned_asset__isnull', True), ('assigned_location__isnull', True), ('assigned_user__isnull', True)), _connector='OR'), name='exactly_one_assignment_target'),
                ),
        migrations.AddConstraint(
                    model_name='supplier',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_supplier_name_active'),
                ),
        migrations.AddConstraint(
                    model_name='supplier',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_supplier_slug_active'),
                ),
        migrations.AddConstraint(
                    model_name='asset',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'asset_tag'), name='unique_tenant_asset_tag'),
                ),
        migrations.AddConstraint(
                    model_name='asset',
                    constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('asset_tag',), name='unique_global_asset_tag'),
                ),
        migrations.AddConstraint(
                    model_name='asset',
                    constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('serial_number', ''), _negated=True)), fields=('tenant', 'serial_number'), name='uniq_active_tenant_serial'),
                ),
        migrations.AddConstraint(
                    model_name='warranty',
                    constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='warranty_end_date_gte_start_date'),
                ),
    ]
