# Generated by Django 5.2.16 on 2026-08-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0101_seed_canonical_missing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_override',
            field=models.ForeignKey(blank=True, help_text='Override the depreciation policy. Leave empty to use the tenant default or asset-type schedule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_overrides', to='assets.depreciation', verbose_name='Depreciation override'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode (EAN, UPC, or GTIN). Scan this barcode to view assets of this type.', max_length=14, verbose_name='EAN'),
        ),
    ]
