# Generated by Django 5.2.16 on 2026-09-01 19:35

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0101_seed_canonical_missing_status'),
        ('extras', '0114_asset_type_definition_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.CharField(max_length=62, unique=True)),
                ('release', models.CharField(max_length=64)),
                ('source_checksum', models.CharField(blank=True, max_length=71, null=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('managed_paths', models.JSONField(blank=True, default=dict)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['namespace'],
            },
            bases=(core.models.ChangeLoggingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryDefaultFieldset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['position', 'fieldset__namespace', 'fieldset__slug'],
            },
        ),
        migrations.AddField(
            model_name='assettype',
            name='configuration',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assettype',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='library_definition_key',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='library_release',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='lifecycle',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('deleted', 'Deleted')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='assettype',
            name='managed_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assettype',
            name='management_kind',
            field=models.CharField(choices=[('core', 'Core'), ('library', 'Library'), ('local', 'Local')], default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='assettype',
            name='region',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='assettype',
            name='replaced_by',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=71, null=True),
        ),
        migrations.CreateModel(
            name='AssetTypeFieldset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldset_memberships', to='assets.assettype')),
                ('fieldset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_type_memberships', to='extras.customfieldset')),
            ],
            options={
                'ordering': ['position', 'fieldset__namespace', 'fieldset__slug'],
            },
        ),
        migrations.AddField(
            model_name='assettype',
            name='custom_fieldsets',
            field=models.ManyToManyField(blank=True, related_name='composed_asset_types', through='assets.AssetTypeFieldset', to='extras.customfieldset'),
        ),
        migrations.AddField(
            model_name='assettype',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_types', to='assets.assettypelibrary'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.UniqueConstraint(condition=models.Q(('library__isnull', False)), fields=('library', 'library_definition_key'), name='unique_assettype_library_identity'),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('library__isnull', True), ('library_definition_key__isnull', True)), models.Q(('library__isnull', False), ('library_definition_key__isnull', False)), _connector='OR'), name='assettype_library_identity_complete'),
        ),
        migrations.AddField(
            model_name='categorydefaultfieldset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_fieldset_memberships', to='assets.category'),
        ),
        migrations.AddField(
            model_name='categorydefaultfieldset',
            name='fieldset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_default_memberships', to='extras.customfieldset'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_custom_fieldsets',
            field=models.ManyToManyField(blank=True, related_name='default_for_categories', through='assets.CategoryDefaultFieldset', to='extras.customfieldset'),
        ),
        migrations.AddConstraint(
            model_name='assettypefieldset',
            constraint=models.UniqueConstraint(fields=('asset_type', 'fieldset'), name='unique_assettype_fieldset'),
        ),
        migrations.AddConstraint(
            model_name='assettypefieldset',
            constraint=models.UniqueConstraint(fields=('asset_type', 'position'), name='unique_assettype_fieldset_position'),
        ),
        migrations.AddConstraint(
            model_name='assettypefieldset',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 1000000)), name='assettype_fieldset_position_range'),
        ),
        migrations.AddConstraint(
            model_name='categorydefaultfieldset',
            constraint=models.UniqueConstraint(fields=('category', 'fieldset'), name='unique_category_default_fieldset'),
        ),
        migrations.AddConstraint(
            model_name='categorydefaultfieldset',
            constraint=models.UniqueConstraint(fields=('category', 'position'), name='unique_category_default_position'),
        ),
        migrations.AddConstraint(
            model_name='categorydefaultfieldset',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 1000000)), name='category_default_position_range'),
        ),
    ]
