# Generated by Django 5.2.16 on 2026-09-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0109_alter_assettype_lifecycle'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettypefieldset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_memberships', to='assets.assettype'),
        ),
    ]
