# Generated by Django 5.2.16 on 2026-09-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0110_alter_assettypefieldset_asset_type'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydefaultfieldset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_fieldset_memberships', to='assets.category'),
        ),
    ]
