# Generated by Django 5.2.16 on 2026-09-03 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0111_alter_categorydefaultfieldset_category'),
        ('extras', '0117_alter_customfieldchoice_choice_set_and_more'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='library_definition_key',
            field=models.CharField(blank=True, max_length=127, null=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]*(?:[-_.][a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='library_release',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._+\\-]{0,63}$')]),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=71, null=True, validators=[django.core.validators.RegexValidator('^sha256:[0-9a-f]{64}$')]),
        ),
        migrations.AlterField(
            model_name='assettypelibrary',
            name='namespace',
            field=models.CharField(max_length=62, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='assettypelibrary',
            name='release',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._+\\-]{0,63}$')]),
        ),
        migrations.AlterField(
            model_name='assettypelibrary',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=71, null=True, validators=[django.core.validators.RegexValidator('^sha256:[0-9a-f]{64}$')]),
        ),
        migrations.AddConstraint(
            model_name='assettype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('management_kind', 'library'), ('library__isnull', False), ('library_definition_key__isnull', False), models.Q(('library_definition_key', ''), _negated=True), ('library_release__isnull', False), models.Q(('library_release', ''), _negated=True)), models.Q(('management_kind__in', ['core', 'local']), ('library__isnull', True), ('library_definition_key__isnull', True), ('library_release__isnull', True), ('source_checksum__isnull', True)), _connector='OR'), name='assettype_management_library_coherence'),
        ),
    ]
