# Generated by Django 5.2.16 on 2026-09-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0115_issue479_t07_provenance_bridge'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypeImageStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Stage ID')),
                ('actor_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Actor ID')),
                ('authentication_revision', models.CharField(max_length=64, verbose_name='Authentication Revision')),
                ('command_kind', models.CharField(max_length=64, verbose_name='Command Kind')),
                ('storage_key', models.CharField(max_length=255, unique=True, verbose_name='Storage Key')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='Byte Size')),
                ('content_digest', models.CharField(max_length=64, verbose_name='Content Digest')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=16, verbose_name='State')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('consumed_asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_image_stages', to='assets.assettype', verbose_name='Consumed Asset Type')),
            ],
            options={
                'verbose_name': 'Asset Type Image Stage',
                'verbose_name_plural': 'Asset Type Image Stages',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('state', 'consumed'), ('consumed_asset_type__isnull', False)), models.Q(models.Q(('state', 'consumed'), _negated=True), ('consumed_asset_type__isnull', True)), _connector='OR'), name='assettypeimagestage_consumed_link_ck')],
            },
        ),
    ]
