# Generated by Django 5.2.16 on 2026-09-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0117_issue479_final_core_vocabulary'),
        ('users', '0100_issue88_shard_62_users_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='cancellation_reason',
            field=models.TextField(blank=True, editable=False, verbose_name='Cancellation reason'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Cancelled at'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_asset_disposals', to=settings.AUTH_USER_MODEL, verbose_name='Cancelled by'),
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('asset',), name='uniq_active_disposal_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetdisposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='disposal_cancellation_coherent'),
        ),
    ]
