# Generated by Django 5.2.16 on 2026-09-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0118_assetdisposal_cancellation_reason_and_more'),
        ('users', '0100_issue88_shard_62_users_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='provider',
        ),
    ]
