# Generated by Django 5.2.17 on 2026-10-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0122_repair_maintenance_anchor"),
        ("users", "0100_issue88_shard_62_users_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetassignment",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="assetmaintenance",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="assetreservation",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
        migrations.AddField(
            model_name="warranty",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
    ]
