# Generated by Django 5.2.17 on 2026-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0100_issue88_shard_62_users_relations"),
        ("assets", "0123_asset_archive_leaf_markers"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettagsequence",
            name="archive_operation_id",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="Archive Operation"),
        ),
    ]
