"""Frozen #479 core vocabulary consumed only by migration 0106."""

CHOICE_SETS = {
    "form-factor": ("Form factor", (("desktop", "Desktop"), ("notebook", "Notebook"), ("tablet", "Tablet"), ("phone", "Phone"), ("rack", "Rack"), ("tower", "Tower"), ("blade", "Blade"), ("appliance", "Appliance"), ("peripheral", "Peripheral"), ("module", "Module"), ("other", "Other"))),
    "memory-type": ("Memory type", (("ddr3", "DDR3"), ("ddr4", "DDR4"), ("ddr5", "DDR5"), ("lpddr4x", "LPDDR4X"), ("lpddr5", "LPDDR5"), ("lpddr5x", "LPDDR5X"), ("hbm2", "HBM2"), ("hbm3", "HBM3"), ("other", "Other"))),
    "storage-medium": ("Storage medium", (("hdd", "Hard disk drive"), ("ssd", "Solid-state drive"), ("nvme_ssd", "NVMe solid-state drive"), ("flash", "Flash"), ("optical", "Optical"), ("tape", "Tape"), ("hybrid", "Hybrid"), ("other", "Other"))),
    "ethernet-speeds": ("Ethernet speeds", (("10m", "10 Mbit/s"), ("100m", "100 Mbit/s"), ("1g", "1 Gbit/s"), ("2_5g", "2.5 Gbit/s"), ("5g", "5 Gbit/s"), ("10g", "10 Gbit/s"), ("25g", "25 Gbit/s"), ("40g", "40 Gbit/s"), ("50g", "50 Gbit/s"), ("100g", "100 Gbit/s"), ("200g", "200 Gbit/s"), ("400g", "400 Gbit/s"))),
    "wifi-standards": ("Wi-Fi standards", (("802_11a", "802.11a"), ("802_11b", "802.11b"), ("802_11g", "802.11g"), ("802_11n", "802.11n"), ("802_11ac", "802.11ac"), ("802_11ax", "802.11ax"), ("802_11be", "802.11be"))),
    "network-functions": ("Network functions", (("switch", "Switch"), ("router", "Router"), ("firewall", "Firewall"), ("wlan_ap", "WLAN access point"), ("wlan_controller", "WLAN controller"), ("load_balancer", "Load balancer"), ("vpn_gateway", "VPN gateway"), ("modem", "Modem"), ("gateway", "Gateway"), ("bridge", "Bridge"))),
    "print-technology": ("Print technology", (("laser", "Laser"), ("inkjet", "Inkjet"), ("thermal", "Thermal"), ("dot_matrix", "Dot matrix"), ("dye_sublimation", "Dye sublimation"), ("solid_ink", "Solid ink"), ("other", "Other"))),
    "operating-system-family": ("Operating system family", (("windows", "Windows"), ("windows_server", "Windows Server"), ("macos", "macOS"), ("linux", "Linux"), ("chromeos", "ChromeOS"), ("ios", "iOS"), ("ipados", "iPadOS"), ("android", "Android"), ("bsd", "BSD"), ("network_os", "Network OS"), ("embedded", "Embedded"), ("other", "Other"))),
    "management-protocols": ("Management protocols", (("https", "HTTPS"), ("ssh", "SSH"), ("snmpv1", "SNMPv1"), ("snmpv2c", "SNMPv2c"), ("snmpv3", "SNMPv3"), ("redfish", "Redfish"), ("ipmi", "IPMI"), ("wsman", "WS-Man"), ("rest", "REST"), ("graphql", "GraphQL"), ("other", "Other"))),
    "sensor-types": ("Sensor types", (("temperature", "Temperature"), ("humidity", "Humidity"), ("pressure", "Pressure"), ("light", "Light"), ("motion", "Motion"), ("vibration", "Vibration"), ("current", "Current"), ("voltage", "Voltage"), ("power", "Power"), ("energy", "Energy"), ("flow", "Flow"), ("level", "Level"), ("gas", "Gas"), ("smoke", "Smoke"), ("position", "Position"), ("other", "Other"))),
    "industrial-protocols": ("Industrial protocols", (("modbus_rtu", "Modbus RTU"), ("modbus_tcp", "Modbus TCP"), ("profinet", "PROFINET"), ("profibus", "PROFIBUS"), ("ethernet_ip", "EtherNet/IP"), ("ethercat", "EtherCAT"), ("bacnet_ip", "BACnet/IP"), ("opc_ua", "OPC UA"), ("canopen", "CANopen"), ("other", "Other"))),
    "regulatory-certifications": ("Regulatory certifications", (("ce", "CE"), ("fcc", "FCC"), ("ul", "UL"), ("csa", "CSA"), ("ukca", "UKCA"), ("vcci", "VCCI"), ("rcm", "RCM"), ("eac", "EAC"), ("other", "Other"))),
    "energy-certifications": ("Energy certifications", (("energy_star", "ENERGY STAR"), ("epeat_bronze", "EPEAT Bronze"), ("epeat_silver", "EPEAT Silver"), ("epeat_gold", "EPEAT Gold"), ("80plus", "80 PLUS"), ("80plus_bronze", "80 PLUS Bronze"), ("80plus_silver", "80 PLUS Silver"), ("80plus_gold", "80 PLUS Gold"), ("80plus_platinum", "80 PLUS Platinum"), ("80plus_titanium", "80 PLUS Titanium"), ("other", "Other"))),
}

FIELDSETS = {
    "product-physical": "Product and Physical",
    "compute-memory": "Compute and Memory",
    "storage": "Storage",
    "connectivity-io": "Connectivity and I/O",
    "network-function": "Network Function",
    "power-battery": "Power and Battery",
    "display-av-imaging": "Display, AV and Imaging",
    "print-scan": "Print and Scan",
    "management-security": "Management and Security",
    "environmental-ruggedization": "Environmental and Ruggedization",
    "sensors-control": "Sensors and Control",
    "compliance-sustainability": "Compliance and Sustainability",
}


def field(key, label, scope, field_type, fieldset, position, **metadata):
    return {
        "key": key,
        "label": label,
        "scope": scope,
        "field_type": field_type,
        "fieldset": fieldset,
        "position": position,
        **metadata,
    }


FIELDS = [
    field("form_factor", "Form factor", "asset_type", "single-select", "product-physical", 10, choice_set="form-factor", max_values=1),
    field("rack_units", "Rack units", "asset_type", "decimal", "product-physical", 20, quantity_kind="length", canonical_unit="U", minimum="0", maximum="100", decimal_scale=1),
    field("weight", "Weight", "asset_type", "decimal", "product-physical", 30, quantity_kind="mass", canonical_unit="kg", minimum="0", maximum="100000", decimal_scale=3),
    field("ip_rating", "IP rating", "asset_type", "text", "product-physical", 40, regex=r"^IP[0-6X][0-9X]K?$", text_max_length=8),
    field("processor_model", "Processor model", "both", "text", "compute-memory", 10, text_max_length=255),
    field("core_count", "Core count", "both", "integer", "compute-memory", 20, quantity_kind="count", minimum="0", maximum="1048576"),
    field("memory_capacity", "Memory capacity", "both", "decimal", "compute-memory", 30, quantity_kind="digital_information", canonical_unit="GiB", minimum="0", maximum="1048576", decimal_scale=3),
    field("memory_type", "Memory type", "both", "single-select", "compute-memory", 40, choice_set="memory-type", max_values=1),
    field("storage_capacity", "Storage capacity", "both", "decimal", "storage", 10, quantity_kind="digital_information", canonical_unit="GiB", minimum="0", maximum="1073741824", decimal_scale=3),
    field("storage_medium", "Storage medium", "both", "single-select", "storage", 20, choice_set="storage-medium", max_values=1),
    field("drive_bay_count", "Drive bay count", "asset_type", "integer", "storage", 30, quantity_kind="count", minimum="0", maximum="65535"),
    field("hot_swap_supported", "Hot-swap storage", "asset_type", "boolean", "storage", 40),
    field("ethernet_port_count", "Ethernet port count", "asset_type", "integer", "connectivity-io", 10, quantity_kind="count", minimum="0", maximum="65535"),
    field("ethernet_speeds", "Ethernet speeds", "asset_type", "multi-select", "connectivity-io", 20, choice_set="ethernet-speeds", max_values=16),
    field("wifi_standards", "Wi-Fi standards", "asset_type", "multi-select", "connectivity-io", 30, choice_set="wifi-standards", max_values=8),
    field("usb_port_count", "USB port count", "asset_type", "integer", "connectivity-io", 40, quantity_kind="count", minimum="0", maximum="1024"),
    field("network_functions", "Network functions", "asset_type", "multi-select", "network-function", 10, choice_set="network-functions", max_values=10),
    field("switching_capacity", "Switching capacity", "asset_type", "decimal", "network-function", 20, quantity_kind="data_rate", canonical_unit="Gbit/s", minimum="0", maximum="1000000000", decimal_scale=3),
    field("poe_port_count", "PoE port count", "asset_type", "integer", "network-function", 30, quantity_kind="count", minimum="0", maximum="65535"),
    field("poe_budget", "PoE budget", "asset_type", "decimal", "network-function", 40, quantity_kind="power", canonical_unit="W", minimum="0", maximum="10000000", decimal_scale=3),
    field("input_voltage", "Input voltage", "asset_type", "decimal", "power-battery", 10, quantity_kind="voltage", canonical_unit="V", minimum="0", maximum="1000000", decimal_scale=3),
    field("power_consumption_max", "Maximum power consumption", "asset_type", "decimal", "power-battery", 20, quantity_kind="power", canonical_unit="W", minimum="0", maximum="100000000", decimal_scale=3),
    field("battery_capacity", "Battery capacity", "both", "decimal", "power-battery", 30, quantity_kind="energy", canonical_unit="Wh", minimum="0", maximum="10000000", decimal_scale=3),
    field("battery_runtime", "Battery runtime", "both", "integer", "power-battery", 40, quantity_kind="duration", canonical_unit="min", minimum="0", maximum="5256000"),
    field("display_size", "Display size", "asset_type", "decimal", "display-av-imaging", 10, quantity_kind="length", canonical_unit="in", minimum="0", maximum="1000", decimal_scale=2),
    field("display_resolution", "Display resolution", "asset_type", "text", "display-av-imaging", 20, regex=r"^[1-9][0-9]{1,4}x[1-9][0-9]{1,4}$", text_max_length=11),
    field("touch_supported", "Touch supported", "asset_type", "boolean", "display-av-imaging", 30),
    field("camera_resolution", "Camera resolution", "asset_type", "decimal", "display-av-imaging", 40, quantity_kind="resolution", canonical_unit="MP", minimum="0", maximum="10000", decimal_scale=2),
    field("print_technology", "Print technology", "asset_type", "single-select", "print-scan", 10, choice_set="print-technology", max_values=1),
    field("color_supported", "Color printing", "asset_type", "boolean", "print-scan", 20),
    field("duplex_supported", "Duplex printing", "asset_type", "boolean", "print-scan", 30),
    field("print_speed", "Print speed", "asset_type", "decimal", "print-scan", 40, quantity_kind="rate", canonical_unit="pages_per_minute", minimum="0", maximum="100000", decimal_scale=2),
    field("operating_system_family", "Operating system family", "both", "single-select", "management-security", 10, choice_set="operating-system-family", max_values=1),
    field("management_protocols", "Management protocols", "asset_type", "multi-select", "management-security", 20, choice_set="management-protocols", max_values=16),
    field("hostname", "Hostname", "asset", "text", "management-security", 30, text_max_length=253, validation_rule="rfc1123_hostname"),
    field("firmware_version", "Firmware version", "asset", "text", "management-security", 40, text_max_length=255),
    field("operating_temperature_min", "Minimum operating temperature", "asset_type", "decimal", "environmental-ruggedization", 10, quantity_kind="temperature", canonical_unit="°C", minimum="-273.15", maximum="1000", decimal_scale=2),
    field("operating_temperature_max", "Maximum operating temperature", "asset_type", "decimal", "environmental-ruggedization", 20, quantity_kind="temperature", canonical_unit="°C", minimum="-273.15", maximum="1000", decimal_scale=2, validation_rule="temperature_max_gte_min"),
    field("outdoor_rated", "Outdoor rated", "asset_type", "boolean", "environmental-ruggedization", 30),
    field("acoustic_level", "Acoustic level", "asset_type", "decimal", "environmental-ruggedization", 40, quantity_kind="sound_pressure", canonical_unit="dBA", minimum="0", maximum="250", decimal_scale=2),
    field("sensor_types", "Sensor types", "asset_type", "multi-select", "sensors-control", 10, choice_set="sensor-types", max_values=32),
    field("analog_input_count", "Analog input count", "asset_type", "integer", "sensors-control", 20, quantity_kind="count", minimum="0", maximum="65535"),
    field("digital_input_count", "Digital input count", "asset_type", "integer", "sensors-control", 30, quantity_kind="count", minimum="0", maximum="65535"),
    field("industrial_protocols", "Industrial protocols", "asset_type", "multi-select", "sensors-control", 40, choice_set="industrial-protocols", max_values=16),
    field("regulatory_certifications", "Regulatory certifications", "asset_type", "multi-select", "compliance-sustainability", 10, choice_set="regulatory-certifications", max_values=16),
    field("rohs_compliant", "RoHS compliant", "asset_type", "boolean", "compliance-sustainability", 20),
    field("energy_certifications", "Energy certifications", "asset_type", "multi-select", "compliance-sustainability", 30, choice_set="energy-certifications", max_values=16),
    field("country_of_origin", "Country of origin", "asset_type", "text", "compliance-sustainability", 40, regex=r"^[A-Z]{2}$", text_max_length=2),
]

CATEGORY_FIELDSETS = {
    "laptops": ("product-physical", "compute-memory", "storage", "connectivity-io", "display-av-imaging", "management-security", "compliance-sustainability"),
    "desktops": ("product-physical", "compute-memory", "storage", "connectivity-io", "management-security", "compliance-sustainability"),
    "servers": ("product-physical", "compute-memory", "storage", "connectivity-io", "network-function", "power-battery", "management-security", "compliance-sustainability"),
    "storage-devices": ("product-physical", "compute-memory", "storage", "connectivity-io", "power-battery", "management-security", "compliance-sustainability"),
    "mobile-phones": ("product-physical", "compute-memory", "storage", "connectivity-io", "power-battery", "display-av-imaging", "management-security", "compliance-sustainability"),
    "tablets": ("product-physical", "compute-memory", "storage", "connectivity-io", "power-battery", "display-av-imaging", "management-security", "compliance-sustainability"),
    "network-devices": ("product-physical", "connectivity-io", "network-function", "power-battery", "management-security", "environmental-ruggedization", "compliance-sustainability"),
    "monitors": ("product-physical", "connectivity-io", "power-battery", "display-av-imaging", "compliance-sustainability"),
    "conference-systems": ("product-physical", "connectivity-io", "power-battery", "display-av-imaging", "management-security", "compliance-sustainability"),
}
