# Generated by Django 5.2.15 on 2026-06-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_assetassignment_assigned_asset_and_more'),
        ('licenses', '0002_license_supplier'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to='organization.assetholder'),
        ),
    ]
