# Generated by Django 5.2.15 on 2026-06-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_remove_assetassignment_exactly_one_assignment_target_and_more'),
        ('licenses', '0003_alter_licenseseatassignment_asset_and_more'),
        ('organization', '0010_assetholder_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenseseatassignment',
            name='chk_assignment_to_one_target',
        ),
        migrations.AddConstraint(
            model_name='licenseseatassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('assigned_holder__isnull', True)), models.Q(('asset__isnull', True), ('assigned_holder__isnull', False)), models.Q(('asset__isnull', True), ('assigned_holder__isnull', True)), _connector='OR'), name='chk_assignment_to_one_target'),
        ),
    ]
