# Generated by Django 5.2.15 on 2026-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_remove_licenseseatassignment_chk_assignment_to_one_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseseatassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
