# Generated by Django 5.2.15 on 2026-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_licenseseatassignment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data'),
        ),
    ]
