# Generated by Django 5.2.15 on 2026-06-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_license_custom_field_data'),
        ('subscriptions', '0010_subscription_custom_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Optional subscription (billing agreement) that funds this license; seats roll up to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='subscriptions.subscription'),
        ),
    ]
