# Generated by Django 5.2.15 on 2026-06-14 12:14

import django.db.models.deletion
from django.db import migrations, models


def drop_orphan_seat_assignments(apps, schema_editor):
    """Delete seat assignments targeting neither an asset nor a holder.

    These rows were always invalid per LicenseSeatAssignment.clean(), but the
    old CheckConstraint permitted them at the DB level. The tightened
    constraint below forbids them, so purge any legacy/orphan rows first
    (including soft-deleted ones — a CheckConstraint applies to every row).
    """
    LicenseSeatAssignment = apps.get_model('licenses', 'LicenseSeatAssignment')
    LicenseSeatAssignment.objects.filter(
        asset__isnull=True, assigned_holder__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_asset_uniq_active_tenant_serial'),
        ('licenses', '0007_license_subscription'),
        ('organization', '0016_currency_callable_default'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licenseseatassignment',
            name='chk_assignment_to_one_target',
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='licenses.license'),
        ),
        migrations.RunPython(
            drop_orphan_seat_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='licenseseatassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('assigned_holder__isnull', True)), models.Q(('asset__isnull', True), ('assigned_holder__isnull', False)), _connector='OR'), name='chk_assignment_to_one_target'),
        ),
    ]
