# Generated by Django 5.2.15 on 2026-06-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_asset_uniq_active_tenant_serial'),
        ('licenses', '0008_remove_licenseseatassignment_chk_assignment_to_one_target_and_more'),
        ('organization', '0017_remove_assetholder_unique_tenant_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='organization.assetholder'),
        ),
    ]
