# Generated by Django 5.2.15 on 2026-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_alter_licenseseatassignment_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.CharField(blank=True, help_text="Optional version constraint for this license entitlement (e.g. '2021', '16.x'). Informational only — reconciliation is performed at the Software level (version-agnostic).", max_length=100),
        ),
    ]
