# Generated by Django 5.2.15 on 2026-06-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_license_currency_license_version'),
        ('organization', '0018_costcenter'),
        ('software', '0009_software_tenant_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='organization.costcenter'),
        ),
        migrations.AddField(
            model_name='licenseseatassignment',
            name='installed_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_seats', to='software.installedsoftware'),
        ),
    ]
