# Generated by Django 5.2.15 on 2026-06-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0053_alter_asset_asset_role_alter_asset_asset_tag_and_more'),
        ('extras', '0035_alter_alertlog_acknowledged_by_and_more'),
        ('licenses', '0011_license_cost_center_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('software', '0010_alter_installedsoftware_asset_and_more'),
        ('subscriptions', '0014_alter_provider_name_alter_provider_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='organization.costcenter', verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(blank=True, db_index=True, help_text='For term licenses or maintenance', null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(choices=[('perpetual_seat', 'Perpetual Seat'), ('subscription_seat', 'Subscription Seat')], db_index=True, default='perpetual_seat', max_length=50, verbose_name='License Type'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(help_text='Descriptive name for the license (e.g., Visio Pro 2021 - EA Renewal FY24)', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='license',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_key',
            field=models.TextField(blank=True, help_text='Product key or activation code. Consider security implications.', verbose_name='Product Key'),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='seats',
            field=models.PositiveIntegerField(default=1, help_text='Total number of seats purchased or entitled', verbose_name='Seats'),
        ),
        migrations.AlterField(
            model_name='license',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='software.software', verbose_name='Software'),
        ),
        migrations.AlterField(
            model_name='license',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Optional subscription (billing agreement) that funds this license; seats roll up to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='subscriptions.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='license',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='assets.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='license',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='licenses', to='extras.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='license',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='organization.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='license',
            name='version',
            field=models.CharField(blank=True, help_text="Optional version constraint for this license entitlement (e.g. '2021', '16.x'). Informational only — reconciliation is performed at the Software level (version-agnostic).", max_length=100, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='assigned_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='installed_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_seats', to='software.installedsoftware', verbose_name='Installed Software'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='licenses.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='licenseseatassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
