# Generated by Django 5.2.15 on 2026-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0055_assettype_ean'),
        ('licenses', '0012_alter_license_cost_center_and_more'),
        ('organization', '0019_alter_assetholder_comments_and_more'),
        ('software', '0010_alter_installedsoftware_asset_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licenseseatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('deleted_at__isnull', True)), fields=('license', 'asset'), name='unique_active_license_seat_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='licenseseatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_holder__isnull', False), ('deleted_at__isnull', True)), fields=('license', 'assigned_holder'), name='unique_active_license_seat_per_holder'),
        ),
    ]
