# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('licenses', '0001_initial'),
        ('licenses', '0002_license_supplier'),
    ]

    dependencies = [
        ('assets', '0100_issue88_shard_10_assets_history_1'),
    ]

    operations = [
        migrations.CreateModel(
                    name='License',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('custom_field_data', models.JSONField(blank=True, default=dict, verbose_name='Custom Field Data')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(help_text='Descriptive name for the license (e.g., Visio Pro 2021 - EA Renewal FY24)', max_length=255, verbose_name='Name')),
                        ('license_type', models.CharField(choices=[('perpetual_seat', 'Perpetual Seat'), ('subscription_seat', 'Subscription Seat')], db_index=True, default='perpetual_seat', max_length=50, verbose_name='License Type')),
                        ('product_key', models.TextField(blank=True, help_text='Product key or activation code. Consider security implications.', verbose_name='Product Key')),
                        ('seats', models.PositiveIntegerField(default=1, help_text='Total number of seats purchased or entitled', verbose_name='Seats')),
                        ('purchase_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Purchase Date')),
                        ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Cost')),
                        ('currency', models.CharField(blank=True, choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('CAD', 'Canadian Dollar (CA$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)')], default='', help_text='ISO 4217 code. Leave blank to use the tenant default currency.', max_length=3, verbose_name='Currency')),
                        ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Order Number')),
                        ('version', models.CharField(blank=True, help_text="Optional version constraint for this license entitlement (e.g. '2021', '16.x'). Informational only — reconciliation is performed at the Software level (version-agnostic).", max_length=100, verbose_name='Version')),
                        ('expiration_date', models.DateField(blank=True, db_index=True, help_text='For term licenses or maintenance', null=True, verbose_name='Expiration Date')),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'License',
                        'verbose_name_plural': 'Licenses',
                        'ordering': ('software__manufacturer', 'software__name', 'name'),
                    },
                    bases=(core.mixins.BookmarkableMixin, core.mixins.TaggableMixin, core.mixins.ExportableMixin, core.mixins.CloneableMixin, core.models.ChangeLoggingMixin, models.Model),
                ),
        migrations.CreateModel(
                    name='LicenseSeatAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('assigned_date', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, verbose_name='Notes')),
                    ],
                    options={
                        'verbose_name': 'License Seat Assignment',
                        'verbose_name_plural': 'License Seat Assignments',
                        'ordering': ('license', 'asset', 'assigned_holder'),
                    },
                    bases=(core.models.ChangeLoggingMixin, models.Model),
                ),
    ]
