# Generated by Django 5.2.16 for ITAMbox issue #88.

import core.mixins
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('licenses', '0003_alter_licenseseatassignment_asset_and_more'),
        ('licenses', '0004_remove_licenseseatassignment_chk_assignment_to_one_target_and_more'),
        ('licenses', '0005_licenseseatassignment_deleted_at_and_more'),
        ('licenses', '0006_license_custom_field_data'),
        ('licenses', '0007_license_subscription'),
        ('licenses', '0008_remove_licenseseatassignment_chk_assignment_to_one_target_and_more'),
        ('licenses', '0009_alter_licenseseatassignment_asset_and_more'),
        ('licenses', '0010_license_currency_license_version'),
        ('licenses', '0011_license_cost_center_and_more'),
        ('licenses', '0012_alter_license_cost_center_and_more'),
        ('licenses', '0013_licenseseatassignment_unique_active_license_seat_per_asset_and_more'),
    ]

    dependencies = [
        ('subscriptions', '0100_issue88_shard_47_subscriptions_relations'),
        ('licenses', '0100_issue88_shard_11_licenses_schema'),
    ]

    operations = [
        migrations.AddField(
                    model_name='license',
                    name='cost_center',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='organization.costcenter', verbose_name='Cost Center'),
                ),
        migrations.AddField(
                    model_name='license',
                    name='software',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='software.software', verbose_name='Software'),
                ),
        migrations.AddField(
                    model_name='license',
                    name='subscription',
                    field=models.ForeignKey(blank=True, help_text='Optional subscription (billing agreement) that funds this license; seats roll up to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='subscriptions.subscription', verbose_name='Subscription'),
                ),
        migrations.AddField(
                    model_name='license',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='assets.supplier', verbose_name='Supplier'),
                ),
        migrations.AddField(
                    model_name='license',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='licenses', to='extras.tag', verbose_name='Tags'),
                ),
        migrations.AddField(
                    model_name='license',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='organization.tenant', verbose_name='Tenant'),
                ),
        migrations.AddField(
                    model_name='licenseseatassignment',
                    name='asset',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='assets.asset', verbose_name='Asset'),
                ),
        migrations.AddField(
                    model_name='licenseseatassignment',
                    name='assigned_holder',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='organization.assetholder', verbose_name='Assigned Holder'),
                ),
        migrations.AddField(
                    model_name='licenseseatassignment',
                    name='installed_software',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_seats', to='software.installedsoftware', verbose_name='Installed Software'),
                ),
        migrations.AddField(
                    model_name='licenseseatassignment',
                    name='license',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='licenses.license', verbose_name='License'),
                ),
        migrations.AddConstraint(
                    model_name='licenseseatassignment',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('assigned_holder__isnull', True)), models.Q(('asset__isnull', True), ('assigned_holder__isnull', False)), _connector='OR'), name='chk_assignment_to_one_target'),
                ),
        migrations.AddConstraint(
                    model_name='licenseseatassignment',
                    constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('deleted_at__isnull', True)), fields=('license', 'asset'), name='unique_active_license_seat_per_asset'),
                ),
        migrations.AddConstraint(
                    model_name='licenseseatassignment',
                    constraint=models.UniqueConstraint(condition=models.Q(('assigned_holder__isnull', False), ('deleted_at__isnull', True)), fields=('license', 'assigned_holder'), name='unique_active_license_seat_per_holder'),
                ),
    ]
