# Generated by Django 5.2.16 on 2026-08-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0100_issue88_shard_48_licenses_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='version',
            field=models.CharField(blank=True, help_text="Optional version constraint for this license entitlement (e.g. '2021', '16.x'). Reconciliation ignores the version and runs at the Software level.", max_length=100, verbose_name='Version'),
        ),
    ]
